import type { Step } from "./types.js";

export const STEPS: Step[] = [
  {
    id: "intro",
    kind: "info",
    mood: "wave",
    title: "Oi, que bom te ver por aqui! 🦜",
    text: "Eu sou a Pia, sua mentora aqui na Colaborativa. Vou te acompanhar em cada passo — sem pressa e sem complicação. Em menos de 2 minutinhos a gente monta seu plano juntos. Bora?",
  },
  {
    id: "experiencia",
    kind: "choice",
    field: "experienceLevel",
    mood: "think",
    title: "Pra começar: como é sua relação com IA hoje?",
    text: "Não tem resposta certa nem errada — é só pra eu falar a sua língua daqui pra frente. 😉",
    options: [
      { value: "iniciante", label: "Tô só começando", desc: "Mal mexi com IA ainda, e tá tudo bem!" },
      { value: "intermediario", label: "Já me viro", desc: "Uso o Claude/ChatGPT no dia a dia" },
      { value: "avancado", label: "Sou casca-grossa", desc: "Já construo coisas com a API" },
    ],
  },
  {
    id: "cert",
    kind: "choice",
    field: "targetCertSlug",
    source: "certs",
    mood: "talk",
    title: "Agora escolhe por onde começar 🧭",
    text: "Cada trilha te leva a uma certificação. Vou te explicar todas em português claro — e relaxa: dá pra trocar depois quando quiser. Se você está começando agora, a AI Fluency é um colo quentinho pra entrar no assunto.",
  },
  {
    id: "meta",
    kind: "choice",
    field: "dailyGoalMin",
    mood: "talk",
    title: "Quanto tempo dá pra dedicar por dia?",
    text: "Cinco minutinhos por dia já fazem milagre — o segredo é a constância, não a maratona. 🔥 Você ajusta isso quando quiser.",
    options: [
      { value: "5", label: "5 min", desc: "Tô de passagem" },
      { value: "10", label: "10 min", desc: "No meu ritmo" },
      { value: "15", label: "15 min", desc: "Comprometido(a)" },
      { value: "20", label: "20 min", desc: "Bora pra cima!" },
    ],
  },
  {
    id: "startup",
    kind: "input",
    field: "startupName",
    mood: "talk",
    title: "Agora a parte divertida: sua startup de IA 🚀",
    text: "Enquanto você estuda, constrói uma empresa de IA fictícia — cada lição que você manda bem faz ela crescer e valer mais. Que nome a gente dá pra ela?",
    placeholder: "Ex.: NeuraLabs",
    prefillFromName: true,
  },
  {
    id: "sample",
    kind: "sample",
    mood: "think",
    title: "Vamo experimentar uma questão? 😋",
    text: "É só uma palhinha pra você sentir como funciona — não vale nota e não tem como errar feio. Escolhe a que te parecer mais certa:",
  },
  {
    id: "fim",
    kind: "celebrate",
    mood: "cheer",
    title: "Prontinho, tô orgulhosa de você! 🎉",
    text: "Seu plano tá montado! Vou te levar pra sua trilha agora — é só seguir os passos. Quando quiser rever isso, é só clicar em “Refazer onboarding”. Tô aqui com você! 💚",
  },
];
