import type { CertificationPack } from "./pack.js";

// "AI Fluency: Framework & Foundations" — trilha oficial da Anthropic Academy.
//
// Conteúdo em português (pt-BR) baseado na trilha pública da Anthropic Academy
// (anthropic.com/ai-fluency, que redireciona para anthropic.skilljar.com). O
// framework central são os 4 Ds: Delegation, Description, Discernment e
// Diligence. Cada lição aponta para a leitura oficial via "> Leitura oficial:".
//
// Convenção de tags (kebab-case): "ai-fluency" sempre presente; mais um marcador
// de tema, ex. "4d", "delegation", "description", "discernment", "diligence",
// "genai", "prompting", "etica".

export const aiFluency: CertificationPack = {
  slug: "ai-fluency",
  title: "AI Fluency: Framework & Foundations (Anthropic Academy)",
  description:
    "Trilha oficial da Anthropic Academy sobre fluência em IA: como colaborar com sistemas de IA de forma eficaz, ética e segura, usando o framework dos 4 Ds (Delegation, Description, Discernment, Diligence).",
  version: 1,
  modules: [
    // =====================================================================
    // MÓDULO 1 — FUNDAMENTOS DA FLUÊNCIA EM IA
    // =====================================================================
    {
      title: "Fundamentos da fluência em IA",
      lessons: [
        {
          title: "O que é fluência em IA e por que ela importa",
          readingMd: [
            "# O que é fluência em IA e por que ela importa",
            "",
            "**Fluência em IA** é a capacidade de **colaborar com sistemas de inteligência artificial de forma eficaz, eficiente, ética e segura**. Não se trata apenas de saber clicar em uma ferramenta ou decorar comandos: trata-se de desenvolver um conjunto de competências que permitem trabalhar *com* a IA como uma parceira de raciocínio, e não apenas usá-la como uma caixa-preta.",
            "",
            "## Uma analogia: aprender um novo idioma",
            "",
            "Pense na diferença entre **saber algumas palavras** de um idioma e **ser fluente** nele. Quem sabe poucas palavras consegue pedir um café, mas trava em uma conversa real. Quem é fluente entende nuances, adapta o tom ao contexto, percebe quando foi mal interpretado e se corrige. A fluência em IA é análoga: muita gente sabe \"pedir um café\" para um modelo (\"resuma este texto\"), mas poucos sabem conduzir uma colaboração rica, iterativa e confiável.",
            "",
            "## As quatro qualidades de uma boa colaboração",
            "",
            "A trilha define quatro qualidades que distinguem uma colaboração fluente:",
            "",
            "- **Eficaz (effective)** — você obtém resultados que realmente atendem ao seu objetivo.",
            "- **Eficiente (efficient)** — você chega lá com bom uso de tempo e esforço, sem retrabalho infinito.",
            "- **Ética (ethical)** — você usa a IA de forma responsável, respeitando pessoas, direitos e a verdade.",
            "- **Segura (safe)** — você evita danos, protege informações sensíveis e mantém controle sobre decisões importantes.",
            "",
            "## Por que isso importa agora",
            "",
            "Sistemas de IA generativa como o Claude estão se tornando ferramentas de uso geral em escrita, análise, programação, pesquisa e tomada de decisão. Quem desenvolve fluência consegue **ampliar suas próprias capacidades** sem terceirizar o julgamento. Quem não a desenvolve corre dois riscos opostos: **subutilizar** a tecnologia (usando-a só para tarefas triviais) ou **confiar demais** nela (aceitando saídas erradas sem verificar).",
            "",
            "A fluência em IA é uma habilidade **transferível**: não fica obsoleta a cada novo modelo. As ferramentas mudam, mas o modo de pensar a colaboração permanece.",
            "",
            "> Leitura oficial: https://www.anthropic.com/ai-fluency",
          ].join("\n"),
          flashcards: [
            {
              front: "Defina fluência em IA.",
              back: "A capacidade de colaborar com sistemas de IA de forma eficaz, eficiente, ética e segura — trabalhar COM a IA, não apenas usá-la como caixa-preta.",
              tags: ["ai-fluency", "fundamentos"],
            },
            {
              front: "Quais são as quatro qualidades de uma colaboração fluente com IA?",
              back: "Eficaz (atinge o objetivo), Eficiente (bom uso de tempo/esforço), Ética (uso responsável) e Segura (evita danos e protege informações).",
              tags: ["ai-fluency", "fundamentos"],
            },
            {
              front: "Por que a fluência em IA é descrita como uma habilidade transferível?",
              back: "Porque ela é um modo de pensar a colaboração que não fica obsoleto a cada novo modelo. As ferramentas mudam, mas as competências permanecem úteis.",
              tags: ["ai-fluency", "fundamentos"],
            },
            {
              front: "Quais são os dois riscos opostos de quem não desenvolve fluência em IA?",
              back: "Subutilizar a IA (usá-la só para tarefas triviais) ou confiar demais nela (aceitar saídas erradas sem verificação crítica).",
              tags: ["ai-fluency", "fundamentos"],
            },
          ],
          questions: [
            {
              prompt: "Qual definição melhor descreve 'fluência em IA' segundo a trilha?",
              options: [
                "Saber quais botões clicar em uma ferramenta de IA",
                "Memorizar o maior número possível de prompts prontos",
                "Colaborar com sistemas de IA de forma eficaz, eficiente, ética e segura",
                "Ser capaz de programar modelos de IA do zero",
              ],
              correctIndex: 2,
              explanation:
                "Fluência em IA é uma competência de colaboração — eficaz, eficiente, ética e segura — não apenas operar uma ferramenta ou decorar prompts.",
              difficulty: 1,
              tags: ["ai-fluency", "fundamentos"],
            },
            {
              prompt:
                "As quatro qualidades de uma colaboração fluente são eficaz, eficiente, ética e:",
              options: ["rápida", "barata", "segura", "automática"],
              correctIndex: 2,
              explanation:
                "As quatro qualidades são: eficaz, eficiente, ética e segura. 'Segura' enfatiza evitar danos e proteger informações.",
              difficulty: 1,
              tags: ["ai-fluency", "fundamentos"],
            },
            {
              prompt:
                "Por que a fluência em IA é considerada 'transferível' e relativamente durável?",
              options: [
                "Porque cada modelo novo exige reaprender tudo do zero",
                "Porque é um modo de pensar a colaboração que sobrevive à troca de ferramentas",
                "Porque depende apenas de uma ferramenta específica",
                "Porque substitui a necessidade de julgamento humano",
              ],
              correctIndex: 1,
              explanation:
                "As ferramentas e modelos mudam, mas as competências de colaboração (os 4 Ds) continuam aplicáveis — por isso a habilidade é transferível.",
              difficulty: 2,
              tags: ["ai-fluency", "fundamentos"],
            },
          ],
          labs: [
            {
              title: "Autoavaliação da sua colaboração com IA",
              promptMd: [
                "# Lab: autoavaliação da sua colaboração com IA",
                "",
                "Escolha **uma tarefa recente** em que você usou (ou poderia ter usado) uma IA generativa. Avalie sua colaboração nas quatro qualidades da fluência.",
                "",
                "Para cada qualidade, escreva 2-3 frases:",
                "1. **Eficaz** — o resultado atendeu ao seu objetivo? Como você soube?",
                "2. **Eficiente** — houve retrabalho? O que poderia ter encurtado o caminho?",
                "3. **Ética** — havia alguma questão de autoria, direitos ou verdade envolvida?",
                "4. **Segura** — havia informação sensível? Você manteve controle sobre a decisão final?",
                "",
                "Conclua com **uma melhoria concreta** que você adotaria na próxima vez.",
              ].join("\n"),
              rubric: [
                "Aborda explicitamente as quatro qualidades (eficaz, eficiente, ética, segura).",
                "Usa uma tarefa real e concreta como base, não exemplos genéricos.",
                "A análise de 'ética' e 'segura' menciona pelo menos um risco real (autoria, verdade, dados sensíveis ou controle da decisão).",
                "Termina com pelo menos uma melhoria acionável para a próxima colaboração.",
              ],
              modelAnswer: [
                "## Tarefa escolhida: redigir o e-mail de proposta para um cliente",
                "",
                "**Eficaz.** O rascunho gerado cobriu os pontos certos (escopo, prazo, preço), mas usei um tom genérico. Soube que atendeu ao objetivo porque o cliente respondeu pedindo apenas um pequeno ajuste de prazo — sinal de que a mensagem ficou clara.",
                "",
                "**Eficiente.** Houve algum retrabalho: na primeira tentativa não dei contexto sobre o cliente, então o texto saiu impessoal. Dar esse contexto logo de início teria economizado duas iterações.",
                "",
                "**Ética.** A proposta continha um compromisso comercial — eu precisava garantir que cada número fosse verdadeiro e que eu, não a IA, assumisse a responsabilidade pelo que foi prometido. Revisei cada valor antes de enviar.",
                "",
                "**Segura.** O e-mail tinha o nome e a dor específica do cliente. Removi qualquer dado que não fosse necessário e mantive a decisão final (enviar ou não) comigo.",
                "",
                "**Melhoria para a próxima vez:** começar todo rascunho dando 3 linhas de contexto sobre o destinatário e o objetivo, e reservar um passo explícito de verificação dos fatos antes de enviar.",
              ].join("\n"),
            },
          ],
        },
        {
          title: "O que é IA generativa e LLMs em alto nível",
          readingMd: [
            "# O que é IA generativa e LLMs em alto nível",
            "",
            "Para colaborar bem, você não precisa entender a matemática interna dos modelos — mas precisa de um **modelo mental correto** de como eles funcionam e onde falham.",
            "",
            "## O que é IA generativa",
            "",
            "**IA generativa** é uma classe de sistemas capazes de **produzir conteúdo novo** — texto, código, imagens, áudio — em vez de apenas classificar ou recuperar algo pronto. Os sistemas baseados em texto, como o Claude, são **Large Language Models (LLMs)**: modelos de linguagem treinados em enormes volumes de texto.",
            "",
            "## Como um LLM 'pensa', em alto nível",
            "",
            "Um LLM aprende padrões estatísticos da linguagem e, dado um contexto, **prevê a próxima porção de texto mais plausível**, repetidamente, até formar uma resposta. Uma boa analogia: é como um **músico de jazz** que internalizou milhares de músicas e improvisa uma frase coerente com o que veio antes — não está \"lembrando\" uma resposta fixa, está *gerando* uma continuação provável.",
            "",
            "Isso explica duas coisas importantes:",
            "- A mesma pergunta pode gerar **respostas diferentes** (há variação na geração).",
            "- O modelo é guiado pelo **contexto que você fornece**: prompts melhores levam a continuações melhores.",
            "",
            "## Capacidades",
            "",
            "LLMs modernos são bons em: resumir, reescrever, traduzir, explicar, brainstorm, estruturar texto, escrever e revisar código, extrair informação e raciocinar passo a passo sobre problemas descritos em linguagem natural.",
            "",
            "## Limitações que você precisa internalizar",
            "",
            "- **Alucinação** — o modelo pode produzir afirmações que *soam* corretas mas são falsas, porque ele otimiza plausibilidade, não verdade.",
            "- **Conhecimento com data de corte** — ele não \"sabe\" eventos posteriores ao seu treinamento, a menos que você forneça a informação.",
            "- **Sem acesso ao mundo por padrão** — não navega na internet nem acessa seus arquivos a menos que conectado a ferramentas para isso.",
            "- **Sensibilidade ao contexto** — instruções ambíguas geram saídas ambíguas. O modelo não \"adivinha\" a intenção que você não escreveu.",
            "- **Vieses** — reflete padrões (inclusive vieses) presentes nos dados em que foi treinado.",
            "",
            "Entender essas limitações é o que separa o uso ingênuo do uso fluente.",
            "",
            "> Leitura oficial: https://www.anthropic.com/ai-fluency",
          ].join("\n"),
          flashcards: [
            {
              front: "O que distingue IA 'generativa' de outros tipos de IA?",
              back: "Ela produz conteúdo novo (texto, código, imagem, áudio) em vez de apenas classificar ou recuperar algo já existente.",
              tags: ["ai-fluency", "genai"],
            },
            {
              front: "Em alto nível, como um LLM produz uma resposta?",
              back: "Aprendendo padrões da linguagem e prevendo repetidamente a próxima porção de texto mais plausível, guiado pelo contexto fornecido.",
              tags: ["ai-fluency", "genai"],
            },
            {
              front: "O que é alucinação em um LLM?",
              back: "Quando o modelo produz uma afirmação que soa correta mas é falsa, porque ele otimiza plausibilidade do texto, não a verdade factual.",
              tags: ["ai-fluency", "genai"],
            },
            {
              front: "Por que um LLM não 'sabe' sobre eventos muito recentes?",
              back: "Seu conhecimento tem uma data de corte (o fim do treinamento). Ele só conhece eventos posteriores se você fornecer a informação no contexto.",
              tags: ["ai-fluency", "genai"],
            },
          ],
          questions: [
            {
              prompt: "Qual descrição reflete melhor como um LLM gera texto?",
              options: [
                "Ele busca a resposta exata em um banco de dados e a copia",
                "Ele prevê a próxima porção de texto mais plausível, guiado pelo contexto",
                "Ele consulta a internet em tempo real para toda resposta",
                "Ele aplica regras gramaticais fixas escritas por humanos",
              ],
              correctIndex: 1,
              explanation:
                "Um LLM gera prevendo continuações plausíveis a partir de padrões aprendidos e do contexto — não copia de um banco nem consulta a internet por padrão.",
              difficulty: 1,
              tags: ["ai-fluency", "genai"],
            },
            {
              prompt:
                "Um modelo afirma com confiança que um livro foi escrito por um autor que nunca o escreveu. Como se chama esse fenômeno?",
              options: ["Viés", "Data de corte", "Alucinação", "Streaming"],
              correctIndex: 2,
              explanation:
                "Produzir uma afirmação plausível porém falsa é uma alucinação — o modelo otimiza plausibilidade do texto, não a verdade.",
              difficulty: 1,
              tags: ["ai-fluency", "genai"],
            },
            {
              prompt:
                "Você pergunta a um LLM sobre um acontecimento de ontem e ele não sabe responder. Qual é a explicação mais provável?",
              options: [
                "O modelo está quebrado",
                "Eventos recentes podem estar além da data de corte do treinamento, e nenhuma fonte foi fornecida no contexto",
                "LLMs nunca conseguem responder perguntas factuais",
                "Você usou temperatura muito baixa",
              ],
              correctIndex: 1,
              explanation:
                "Sem acesso a ferramentas externas, o conhecimento do modelo é limitado à sua data de corte; para eventos recentes é preciso fornecer a informação no contexto.",
              difficulty: 2,
              tags: ["ai-fluency", "genai"],
            },
            {
              prompt: "Qual destas NÃO é, por padrão, uma capacidade de um LLM isolado?",
              options: [
                "Resumir um texto que você cola no prompt",
                "Reescrever um parágrafo em outro tom",
                "Acessar seus arquivos locais e a internet sem nenhuma integração",
                "Explicar um conceito passo a passo",
              ],
              correctIndex: 2,
              explanation:
                "Por padrão o modelo não acessa arquivos nem a internet — isso só ocorre quando ele é conectado a ferramentas/integrações.",
              difficulty: 2,
              tags: ["ai-fluency", "genai"],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // MÓDULO 2 — O FRAMEWORK DOS 4 Ds
    // =====================================================================
    {
      title: "O framework dos 4 Ds",
      lessons: [
        {
          title: "Visão geral do framework dos 4 Ds",
          readingMd: [
            "# Visão geral do framework dos 4 Ds",
            "",
            "O coração da trilha é o **framework dos 4 Ds**, quatro competências que, juntas, descrevem o que significa colaborar bem com IA:",
            "",
            "1. **Delegation (Delegação)** — decidir **o que** entregar à IA, o que fazer você mesmo e como dividir o trabalho.",
            "2. **Description (Descrição)** — **comunicar** à IA o que você quer: tarefa, contexto, formato e processo desejados.",
            "3. **Discernment (Discernimento)** — **avaliar criticamente** o que a IA produziu, como ela chegou lá e como ela se comportou.",
            "4. **Diligence (Diligência)** — agir de forma **responsável**: transparência, verificação, ética e segurança ao usar e divulgar o trabalho.",
            "",
            "## Como os 4 Ds se encaixam",
            "",
            "Pense em uma colaboração com um **profissional muito capaz, mas que não te conhece**. Você precisa: decidir o que pedir (Delegation), explicar bem o pedido (Description), revisar criticamente a entrega (Discernment) e usar o resultado com responsabilidade (Diligence). Os 4 Ds tornam esse instinto explícito e treinável.",
            "",
            "## Não é estritamente linear",
            "",
            "Embora seja natural pensar nos 4 Ds em sequência, na prática você **circula** entre eles. Em especial, **Description e Discernment formam um laço**: você descreve, avalia o resultado, refina a descrição, avalia de novo. Esse é o **laço Descrição–Discernimento**, que veremos em detalhe.",
            "",
            "A **Diligence** atravessa tudo: ela não é só o último passo, é uma postura que acompanha cada decisão — desde escolher o que delegar até decidir como divulgar o resultado.",
            "",
            "> Leitura oficial: https://www.anthropic.com/ai-fluency",
          ].join("\n"),
          flashcards: [
            {
              front: "Quais são os 4 Ds da fluência em IA?",
              back: "Delegation (delegação), Description (descrição), Discernment (discernimento) e Diligence (diligência).",
              tags: ["ai-fluency", "4d"],
            },
            {
              front: "Em uma frase, o que é Delegation?",
              back: "Decidir o que entregar à IA, o que fazer você mesmo e como dividir o trabalho entre humano e máquina.",
              tags: ["ai-fluency", "4d", "delegation"],
            },
            {
              front: "O que é o laço Descrição–Discernimento?",
              back: "O ciclo de descrever uma tarefa à IA, avaliar criticamente o resultado e refinar a descrição — repetidamente — até chegar a um bom resultado.",
              tags: ["ai-fluency", "4d", "description", "discernment"],
            },
            {
              front: "Por que se diz que a Diligence 'atravessa' os outros 3 Ds?",
              back: "Porque ser responsável (transparência, verificação, ética, segurança) é uma postura presente em cada decisão, não apenas um passo final.",
              tags: ["ai-fluency", "4d", "diligence"],
            },
          ],
          questions: [
            {
              prompt: "Qual sequência lista corretamente os 4 Ds?",
              options: [
                "Delegation, Description, Discernment, Diligence",
                "Design, Develop, Deploy, Deliver",
                "Decide, Draft, Debug, Document",
                "Data, Description, Decision, Deployment",
              ],
              correctIndex: 0,
              explanation:
                "Os 4 Ds são Delegation, Description, Discernment e Diligence.",
              difficulty: 1,
              tags: ["ai-fluency", "4d"],
            },
            {
              prompt: "Qual par de Ds forma um 'laço' iterativo na prática?",
              options: [
                "Delegation e Diligence",
                "Description e Discernment",
                "Delegation e Description",
                "Discernment e Diligence",
              ],
              correctIndex: 1,
              explanation:
                "Description e Discernment formam o laço Descrição–Discernimento: descrever, avaliar e refinar repetidamente.",
              difficulty: 2,
              tags: ["ai-fluency", "4d", "description", "discernment"],
            },
            {
              prompt:
                "Decidir que VOCÊ deve escrever a conclusão emocional de um discurso, mas pedir à IA o rascunho da parte factual, é principalmente um exercício de qual D?",
              options: ["Description", "Discernment", "Delegation", "Diligence"],
              correctIndex: 2,
              explanation:
                "Dividir o trabalho entre o que cabe ao humano e o que cabe à IA é o núcleo da Delegation.",
              difficulty: 2,
              tags: ["ai-fluency", "4d", "delegation"],
            },
          ],
        },
        {
          title: "Delegation: o que delegar e o que manter com você",
          readingMd: [
            "# Delegation: o que delegar e o que manter com você",
            "",
            "**Delegation** é a arte de decidir **o que** vale a pena entregar à IA, **o que** é melhor você fazer e **como** dividir um trabalho maior em partes. Antes de escrever qualquer prompt, a pergunta certa é: *isto deveria ser feito por mim, pela IA, ou por nós dois juntos?*",
            "",
            "## Três tipos de consciência (awareness)",
            "",
            "Uma boa delegação se apoia em três percepções:",
            "",
            "- **Consciência do problema (problem awareness)** — entender de verdade o que você está tentando alcançar. Qual é o objetivo, quais são os critérios de sucesso, o que é inegociável? Você não consegue delegar bem o que você mesmo não compreendeu.",
            "- **Consciência da plataforma (platform awareness)** — conhecer os **pontos fortes e fracos** da ferramenta de IA. Para que ela é boa? Onde ela costuma falhar (cálculos exatos, fatos recentes, números sensíveis)? Que ferramentas ela tem acesso?",
            "- **Consciência de delegação de tarefas (task delegation)** — combinar as duas anteriores para distribuir o trabalho: quais subtarefas vão para a IA, quais ficam com você, e como elas se conectam.",
            "",
            "## Quem faz o quê: pense em forças complementares",
            "",
            "A IA tende a brilhar em: gerar rascunhos rápidos, explorar muitas alternativas, resumir e reestruturar, lidar com volume. Você tende a brilhar em: julgamento, contexto tácito, valores, responsabilidade, decisões de alto risco e o gosto final.",
            "",
            "> Regra prática: **delegue a geração, mantenha o julgamento.** Use a IA para multiplicar opções e velocidade; reserve para você as decisões que carregam risco, ética ou autoria.",
            "",
            "## Delegação não é abdicação",
            "",
            "Delegar uma tarefa **não** transfere a responsabilidade pelo resultado. Se você publica um texto escrito pela IA, a responsabilidade pelo que ele afirma é **sua**. Boa delegação inclui decidir **quanto controle** manter sobre cada etapa.",
            "",
            "## Exemplo do dia a dia",
            "",
            "Você precisa preparar uma apresentação. **Delegação madura:** você define a mensagem central e o público (problem awareness), pede à IA três estruturas possíveis e rascunhos de slides (aproveitando a força dela em gerar opções), mas escreve você mesmo o slide de recomendação final — porque é ali que está o seu julgamento profissional e a sua responsabilidade.",
            "",
            "> Leitura oficial: https://www.anthropic.com/ai-fluency",
          ].join("\n"),
          flashcards: [
            {
              front: "Quais são os três tipos de consciência que sustentam a Delegation?",
              back: "Consciência do problema (o que você quer alcançar), da plataforma (forças/fraquezas da IA) e de delegação de tarefas (como dividir o trabalho).",
              tags: ["ai-fluency", "delegation"],
            },
            {
              front: "Regra prática de delegação em uma frase.",
              back: "Delegue a geração, mantenha o julgamento: use a IA para velocidade e opções; reserve para você as decisões com risco, ética ou autoria.",
              tags: ["ai-fluency", "delegation"],
            },
            {
              front: "Delegar uma tarefa à IA transfere a responsabilidade pelo resultado?",
              back: "Não. Delegação não é abdicação: a responsabilidade pelo que você publica ou decide continua sendo sua.",
              tags: ["ai-fluency", "delegation"],
            },
            {
              front: "Por que a 'consciência do problema' vem antes de delegar?",
              back: "Porque você não consegue delegar bem aquilo que não compreendeu — sem objetivo e critérios de sucesso claros, o pedido fica vago.",
              tags: ["ai-fluency", "delegation"],
            },
          ],
          questions: [
            {
              prompt:
                "Conhecer os pontos fortes e fracos da ferramenta de IA (ex.: que ela falha em cálculos exatos) é qual consciência da Delegation?",
              options: [
                "Consciência do problema",
                "Consciência da plataforma",
                "Consciência de delegação de tarefas",
                "Consciência de discernimento",
              ],
              correctIndex: 1,
              explanation:
                "Conhecer capacidades e limitações da ferramenta é a consciência da plataforma (platform awareness).",
              difficulty: 1,
              tags: ["ai-fluency", "delegation"],
            },
            {
              prompt: "Qual afirmação reflete o princípio 'delegação não é abdicação'?",
              options: [
                "Se a IA escreveu, a culpa por um erro é da IA",
                "Ao publicar um texto gerado por IA, a responsabilidade pelo conteúdo continua sendo sua",
                "Delegar significa nunca mais revisar o trabalho",
                "A IA assume a autoria legal do que produz",
              ],
              correctIndex: 1,
              explanation:
                "Delegar a execução não transfere a responsabilidade pelo resultado; quem usa e publica responde pelo conteúdo.",
              difficulty: 2,
              tags: ["ai-fluency", "delegation"],
            },
            {
              prompt:
                "Seguindo 'delegue a geração, mantenha o julgamento', qual tarefa é a MENOS apropriada para delegar inteiramente à IA?",
              options: [
                "Gerar três variações de título para um artigo",
                "Resumir um relatório longo",
                "Decidir, sozinha, se um paciente deve receber alta médica",
                "Reescrever um parágrafo em tom mais formal",
              ],
              correctIndex: 2,
              explanation:
                "Decisões de alto risco com implicações éticas e de responsabilidade devem manter o julgamento humano; a IA pode apoiar, mas não decidir sozinha.",
              difficulty: 2,
              tags: ["ai-fluency", "delegation"],
            },
          ],
          labs: [
            {
              title: "Plano de delegação para um projeto real",
              promptMd: [
                "# Lab: plano de delegação para um projeto real",
                "",
                "Escolha um projeto ou tarefa **maior** que você precise entregar em breve.",
                "",
                "Produza um plano de delegação contendo:",
                "1. **Problem awareness** — objetivo, público e 2-3 critérios de sucesso.",
                "2. **Platform awareness** — 2 forças e 2 limitações da IA relevantes para este projeto.",
                "3. **Task delegation** — uma tabela dividindo as subtarefas em: *IA faz*, *eu faço*, *fazemos juntos (eu reviso)*.",
                "4. Justifique **por que** ao menos uma subtarefa ficou com você (risco, ética, autoria ou julgamento).",
              ].join("\n"),
              rubric: [
                "Define objetivo, público e critérios de sucesso concretos (problem awareness).",
                "Lista forças e limitações reais da IA pertinentes ao projeto (platform awareness).",
                "Apresenta uma divisão clara das subtarefas entre IA, humano e colaboração revisada.",
                "Justifica ao menos uma subtarefa mantida com o humano por risco, ética, autoria ou julgamento.",
              ],
              modelAnswer: [
                "## Projeto: relatório trimestral de resultados para a diretoria",
                "",
                "**1. Problem awareness.** Objetivo: comunicar à diretoria o desempenho do trimestre e recomendar 2 ações. Público: diretores ocupados, pouco tempo. Critérios de sucesso: (a) cabe em 2 páginas, (b) cada número tem fonte verificável, (c) a recomendação final é clara e defensável.",
                "",
                "**2. Platform awareness.** Forças: a IA é ótima para estruturar o relatório e reescrever parágrafos de forma concisa. Limitações: pode errar contas e não conhece nossos números internos — todo dado precisa vir de mim e ser conferido.",
                "",
                "**3. Task delegation.**",
                "",
                "| Subtarefa | Responsável |",
                "| --- | --- |",
                "| Propor a estrutura do relatório | IA |",
                "| Reescrever rascunhos para ficarem concisos | IA |",
                "| Inserir e conferir todos os números | Eu |",
                "| Escrever a recomendação final | Eu |",
                "| Revisar tom e clareza do texto final | Juntos (eu reviso) |",
                "",
                "**4. Justificativa.** A recomendação final ficou comigo porque carrega julgamento profissional e responsabilidade perante a diretoria — é uma decisão de risco que não delego, embora eu use a IA para refinar a redação depois de decidida.",
              ].join("\n"),
            },
          ],
        },
        {
          title: "Description: descrever bem a tarefa, o contexto e o formato",
          readingMd: [
            "# Description: descrever bem a tarefa, o contexto e o formato",
            "",
            "**Description** é a competência de **comunicar à IA o que você quer** de forma que ela possa de fato entregar. Um modelo não lê sua mente: a qualidade da saída costuma refletir a qualidade da descrição. Descrever bem é o ponto onde mais gente ganha resultado rapidamente.",
            "",
            "## Três dimensões da descrição",
            "",
            "- **Descrição do produto (product)** — *o que* você quer como resultado: o entregável, o formato, o tamanho, o tom, as restrições. \"Um e-mail de no máximo 120 palavras, tom cordial, terminando com uma pergunta.\"",
            "- **Descrição do processo (process)** — *como* você quer que a IA chegue lá: pensar passo a passo, considerar prós e contras antes de concluir, fazer perguntas antes de começar, ou seguir um método específico.",
            "- **Descrição do desempenho (performance)** — *quem* a IA deve ser e *como* deve se comportar: o papel/persona, o nível de detalhe, o público-alvo, o que evitar. \"Você é um revisor técnico cético; aponte fraquezas, não elogie.\"",
            "",
            "## Os ingredientes de uma boa descrição",
            "",
            "1. **Tarefa clara** — diga o verbo e o objeto: \"classifique\", \"resuma\", \"reescreva\", \"compare\".",
            "2. **Contexto suficiente** — quem é o público, qual o objetivo, o que já foi tentado, restrições.",
            "3. **Formato de saída** — lista, tabela, JSON, número de itens, seções.",
            "4. **Exemplos** quando possível — mostrar um bom exemplo (\"few-shot\") vale mais que muitos adjetivos.",
            "5. **Limites** — o que NÃO fazer, o que evitar, quando dizer \"não sei\".",
            "",
            "## Analogia: instruir um colega novo",
            "",
            "Imagine pedir algo a um colega competente no **primeiro dia**, que não conhece o cliente nem o histórico. Você não diria apenas \"faça a proposta\". Você daria contexto, mostraria um exemplo do padrão da casa e diria o formato esperado. Descrever para a IA é o mesmo exercício — feito de forma explícita.",
            "",
            "## Exemplo: de vago a descritivo",
            "",
            "```",
            "Vago:    \"Escreva sobre nosso produto.\"",
            "Melhor:  \"Você é um redator de marketing B2B (desempenho).",
            "          Escreva 3 versões de um parágrafo de abertura (produto)",
            "          para um e-commerce de café para escritórios, público de",
            "          gestores de RH, tom prático e caloroso, máx. 60 palavras",
            "          cada (produto). Antes de escrever, liste em 1 linha o",
            "          benefício central de cada versão (processo).\"",
            "```",
            "",
            "> Leitura oficial: https://www.anthropic.com/ai-fluency",
          ].join("\n"),
          flashcards: [
            {
              front: "Quais são as três dimensões da Description?",
              back: "Produto (o que você quer: entregável, formato, tom), Processo (como a IA deve chegar lá) e Desempenho (quem a IA deve ser e como se comportar).",
              tags: ["ai-fluency", "description"],
            },
            {
              front: "Por que dar contexto é parte essencial da descrição?",
              back: "Porque o modelo não lê sua mente; sem público, objetivo e restrições, ele preenche as lacunas com suposições genéricas.",
              tags: ["ai-fluency", "description"],
            },
            {
              front: "O que significa 'descrição de desempenho' (performance)?",
              back: "Definir o papel/persona da IA e como ela deve se comportar — nível de detalhe, público-alvo, tom e o que evitar.",
              tags: ["ai-fluency", "description"],
            },
            {
              front: "Por que incluir um exemplo (few-shot) costuma ajudar mais que adjetivos?",
              back: "Um bom exemplo mostra concretamente o padrão esperado, reduzindo ambiguidade muito mais do que descrições vagas como 'profissional' ou 'bonito'.",
              tags: ["ai-fluency", "description", "prompting"],
            },
          ],
          questions: [
            {
              prompt:
                "Pedir 'pense passo a passo e liste os prós e contras antes de concluir' é um exemplo de qual dimensão da Description?",
              options: [
                "Descrição do produto",
                "Descrição do processo",
                "Descrição do desempenho",
                "Descrição do discernimento",
              ],
              correctIndex: 1,
              explanation:
                "Instruir COMO a IA deve chegar ao resultado (o método/raciocínio) é a descrição de processo.",
              difficulty: 2,
              tags: ["ai-fluency", "description"],
            },
            {
              prompt:
                "'Você é um revisor técnico cético; aponte fraquezas e não elogie.' Essa instrução é principalmente:",
              options: [
                "Descrição de produto",
                "Descrição de processo",
                "Descrição de desempenho",
                "Uma alucinação",
              ],
              correctIndex: 2,
              explanation:
                "Definir o papel e o comportamento da IA (persona, postura) é a descrição de desempenho.",
              difficulty: 2,
              tags: ["ai-fluency", "description"],
            },
            {
              prompt:
                "Qual destes é o passo mais eficaz para transformar 'Escreva sobre nosso produto' em uma boa descrição?",
              options: [
                "Repetir o pedido mais vezes",
                "Adicionar público, objetivo, formato, tom e um exemplo do padrão desejado",
                "Aumentar o tamanho máximo da resposta",
                "Pedir para a IA ser 'mais criativa'",
              ],
              correctIndex: 1,
              explanation:
                "Boas descrições adicionam contexto (público, objetivo), formato e exemplos — não adjetivos vagos nem repetição.",
              difficulty: 1,
              tags: ["ai-fluency", "description", "prompting"],
            },
          ],
          labs: [
            {
              title: "Reescreva um prompt vago usando as três dimensões",
              promptMd: [
                "# Lab: reescreva um prompt vago",
                "",
                "Parta deste prompt propositalmente vago:",
                "",
                "> \"Me ajude com um post sobre produtividade.\"",
                "",
                "Reescreva-o cobrindo explicitamente as **três dimensões** da Description e identifique cada parte:",
                "1. **Desempenho** — papel/persona e comportamento da IA.",
                "2. **Produto** — entregável, formato, tamanho, tom, restrições.",
                "3. **Processo** — como a IA deve raciocinar/proceder antes de entregar.",
                "",
                "Inclua pelo menos **um limite** (algo a evitar) e, se fizer sentido, **um exemplo**.",
              ].join("\n"),
              rubric: [
                "Cobre explicitamente as três dimensões (desempenho, produto, processo) e rotula cada uma.",
                "Especifica formato e restrições concretas (tamanho, tom, estrutura) no produto.",
                "Inclui ao menos um limite explícito sobre o que evitar.",
                "O prompt final é claramente mais acionável que o original vago.",
              ],
              modelAnswer: [
                "## Prompt reescrito",
                "",
                "**[Desempenho]** Você é um estrategista de conteúdo para LinkedIn que escreve para profissionais de tecnologia ocupados; seja direto e evite jargão motivacional vazio.",
                "",
                "**[Produto]** Escreva 1 post de até 150 palavras sobre produtividade com foco em *uma* técnica concreta (ex.: timeboxing). Estrutura: um gancho de 1 linha, 3 passos práticos em lista, e uma pergunta final para engajamento. Tom prático e respeitoso.",
                "",
                "**[Processo]** Antes de escrever, declare em 1 linha qual técnica você escolheu e por que ela cabe nesse público. Só então redija o post.",
                "",
                "**[Limite]** Não prometa resultados milagrosos, não use clichês como 'hustle' e não invente estatísticas — se citar um dado, deixe claro que é ilustrativo.",
                "",
                "**[Exemplo de gancho desejado]** \"Você não precisa de mais horas no dia — precisa de menos abas abertas.\"",
              ].join("\n"),
            },
          ],
        },
        {
          title: "Discernment e Diligence: avaliar criticamente e agir com responsabilidade",
          readingMd: [
            "# Discernment e Diligence: avaliar criticamente e agir com responsabilidade",
            "",
            "Os dois últimos Ds são o que tornam a colaboração **confiável**. Sem eles, você acelera — mas pode acelerar na direção errada.",
            "",
            "## Discernment: julgar o que a IA entregou",
            "",
            "**Discernment** é avaliar criticamente a colaboração em três frentes:",
            "",
            "- **Discernimento do produto (product)** — o resultado está **correto, completo e adequado**? Os fatos batem? O tom serve ao público? Falta algo? Há erro ou alucinação?",
            "- **Discernimento do processo (process)** — o **caminho** que a IA seguiu faz sentido? O raciocínio é sólido ou há saltos lógicos? Ela usou as fontes/ferramentas certas?",
            "- **Discernimento do desempenho (performance)** — a IA **se comportou** como pedido? Manteve o papel, o tom e os limites? Está sendo bajuladora ou complacente demais (concordando com tudo)?",
            "",
            "O discernimento alimenta o **laço Descrição–Discernimento**: cada avaliação vira um insumo para melhorar a próxima descrição. É um ciclo, não um veredito único.",
            "",
            "## Diligence: usar a IA de forma responsável",
            "",
            "**Diligence** é a postura ética e cuidadosa que atravessa toda a colaboração. Três frentes:",
            "",
            "- **Diligência de criação (creation)** — verificar fatos, conferir números, checar fontes, garantir originalidade e respeitar direitos antes de adotar o que a IA produziu.",
            "- **Diligência de transparência (transparency)** — ser honesto sobre **quando e como** a IA foi usada, conforme o contexto exige (trabalho, escola, publicação).",
            "- **Diligência de implantação/uso (deployment)** — pensar nas consequências de colocar aquilo no mundo: privacidade (não vazar dados sensíveis), impacto sobre pessoas, segurança e o controle humano sobre decisões importantes.",
            "",
            "> Princípio-chave: **a verificação é sua, não da IA.** O modelo pode soar seguro e ainda assim estar errado; quem assina o resultado é você.",
            "",
            "## Exemplo integrado",
            "",
            "A IA gera um parágrafo com uma estatística atraente. **Discernimento de produto:** essa estatística é verdadeira? **Diligência de criação:** você confere a fonte — e descobre que ela não existe (alucinação). **Diligência de transparência:** ao publicar, você sinaliza que a IA ajudou na redação. **Diligência de uso:** você remove qualquer dado pessoal que tenha colado no prompt. O resultado final é rápido *e* confiável.",
            "",
            "> Leitura oficial: https://www.anthropic.com/ai-fluency",
          ].join("\n"),
          flashcards: [
            {
              front: "Quais são as três frentes do Discernment?",
              back: "Produto (o resultado está correto/completo?), Processo (o caminho/raciocínio faz sentido?) e Desempenho (a IA se comportou como pedido, sem bajulação?).",
              tags: ["ai-fluency", "discernment"],
            },
            {
              front: "Quais são as três frentes da Diligence?",
              back: "Criação (verificar fatos/fontes/direitos), Transparência (revelar uso da IA) e Implantação/uso (privacidade, consequências e controle humano).",
              tags: ["ai-fluency", "diligence"],
            },
            {
              front: "Princípio-chave da diligência sobre verificação.",
              back: "A verificação é sua, não da IA. O modelo pode soar seguro e estar errado; quem assina o resultado responde por ele.",
              tags: ["ai-fluency", "diligence"],
            },
            {
              front: "Como o Discernment alimenta o laço Descrição–Discernimento?",
              back: "Cada avaliação crítica do resultado vira insumo para refinar a próxima descrição, em ciclo, até chegar a uma saída adequada.",
              tags: ["ai-fluency", "discernment", "description"],
            },
          ],
          questions: [
            {
              prompt:
                "Perceber que a IA está concordando com tudo o que você diz, sem contestar erros, é uma falha detectada por qual frente do Discernment?",
              options: [
                "Discernimento de produto",
                "Discernimento de processo",
                "Discernimento de desempenho",
                "Diligência de transparência",
              ],
              correctIndex: 2,
              explanation:
                "Avaliar se a IA mantém o comportamento pedido — inclusive não ser bajuladora/complacente — é o discernimento de desempenho.",
              difficulty: 2,
              tags: ["ai-fluency", "discernment"],
            },
            {
              prompt:
                "Conferir se uma estatística citada pela IA realmente existe antes de publicá-la é um ato de:",
              options: [
                "Diligência de criação",
                "Descrição de processo",
                "Delegação de tarefas",
                "Diligência de transparência",
              ],
              correctIndex: 0,
              explanation:
                "Verificar fatos, fontes e números antes de adotar o conteúdo é a diligência de criação.",
              difficulty: 1,
              tags: ["ai-fluency", "diligence"],
            },
            {
              prompt:
                "Revelar honestamente, em um trabalho acadêmico, que você usou IA para revisar a redação corresponde a qual frente da Diligence?",
              options: [
                "Diligência de criação",
                "Diligência de transparência",
                "Diligência de implantação/uso",
                "Discernimento de produto",
              ],
              correctIndex: 1,
              explanation:
                "Ser honesto sobre quando e como a IA foi usada, conforme o contexto exige, é a diligência de transparência.",
              difficulty: 1,
              tags: ["ai-fluency", "diligence"],
            },
            {
              prompt:
                "Você colou dados pessoais de clientes em um prompt e agora vai publicar a saída. Qual frente da Diligence trata desse risco?",
              options: [
                "Diligência de transparência",
                "Diligência de criação",
                "Diligência de implantação/uso (privacidade e consequências)",
                "Discernimento de processo",
              ],
              correctIndex: 2,
              explanation:
                "Proteger privacidade e pensar nas consequências de colocar algo no mundo é a diligência de implantação/uso.",
              difficulty: 2,
              tags: ["ai-fluency", "diligence"],
            },
          ],
          labs: [
            {
              title: "Checklist de discernimento e diligência",
              promptMd: [
                "# Lab: aplique discernimento e diligência a uma saída de IA",
                "",
                "Pegue (ou imagine) uma resposta de IA que contenha **uma afirmação factual** e **uma recomendação**.",
                "",
                "Escreva um checklist preenchido cobrindo:",
                "1. **Discernimento de produto** — a afirmação é verdadeira/completa? Como você checaria?",
                "2. **Discernimento de processo** — o raciocínio tem saltos? Faltou considerar algo?",
                "3. **Discernimento de desempenho** — a IA manteve o papel pedido, sem bajulação?",
                "4. **Diligência de criação** — que verificação concreta você faria antes de usar?",
                "5. **Diligência de transparência** — neste contexto, você revelaria o uso de IA? Como?",
                "6. **Diligência de uso** — há dado sensível ou consequência a mitigar?",
              ].join("\n"),
              rubric: [
                "Cobre as três frentes do discernimento (produto, processo, desempenho).",
                "Cobre as três frentes da diligência (criação, transparência, uso).",
                "Indica pelo menos uma verificação concreta e acionável (não apenas 'verificar').",
                "Identifica ao menos um risco real de transparência, privacidade ou consequência.",
              ],
              modelAnswer: [
                "## Saída avaliada: 'A técnica X aumenta a retenção em 30%; recomendo adotá-la em toda a equipe.'",
                "",
                "**1. Discernimento de produto.** O número de 30% é suspeito por ser redondo e sem fonte. Checaria buscando o estudo original; se não houver, trato como não confiável.",
                "",
                "**2. Discernimento de processo.** A IA pulou da estatística direto para 'adotar em toda a equipe' sem considerar o nosso contexto (tamanho do time, custo de adoção). Falta nuance.",
                "",
                "**3. Discernimento de desempenho.** Pedi um conselheiro cético, mas a resposta soou vendedora e otimista demais — sinal de complacência; vou pedir explicitamente os contra-argumentos.",
                "",
                "**4. Diligência de criação.** Verificação concreta: procurar a fonte da estatística e, na ausência, remover o número ou marcá-lo como ilustrativo.",
                "",
                "**5. Diligência de transparência.** Se eu levar isso a uma decisão de equipe, direi que a IA ajudou a estruturar a análise, e que os dados foram conferidos por mim.",
                "",
                "**6. Diligência de uso.** Não há dado pessoal aqui, mas a recomendação afeta toda a equipe — então a decisão final fica comigo, com base em evidências verificadas, não na confiança do texto.",
              ].join("\n"),
            },
          ],
        },
      ],
    },

    // =====================================================================
    // MÓDULO 3 — COLABORANDO COM CLAUDE NA PRÁTICA
    // =====================================================================
    {
      title: "Colaborando com Claude na prática",
      lessons: [
        {
          title: "Prompting eficaz: contexto, formato e exemplos",
          readingMd: [
            "# Prompting eficaz: contexto, formato e exemplos",
            "",
            "Prompting eficaz é a aplicação prática da **Description**. Não existe \"prompt mágico\": existem hábitos que tornam suas instruções claras, contextualizadas e verificáveis. Esta lição reúne os mais úteis.",
            "",
            "## 1. Seja específico sobre a tarefa",
            "",
            "Troque verbos vagos por verbos precisos. \"Melhore isto\" é ambíguo; \"reescreva isto em tom mais formal, mantendo o mesmo tamanho\" é acionável. Diga o **verbo** (resumir, classificar, comparar) e o **objeto**.",
            "",
            "## 2. Dê contexto suficiente",
            "",
            "O modelo só sabe o que está no prompt. Inclua: público-alvo, objetivo, o que já foi tentado, restrições e qualquer material de referência. Colar o texto-fonte é quase sempre melhor que descrevê-lo por cima.",
            "",
            "## 3. Especifique o formato de saída",
            "",
            "Peça a forma exata: uma tabela, uma lista de 5 itens, JSON com campos definidos, um parágrafo de até N palavras. Formato explícito reduz idas e vindas.",
            "",
            "## 4. Mostre exemplos (few-shot)",
            "",
            "Se você tem um padrão (\"queremos títulos assim: ...\"), mostre 1-2 exemplos. Exemplos comunicam estilo e estrutura melhor do que adjetivos.",
            "",
            "## 5. Peça raciocínio quando a tarefa for complexa",
            "",
            "Para problemas com várias etapas, peça que a IA **pense passo a passo** ou explique seu raciocínio antes da resposta final. Isso costuma melhorar a qualidade e torna o resultado **auditável** (você vê onde ela errou).",
            "",
            "## 6. Defina o papel e os limites",
            "",
            "Diga quem a IA deve ser (\"você é um revisor jurídico cuidadoso\") e o que evitar (\"se não tiver certeza, diga que não sabe em vez de inventar\"). Pedir que ela admita incerteza reduz alucinações.",
            "",
            "## Um molde reutilizável",
            "",
            "```",
            "[Papel]      Você é ...",
            "[Tarefa]     Faça ... (verbo + objeto)",
            "[Contexto]   Público: ... Objetivo: ... Restrições: ...",
            "[Formato]    Entregue como ...",
            "[Exemplo]    Um bom resultado se parece com ...",
            "[Limites]    Não faça ...; se não souber, diga ...",
            "```",
            "",
            "> Leitura oficial: https://www.anthropic.com/ai-fluency",
          ].join("\n"),
          flashcards: [
            {
              front: "Por que colar o texto-fonte no prompt costuma ser melhor que descrevê-lo?",
              back: "Porque o modelo só sabe o que está no prompt; fornecer o material real elimina suposições e dá base concreta para a resposta.",
              tags: ["ai-fluency", "prompting"],
            },
            {
              front: "Que efeito tem pedir à IA para 'pensar passo a passo' em tarefas complexas?",
              back: "Tende a melhorar a qualidade e torna o resultado auditável — você consegue ver onde o raciocínio falhou.",
              tags: ["ai-fluency", "prompting"],
            },
            {
              front: "Como reduzir alucinações via prompt?",
              back: "Pedir explicitamente que a IA admita incerteza ('se não tiver certeza, diga que não sabe em vez de inventar') e fornecer fontes no contexto.",
              tags: ["ai-fluency", "prompting"],
            },
            {
              front: "Por que exemplos (few-shot) comunicam melhor que adjetivos?",
              back: "Porque mostram concretamente o estilo e a estrutura desejados, em vez de depender de palavras vagas como 'profissional' ou 'criativo'.",
              tags: ["ai-fluency", "prompting"],
            },
          ],
          questions: [
            {
              prompt: "Qual destes é o prompt mais acionável?",
              options: [
                "Melhore este texto",
                "Deixe isto melhor e mais bonito",
                "Reescreva este parágrafo em tom formal, mantendo o tamanho e sem mudar os fatos",
                "Faça mágica com este texto",
              ],
              correctIndex: 2,
              explanation:
                "O terceiro especifica verbo, transformação desejada e restrições — é acionável. Os demais são vagos.",
              difficulty: 1,
              tags: ["ai-fluency", "prompting"],
            },
            {
              prompt:
                "Você quer respostas em um formato consistente para processar depois. O que mais ajuda?",
              options: [
                "Pedir 'seja organizado'",
                "Especificar o formato exato (ex.: JSON com campos nome, valor, data)",
                "Aumentar a temperatura",
                "Repetir a pergunta três vezes",
              ],
              correctIndex: 1,
              explanation:
                "Especificar o formato de saída exato reduz ambiguidade e retrabalho, tornando a saída previsível.",
              difficulty: 1,
              tags: ["ai-fluency", "prompting"],
            },
            {
              prompt:
                "Adicionar 'se você não tiver certeza, diga que não sabe em vez de inventar' serve principalmente para:",
              options: [
                "Deixar a resposta mais longa",
                "Reduzir o risco de alucinação ao dar à IA permissão para admitir incerteza",
                "Aumentar a criatividade",
                "Trocar o idioma da resposta",
              ],
              correctIndex: 1,
              explanation:
                "Permitir que o modelo admita incerteza reduz a pressão por inventar respostas plausíveis porém falsas.",
              difficulty: 2,
              tags: ["ai-fluency", "prompting"],
            },
          ],
          labs: [
            {
              title: "Monte um prompt usando o molde reutilizável",
              promptMd: [
                "# Lab: monte um prompt com o molde [Papel/Tarefa/Contexto/Formato/Exemplo/Limites]",
                "",
                "Escolha uma tarefa real sua e escreva um prompt completo usando os seis campos do molde:",
                "",
                "- **Papel** — quem a IA deve ser.",
                "- **Tarefa** — verbo + objeto.",
                "- **Contexto** — público, objetivo, restrições.",
                "- **Formato** — a forma exata da saída.",
                "- **Exemplo** — como se parece um bom resultado.",
                "- **Limites** — o que evitar; o que fazer em caso de incerteza.",
              ].join("\n"),
              rubric: [
                "Preenche os seis campos do molde (papel, tarefa, contexto, formato, exemplo, limites).",
                "A tarefa usa verbo preciso e objeto claro.",
                "O formato de saída é concreto e verificável.",
                "Os limites incluem uma instrução para lidar com incerteza (ex.: admitir não saber).",
              ],
              modelAnswer: [
                "**[Papel]** Você é um analista de suporte sênior, claro e empático.",
                "",
                "**[Tarefa]** Redija uma resposta a um cliente que reclamou de uma cobrança duplicada.",
                "",
                "**[Contexto]** Público: cliente irritado, primeiro contato. Objetivo: acalmar, explicar o próximo passo e dar prazo. Restrição: não admitir culpa antes da apuração.",
                "",
                "**[Formato]** Um e-mail de até 120 palavras: saudação, reconhecimento do problema, próximo passo com prazo, encerramento cordial.",
                "",
                "**[Exemplo]** Tom desejado: 'Entendo o transtorno e já estou verificando o ocorrido — retorno até amanhã às 18h com uma posição.'",
                "",
                "**[Limites]** Não prometa reembolso antes da apuração; se faltar informação para concluir, deixe um campo [VERIFICAR] em vez de inventar dados.",
              ].join("\n"),
            },
          ],
        },
        {
          title: "Iteração e o laço Descrição–Discernimento",
          readingMd: [
            "# Iteração e o laço Descrição–Discernimento",
            "",
            "Raramente o primeiro prompt produz o resultado ideal — e tudo bem. A colaboração fluente é **iterativa**: você descreve, avalia, refina. Esse ciclo é o **laço Descrição–Discernimento**, o motor prático dos 4 Ds.",
            "",
            "## O ciclo, passo a passo",
            "",
            "1. **Descreva** — escreva o melhor prompt que conseguir (Description).",
            "2. **Avalie** — examine a saída com olhar crítico (Discernment): o que está bom, o que falhou e *por quê*.",
            "3. **Refine** — ajuste a descrição com base no que você aprendeu, não recomece do zero às cegas.",
            "4. **Repita** — até a saída atender aos seus critérios.",
            "",
            "## Refinar é diagnosticar, não 'tentar de novo'",
            "",
            "A diferença entre iterar bem e mal está no diagnóstico. Em vez de reescrever o prompt inteiro na esperança, pergunte: *qual parte da minha descrição causou esse problema?*",
            "",
            "- Saída longa demais? → faltou restrição de tamanho (produto).",
            "- Tom errado? → faltou definir persona/público (desempenho).",
            "- Pulou etapas? → peça raciocínio passo a passo (processo).",
            "- Inventou um fato? → reforce limites e peça fontes (diligência).",
            "",
            "## Dê feedback específico",
            "",
            "Ao iterar dentro de uma conversa, não diga só \"está ruim\". Diga **o que** mudar: \"encurte para 80 palavras\", \"remova o segundo parágrafo\", \"use um tom mais técnico\", \"a estatística do 3º item parece inventada, remova-a\". Feedback específico funciona como uma nova descrição focada.",
            "",
            "## Saiba quando parar (e quando assumir)",
            "",
            "Iterar tem retorno decrescente. Se após algumas rodadas a IA não chega lá, talvez a tarefa peça **mais contexto seu**, ou seja melhor você **assumir aquela parte** (volta à Delegation). Reconhecer isso é fluência, não fracasso.",
            "",
            "## Analogia: dirigir, não programar",
            "",
            "Colaborar com a IA se parece mais com **dirigir** (corrigir o rumo continuamente, observando a estrada) do que com **programar uma rota fixa**. O laço Descrição–Discernimento é o seu volante.",
            "",
            "> Leitura oficial: https://www.anthropic.com/ai-fluency",
          ].join("\n"),
          flashcards: [
            {
              front: "Quais são os passos do laço Descrição–Discernimento?",
              back: "Descrever (prompt), avaliar a saída criticamente, refinar a descrição com base no que aprendeu e repetir até atender aos critérios.",
              tags: ["ai-fluency", "description", "discernment"],
            },
            {
              front: "Qual a diferença entre iterar bem e iterar mal?",
              back: "Iterar bem é diagnosticar qual parte da descrição causou o problema e ajustar só isso; iterar mal é reescrever tudo às cegas na esperança.",
              tags: ["ai-fluency", "iteracao"],
            },
            {
              front: "Quando a melhor decisão ao iterar é parar e voltar à Delegation?",
              back: "Quando há retorno decrescente: depois de algumas rodadas sem chegar lá, talvez falte contexto seu ou seja melhor você assumir aquela parte da tarefa.",
              tags: ["ai-fluency", "delegation", "iteracao"],
            },
            {
              front: "Por que colaborar com IA é mais como 'dirigir' do que 'programar uma rota'?",
              back: "Porque você corrige o rumo continuamente observando os resultados, em vez de definir uma sequência fixa de antemão.",
              tags: ["ai-fluency", "iteracao"],
            },
          ],
          questions: [
            {
              prompt:
                "A saída veio com o tom errado para o público. Qual dimensão da descrição você deve reforçar ao iterar?",
              options: [
                "Produto (formato/tamanho)",
                "Desempenho (persona/público)",
                "Diligência de transparência",
                "Nada — basta repetir o prompt",
              ],
              correctIndex: 1,
              explanation:
                "Tom inadequado costuma indicar falta de definição de persona/público — a dimensão de desempenho da descrição.",
              difficulty: 2,
              tags: ["ai-fluency", "description", "iteracao"],
            },
            {
              prompt: "Qual é a forma mais eficaz de dar feedback ao iterar dentro de uma conversa?",
              options: [
                "Dizer apenas 'está ruim, refaça'",
                "Apontar especificamente o que mudar (tamanho, trecho, tom, dado a remover)",
                "Apagar a conversa e começar do zero sempre",
                "Aumentar a temperatura e tentar de novo",
              ],
              correctIndex: 1,
              explanation:
                "Feedback específico age como uma nova descrição focada e guia a IA muito melhor que críticas vagas.",
              difficulty: 1,
              tags: ["ai-fluency", "iteracao"],
            },
            {
              prompt:
                "Após várias iterações a IA ainda não entrega o resultado. Qual reação reflete fluência?",
              options: [
                "Insistir indefinidamente com o mesmo prompt",
                "Concluir que IA é inútil e abandonar a ferramenta",
                "Reconhecer o retorno decrescente: dar mais contexto ou assumir você mesmo aquela parte",
                "Aceitar a saída ruim como está",
              ],
              correctIndex: 2,
              explanation:
                "Reconhecer retorno decrescente e voltar à Delegation (mais contexto ou assumir a tarefa) é uma decisão fluente, não um fracasso.",
              difficulty: 2,
              tags: ["ai-fluency", "iteracao", "delegation"],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // MÓDULO 4 — USO RESPONSÁVEL E ÉTICO
    // =====================================================================
    {
      title: "Uso responsável e ético",
      lessons: [
        {
          title: "Alucinação, verificação e pensamento crítico",
          readingMd: [
            "# Alucinação, verificação e pensamento crítico",
            "",
            "A capacidade que mais protege você no uso de IA é o **discernimento crítico** aplicado às saídas. Modelos são fluentes e convincentes — e essa fluência pode mascarar erros.",
            "",
            "## Por que a alucinação acontece",
            "",
            "Um LLM otimiza para produzir texto **plausível**, não necessariamente **verdadeiro**. Quando não 'sabe' algo, ele tende a preencher a lacuna com algo que *soa* certo. Por isso uma alucinação costuma vir com a mesma confiança de uma afirmação correta — o tom não é um sinal de veracidade.",
            "",
            "## Onde o risco é maior",
            "",
            "- **Fatos específicos** — datas, números, nomes, citações, referências bibliográficas.",
            "- **Eventos recentes** — além da data de corte do modelo.",
            "- **Detalhes técnicos ou jurídicos** precisos.",
            "- **Cálculos** exatos feitos 'de cabeça' pelo modelo.",
            "",
            "## Estratégias de verificação",
            "",
            "1. **Confira fatos críticos em fontes independentes** — especialmente números, citações e nomes.",
            "2. **Peça as fontes** e então **verifique se elas existem** (a própria referência pode ser inventada).",
            "3. **Forneça você mesmo o material** (grounding): colar o documento e pedir respostas baseadas *só* nele reduz alucinação.",
            "4. **Use ferramentas certas para cada coisa** — para contas exatas, prefira uma calculadora/código a confiar na aritmética mental do modelo.",
            "5. **Calibre o esforço ao risco** — quanto maior a consequência de um erro, mais rigorosa a verificação.",
            "",
            "## Pensamento crítico: trate a IA como uma fonte, não um oráculo",
            "",
            "A postura saudável é tratar a saída da IA como o **rascunho de um colega esperto, porém falível**: útil, frequentemente certo, mas que você **revisa** antes de assinar embaixo. A confiança deve ser **proporcional** à verificação que você fez — não ao tom seguro do texto.",
            "",
            "> Leitura oficial: https://www.anthropic.com/ai-fluency",
          ].join("\n"),
          flashcards: [
            {
              front: "Por que o tom confiante de uma resposta de IA não indica que ela é verdadeira?",
              back: "Porque o modelo otimiza plausibilidade do texto, não verdade; uma alucinação tende a soar tão segura quanto um fato correto.",
              tags: ["ai-fluency", "etica", "genai"],
            },
            {
              front: "O que é 'grounding' como estratégia de verificação?",
              back: "Fornecer você mesmo o material (ex.: colar o documento) e pedir respostas baseadas só nele, reduzindo a chance de o modelo inventar.",
              tags: ["ai-fluency", "etica", "prompting"],
            },
            {
              front: "Onde o risco de alucinação é maior?",
              back: "Em fatos específicos (datas, números, nomes, citações), eventos recentes, detalhes técnicos/jurídicos e cálculos exatos.",
              tags: ["ai-fluency", "etica", "genai"],
            },
            {
              front: "Como calibrar o esforço de verificação?",
              back: "De forma proporcional ao risco: quanto maior a consequência de um erro, mais rigorosa deve ser a checagem.",
              tags: ["ai-fluency", "etica", "diligence"],
            },
          ],
          questions: [
            {
              prompt: "Uma resposta soa muito confiante. O que isso diz sobre sua veracidade?",
              options: [
                "Que ela certamente está correta",
                "Nada de confiável — confiança no tom não é evidência de verdade",
                "Que a temperatura estava alta",
                "Que a fonte foi verificada automaticamente",
              ],
              correctIndex: 1,
              explanation:
                "O tom confiante não é sinal de veracidade; alucinações costumam soar tão seguras quanto fatos corretos.",
              difficulty: 1,
              tags: ["ai-fluency", "etica", "genai"],
            },
            {
              prompt:
                "A IA cita um artigo científico para embasar uma afirmação. Qual é o passo de diligência apropriado?",
              options: [
                "Confiar, pois citar fonte garante veracidade",
                "Verificar se o artigo realmente existe e diz aquilo, pois a referência pode ser inventada",
                "Pedir para a IA jurar que é verdade",
                "Ignorar a fonte completamente",
              ],
              correctIndex: 1,
              explanation:
                "Referências podem ser alucinadas; é preciso confirmar que a fonte existe e sustenta a afirmação.",
              difficulty: 2,
              tags: ["ai-fluency", "etica", "diligence"],
            },
            {
              prompt:
                "Para uma conta aritmética exata dentro de um relatório, a abordagem mais segura é:",
              options: [
                "Confiar na aritmética mental do modelo",
                "Usar uma calculadora ou código e conferir o resultado",
                "Pedir o número em letras maiúsculas",
                "Aumentar max_tokens",
              ],
              correctIndex: 1,
              explanation:
                "Cálculos exatos devem usar a ferramenta certa (calculadora/código); o modelo pode errar contas feitas 'de cabeça'.",
              difficulty: 1,
              tags: ["ai-fluency", "etica", "genai"],
            },
          ],
          labs: [
            {
              title: "Plano de verificação proporcional ao risco",
              promptMd: [
                "# Lab: plano de verificação proporcional ao risco",
                "",
                "Imagine que você vai usar uma saída de IA em um contexto de **alto risco** (ex.: material para um cliente, decisão financeira, conteúdo público).",
                "",
                "Liste:",
                "1. **3 afirmações** da saída que exigiriam verificação (priorize fatos, números, citações).",
                "2. Para cada uma, **como** você verificaria (fonte independente, ferramenta, especialista).",
                "3. **1 estratégia preventiva** de prompt que reduziria alucinação desde o início (ex.: grounding, pedir fontes, admitir incerteza).",
                "4. Uma frase explicando por que o **nível de risco** justifica esse esforço.",
              ].join("\n"),
              rubric: [
                "Identifica afirmações verificáveis concretas, priorizando fatos/números/citações.",
                "Associa a cada afirmação um método de verificação plausível e específico.",
                "Inclui ao menos uma estratégia preventiva de prompt (grounding, fontes ou incerteza).",
                "Conecta explicitamente o esforço de verificação ao nível de risco do contexto.",
              ],
              modelAnswer: [
                "## Contexto: relatório de viabilidade que irá para um investidor",
                "",
                "**Afirmações a verificar:**",
                "1. 'O mercado cresce 12% ao ano.' → conferir em relatório setorial independente; sem fonte sólida, marco como estimativa.",
                "2. 'O concorrente X faturou R$ 50 mi em 2024.' → checar em demonstrativos públicos ou fontes de imprensa confiáveis.",
                "3. 'A regulação Y permite esse modelo de negócio.' → confirmar com a fonte legal oficial ou um advogado.",
                "",
                "**Métodos:** (1) fonte setorial; (2) registros públicos; (3) texto legal/especialista — nada baseado só na palavra do modelo.",
                "",
                "**Estratégia preventiva de prompt:** fornecer os documentos que tenho e instruir 'responda apenas com base no material anexado; se algo não estiver nele, diga que precisa ser verificado' (grounding + admitir incerteza).",
                "",
                "**Justificativa do esforço:** como o relatório embasa uma decisão de investimento, o custo de um número errado é altíssimo — por isso cada dado crítico passa por fonte independente antes de entrar no documento.",
              ].join("\n"),
            },
          ],
        },
        {
          title: "Viés, privacidade e transparência",
          readingMd: [
            "# Viés, privacidade e transparência",
            "",
            "Além da precisão, o uso responsável de IA envolve cuidar de **vieses**, **privacidade** e **transparência** — três frentes da diligência que protegem pessoas, não só a qualidade do trabalho.",
            "",
            "## Viés",
            "",
            "LLMs aprendem com grandes volumes de texto humano e, com eles, **herdam padrões e vieses** presentes nesses dados — sobre gênero, raça, cultura, profissões e muito mais. Na prática isso pode aparecer como suposições estereotipadas, perspectivas pouco representativas ou um ponto de vista que parece neutro mas não é.",
            "",
            "Como lidar:",
            "- **Suspeite de generalizações** e de saídas que tratam um grupo como homogêneo.",
            "- **Peça perspectivas múltiplas** explicitamente quando o tema for sensível.",
            "- **Traga o contexto que falta** — o modelo não conhece a sua realidade local a menos que você a descreva.",
            "- Lembre que **você é o filtro final**: o julgamento sobre justiça e adequação é humano.",
            "",
            "## Privacidade",
            "",
            "Trate o prompt como algo que **sai do seu controle imediato**. Antes de colar informação, pergunte: *isto é sensível? eu tenho permissão para compartilhar?*",
            "",
            "- **Não cole dados pessoais de terceiros** (CPF, saúde, dados de clientes) sem necessidade e base legal.",
            "- **Anonimize** quando possível: substitua nomes e identificadores por marcadores.",
            "- **Conheça a política** da ferramenta sobre uso de dados e retenção no seu contexto (trabalho, empresa).",
            "- Minimize: forneça **só o necessário** para a tarefa.",
            "",
            "## Transparência",
            "",
            "Ser honesto sobre o uso de IA constrói confiança e, em muitos contextos, é uma exigência ética (e às vezes formal).",
            "- **Revele quando o contexto pede** — trabalho acadêmico, publicação, decisões que afetam terceiros.",
            "- **Seja específico**: dizer 'a IA ajudou a revisar a redação' é diferente de 'a IA escreveu tudo'.",
            "- **Assuma a autoria e a responsabilidade** pelo resultado final — a transparência não dilui o fato de que quem assina responde.",
            "",
            "## Princípio integrador: humano no comando",
            "",
            "Em todas essas frentes, o fio condutor é o **controle humano significativo**: a IA amplia o que você faz, mas as decisões com peso ético, legal ou humano permanecem **suas**.",
            "",
            "> Leitura oficial: https://www.anthropic.com/ai-fluency",
          ].join("\n"),
          flashcards: [
            {
              front: "Por que LLMs podem reproduzir vieses?",
              back: "Porque aprendem com grandes volumes de texto humano e herdam padrões e vieses presentes nesses dados (gênero, raça, cultura etc.).",
              tags: ["ai-fluency", "etica", "vies"],
            },
            {
              front: "Duas práticas de privacidade ao usar IA.",
              back: "Não colar dados pessoais de terceiros sem necessidade/base legal e anonimizar/minimizar — fornecer só o necessário e conhecer a política de dados da ferramenta.",
              tags: ["ai-fluency", "etica", "privacidade"],
            },
            {
              front: "O que torna a transparência sobre o uso de IA mais útil?",
              back: "Ser específico sobre o quê a IA fez ('ajudou a revisar' vs. 'escreveu tudo') e assumir a autoria e responsabilidade pelo resultado.",
              tags: ["ai-fluency", "etica", "transparencia"],
            },
            {
              front: "O que é 'controle humano significativo'?",
              back: "O princípio de que a IA amplia o trabalho, mas decisões com peso ético, legal ou humano permanecem com a pessoa, que responde por elas.",
              tags: ["ai-fluency", "etica", "diligence"],
            },
          ],
          questions: [
            {
              prompt:
                "Ao tratar de um tema sensível, qual prática ajuda a mitigar viés na saída da IA?",
              options: [
                "Aceitar a primeira resposta como neutra",
                "Pedir explicitamente perspectivas múltiplas e fornecer o contexto que falta",
                "Aumentar o tamanho da resposta",
                "Evitar dar qualquer contexto",
              ],
              correctIndex: 1,
              explanation:
                "Solicitar perspectivas múltiplas e fornecer contexto reduz suposições estereotipadas; nenhuma saída é automaticamente neutra.",
              difficulty: 2,
              tags: ["ai-fluency", "etica", "vies"],
            },
            {
              prompt: "Qual é a postura correta sobre dados pessoais de terceiros em prompts?",
              options: [
                "Colar tudo, pois a IA é privada por padrão",
                "Evitar colar dados sensíveis sem necessidade e base legal; anonimizar e minimizar",
                "Só evitar se a ferramenta for gratuita",
                "Privacidade não se aplica a prompts",
              ],
              correctIndex: 1,
              explanation:
                "Deve-se evitar dados pessoais sensíveis sem necessidade/base legal, anonimizando e fornecendo só o necessário.",
              difficulty: 1,
              tags: ["ai-fluency", "etica", "privacidade"],
            },
            {
              prompt:
                "Em um artigo que você vai publicar, você usou IA para reescrever trechos. Qual atitude reflete transparência madura?",
              options: [
                "Esconder o uso, pois ninguém perguntou",
                "Afirmar que a IA escreveu 100% para se eximir de erros",
                "Revelar de forma específica como a IA foi usada e assumir a responsabilidade pelo conteúdo",
                "Creditar toda a autoria à IA",
              ],
              correctIndex: 2,
              explanation:
                "Transparência madura é revelar especificamente o uso e ainda assim assumir a autoria e a responsabilidade pelo resultado final.",
              difficulty: 2,
              tags: ["ai-fluency", "etica", "transparencia"],
            },
            {
              prompt: "O princípio de 'controle humano significativo' implica que:",
              options: [
                "A IA deve tomar todas as decisões para ser eficiente",
                "Decisões com peso ético, legal ou humano permanecem com a pessoa responsável",
                "Humanos não devem usar IA em decisões",
                "O controle é apenas técnico, não ético",
              ],
              correctIndex: 1,
              explanation:
                "A IA amplia capacidades, mas decisões de peso ético/legal/humano e a responsabilidade por elas permanecem humanas.",
              difficulty: 1,
              tags: ["ai-fluency", "etica", "diligence"],
            },
          ],
          labs: [
            {
              title: "Política pessoal de uso responsável de IA",
              promptMd: [
                "# Lab: escreva sua política pessoal de uso responsável de IA",
                "",
                "Redija uma mini-política (1 página) que você seguiria ao usar IA no trabalho ou nos estudos, com seções:",
                "1. **Viés** — 2 regras para detectar e mitigar viés.",
                "2. **Privacidade** — 2 regras sobre o que nunca colar e como anonimizar.",
                "3. **Transparência** — quando e como você revela o uso de IA.",
                "4. **Verificação** — seu critério mínimo antes de publicar/entregar.",
                "5. **Controle humano** — quais decisões você nunca delega inteiramente.",
              ].join("\n"),
              rubric: [
                "Cobre as cinco seções (viés, privacidade, transparência, verificação, controle humano).",
                "As regras são concretas e acionáveis, não slogans genéricos.",
                "A seção de privacidade especifica o que nunca colar e/ou como anonimizar.",
                "Define ao menos uma classe de decisão que nunca é delegada inteiramente à IA.",
              ],
              modelAnswer: [
                "## Minha política de uso responsável de IA",
                "",
                "**1. Viés.** (a) Em temas sensíveis, peço sempre ao menos duas perspectivas e questiono generalizações. (b) Reviso saídas sobre pessoas/grupos buscando estereótipos antes de usar.",
                "",
                "**2. Privacidade.** (a) Nunca colo CPF, dados de saúde ou dados de clientes sem base legal e necessidade. (b) Quando preciso do conteúdo, substituo nomes por [CLIENTE], [PESSOA] e removo identificadores.",
                "",
                "**3. Transparência.** Em entregas a clientes e trabalhos avaliados, declaro de forma específica como usei IA (ex.: 'usei IA para estruturar e revisar a redação; os dados e conclusões são meus').",
                "",
                "**4. Verificação.** Antes de entregar, todo número, citação e nome próprio passa por uma fonte independente; o que não puder verificar, removo ou marco como estimativa.",
                "",
                "**5. Controle humano.** Nunca delego inteiramente: decisões financeiras, jurídicas, de pessoas (contratar, avaliar) e qualquer recomendação que eu assine profissionalmente. A IA apoia; a decisão e a responsabilidade são minhas.",
              ].join("\n"),
            },
          ],
        },
      ],
    },
  ],
};
