import type { ModuleSeed } from "./pack.js";

// Módulos adicionais que aprofundam a Claude Certified Architect – Foundations.
// São concatenados ao pack principal (cca-foundations.ts) pelo registro de packs.
//
// Cobrem quatro áreas que toda pessoa arquiteta precisa dominar além da API
// básica: engenharia de prompts, entradas multimodais (imagens/PDFs) e saídas
// estruturadas, a família de modelos + janela de contexto + extended thinking, e
// avaliação/qualidade (evals + citations). Conteúdo em pt-BR, com callout
// "> Leitura oficial:" em cada lição apontando para a documentação oficial.
//
// Convenção de tags (kebab-case): "prompt-engineering" | "vision" | "pdf" |
// "structured-outputs" | "models" | "extended-thinking" | "evals" | "citations".
export const foundationsExtraModules: ModuleSeed[] = [
  // =====================================================================
  // MÓDULO — PROMPT ENGINEERING
  // =====================================================================
  {
    title: "Prompt Engineering",
    lessons: [
      {
        title: "Clareza, especificidade e exemplos (few-shot)",
        readingMd: [
          "# Clareza, especificidade e exemplos (few-shot)",
          "",
          "Antes de qualquer técnica avançada, a engenharia de prompts começa por **dizer claramente o que você quer**. Claude é poderoso, mas não lê mentes: ele segue o que está escrito. A maior parte dos prompts ruins falha porque é vaga, ambígua ou assume contexto que o modelo não tem.",
          "",
          "> Importante: a própria documentação recomenda **definir critérios de sucesso e construir avaliações ANTES de iterar no prompt**. Você precisa saber o que é \"bom\" para conseguir melhorar de forma empírica, não no chute.",
          "",
          "## 1. Seja claro e direto",
          "",
          "Trate Claude como um colaborador novo, brilhante mas sem contexto. Dê:",
          "",
          "- **O objetivo** da tarefa e o que será feito com a saída (\"isto vai para um e-mail ao cliente\").",
          "- **O público** e o **tom** esperados.",
          "- **Instruções sequenciais** quando a tarefa tem passos — use uma lista numerada ou bullets.",
          "- **Restrições explícitas** (\"responda em no máximo 3 frases\", \"não invente dados\", \"use apenas o texto fornecido\").",
          "",
          "Uma boa heurística: se você mostrasse o prompt a um colega humano sem mais contexto, ele saberia exatamente o que fazer? Se não, o prompt está incompleto.",
          "",
          "## 2. Seja específico sobre o formato",
          "",
          "Não diga apenas \"resuma\". Diga **como** resumir: quantos itens, em que estrutura, com ou sem título. Quanto mais específico o formato desejado, mais previsível a saída — o que é essencial para integrar a resposta em um sistema.",
          "",
          "## 3. Dê exemplos (multishot / few-shot)",
          "",
          "Exemplos são a forma mais eficaz de comunicar o que você quer. Em vez de descrever o estilo, **mostre** 2 a 5 pares entrada→saída no formato exato esperado. Isso é chamado de *few-shot* (ou *multishot*) prompting.",
          "",
          "Boas práticas para exemplos:",
          "",
          "- Use **exemplos relevantes e diversos**, cobrindo casos comuns e casos de borda (entradas estranhas, ambíguas).",
          "- Mantenha o **formato consistente** entre todos os exemplos — Claude imita o padrão que você demonstra.",
          "- Envolva cada exemplo em **tags** para separá-los claramente do resto do prompt (veja a lição sobre XML tags).",
          "",
          "```text",
          "Classifique o sentimento como positivo, negativo ou neutro.",
          "",
          "<exemplos>",
          "Texto: \"Adorei o atendimento, voltarei sempre!\" => positivo",
          "Texto: \"Demorou 2h e ninguém me avisou.\" => negativo",
          "Texto: \"O pedido chegou na data prevista.\" => neutro",
          "</exemplos>",
          "",
          "Texto: \"A embalagem veio amassada mas o produto funciona.\" =>",
          "```",
          "",
          "Few-shot reduz drasticamente a variabilidade e ensina convenções difíceis de descrever em palavras (rótulos exatos, pontuação, idioma da saída).",
          "",
          "## Ordem das técnicas",
          "",
          "A documentação sugere aplicar as técnicas mais ou menos nesta ordem de impacto: **(1) ser claro e direto → (2) usar exemplos → (3) deixar Claude pensar (chain-of-thought) → (4) usar XML tags → (5) dar um papel via system prompt → (6) prefill da resposta → (7) encadear prompts**. Comece pelo topo; só avance quando o ganho parar.",
          "",
          "> Leitura oficial: https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview",
        ].join("\n"),
        flashcards: [
          {
            front: "Qual é o pré-requisito que a documentação recomenda ANTES de iterar em prompts?",
            back: "Definir critérios de sucesso claros e construir avaliações (evals) para medir empiricamente. Sem isso você não sabe se uma mudança no prompt melhorou ou piorou.",
            tags: ["prompt-engineering", "evals"],
          },
          {
            front: "O que significa few-shot (multishot) prompting?",
            back: "Incluir alguns exemplos de pares entrada→saída no formato exato desejado para que Claude imite o padrão. É a forma mais eficaz de comunicar estilo, rótulos e convenções.",
            tags: ["prompt-engineering"],
          },
          {
            front: "Boa heurística para saber se um prompt está claro o suficiente?",
            back: "Imagine mostrar o prompt a um colega humano sem contexto adicional: ele saberia exatamente o que fazer? Se não, faltam objetivo, público, formato ou restrições.",
            tags: ["prompt-engineering"],
          },
          {
            front: "Por que dar exemplos costuma superar descrever o estilo em palavras?",
            back: "Exemplos demonstram concretamente o formato, os rótulos e as convenções; Claude imita o padrão. Descrições verbais deixam ambiguidade que os exemplos eliminam.",
            tags: ["prompt-engineering"],
          },
        ],
        questions: [
          {
            prompt: "Segundo a documentação, o que você deve ter ANTES de começar a engenharia de prompts?",
            options: [
              "Um modelo fine-tuned específico para a tarefa",
              "Critérios de sucesso claros e formas de avaliar empiricamente o prompt",
              "Acesso ao parâmetro top_k",
              "Um dataset de pelo menos 1 milhão de exemplos",
            ],
            correctIndex: 1,
            explanation:
              "A página de overview afirma que o guia assume critérios de sucesso definidos e meios de testar empiricamente contra eles. Sem isso, você não consegue iterar de forma objetiva.",
            difficulty: 2,
            tags: ["prompt-engineering", "evals"],
          },
          {
            prompt: "Qual prática melhor descreve few-shot prompting?",
            options: [
              "Aumentar o parâmetro temperature para gerar mais variações",
              "Fornecer alguns exemplos de entrada→saída no formato exato desejado",
              "Repetir a instrução várias vezes para reforço",
              "Usar um system prompt muito longo com regras",
            ],
            correctIndex: 1,
            explanation:
              "Few-shot (multishot) significa incluir exemplos concretos no formato esperado para que Claude reproduza o padrão. É distinto de temperature, repetição ou regras no system prompt.",
            difficulty: 1,
            tags: ["prompt-engineering"],
          },
          {
            prompt: "Por que vale a pena incluir casos de borda entre os exemplos few-shot?",
            options: [
              "Para aumentar o número de tokens de entrada e ativar prompt caching",
              "Porque exemplos diversos, incluindo entradas ambíguas, ensinam o modelo a lidar com situações reais difíceis",
              "Porque só casos de borda contam como exemplos válidos",
              "Para forçar stop_reason = max_tokens",
            ],
            correctIndex: 1,
            explanation:
              "Exemplos relevantes e diversos — inclusive de borda — orientam o comportamento em entradas reais difíceis, reduzindo erros nos casos que mais importam.",
            difficulty: 2,
            tags: ["prompt-engineering"],
          },
        ],
        labs: [
          {
            title: "Transformar um prompt vago em um prompt claro com few-shot",
            promptMd: [
              "Você recebeu este prompt fraco usado em produção:",
              "",
              "> \"Resuma o ticket de suporte.\"",
              "",
              "Os resumos saem inconsistentes: às vezes longos, às vezes sem mencionar a ação tomada, em formatos diferentes.",
              "",
              "**Tarefa:** reescreva o prompt aplicando clareza, especificidade de formato e few-shot. Inclua: objetivo/uso da saída, formato exato (ex.: 3 campos), e 2 exemplos no formato desejado, separados por tags.",
            ].join("\n"),
            rubric: [
              "Deixa claro o objetivo e o uso da saída (ex.: alimentar um painel ou e-mail).",
              "Especifica um formato exato e verificável (campos/estrutura fixos).",
              "Inclui pelo menos 2 exemplos no formato desejado.",
              "Usa tags (ex.: <exemplos>) para separar os exemplos das instruções.",
              "Adiciona ao menos uma restrição explícita (tamanho, não inventar, idioma).",
            ],
            modelAnswer: [
              "```text",
              "Você resume tickets de suporte para um painel interno da equipe de operações.",
              "Resuma o ticket em EXATAMENTE três linhas, neste formato:",
              "Problema: <uma frase>",
              "Causa: <uma frase, ou \"não informada\">",
              "Ação tomada: <uma frase, ou \"pendente\">",
              "",
              "Regras: use apenas informações presentes no ticket; não invente causas;",
              "máximo de 20 palavras por linha; responda em português.",
              "",
              "<exemplos>",
              "Ticket: \"Cliente não consegue logar desde a atualização. Resetamos a senha e funcionou.\"",
              "Problema: Cliente sem acesso ao login após a atualização.",
              "Causa: Credencial inválida após a atualização.",
              "Ação tomada: Senha resetada, acesso restaurado.",
              "",
              "Ticket: \"Boleto não chegou. Cliente cobra resposta. Ainda investigando o envio.\"",
              "Problema: Boleto não recebido pelo cliente.",
              "Causa: não informada.",
              "Ação tomada: pendente.",
              "</exemplos>",
              "",
              "Ticket: \"{{TICKET}}\"",
              "```",
              "",
              "Por que funciona: o objetivo e o público estão explícitos; o formato de 3 campos é",
              "verificável por código; as restrições evitam alucinação e controlam o tamanho; e os",
              "dois exemplos demonstram exatamente o padrão, inclusive como tratar dados ausentes.",
            ].join("\n"),
          },
        ],
      },
      {
        title: "Chain-of-thought e XML tags",
        readingMd: [
          "# Chain-of-thought e XML tags",
          "",
          "Duas técnicas que costumam dar o maior salto de qualidade depois de clareza e exemplos: **deixar Claude pensar passo a passo** e **estruturar o prompt com XML tags**.",
          "",
          "## Chain-of-thought (raciocínio passo a passo)",
          "",
          "Para tarefas complexas — matemática, lógica de múltiplos passos, análise, decisões — pedir que Claude **pense antes de responder** melhora bastante a qualidade. Quando o modelo escreve o raciocínio, ele \"trabalha\" o problema em vez de pular para uma resposta possivelmente errada.",
          "",
          "Formas de induzir chain-of-thought (CoT):",
          "",
          "- **Básico:** \"Pense passo a passo antes de responder.\"",
          "- **Guiado:** liste os passos que você quer (\"primeiro identifique X, depois calcule Y, depois conclua\").",
          "- **Estruturado:** peça o raciocínio dentro de uma tag e a resposta final em outra, para conseguir separar as duas no seu código:",
          "",
          "```text",
          "Pense no problema dentro de <pensamento>...</pensamento>.",
          "Depois dê a resposta final dentro de <resposta>...</resposta>.",
          "```",
          "",
          "Assim você pode mostrar ao usuário só o conteúdo de `<resposta>` e, se quiser, descartar o raciocínio. **Atenção:** CoT via prompt consome tokens de saída (o raciocínio é gerado). Para raciocínio nativo e gerenciado pela API, veja a lição de *raciocínio (thinking)*.",
          "",
          "## XML tags para estruturar o prompt",
          "",
          "Claude foi treinado prestando atenção a **tags no estilo XML**. Use-as para delimitar partes do prompt sem ambiguidade: o documento de entrada, os exemplos, as instruções, o formato de saída.",
          "",
          "Benefícios:",
          "",
          "- **Clareza:** separa claramente \"o que é dado\" de \"o que é instrução\".",
          "- **Precisão:** reduz o risco de o modelo confundir suas instruções com o conteúdo a ser processado.",
          "- **Parsing:** se você pedir a saída dentro de uma tag (ex.: `<json>`), fica trivial extrair só aquele trecho da resposta.",
          "",
          "```text",
          "<instrucoes>",
          "Extraia o nome e o e-mail do cliente do texto abaixo.",
          "</instrucoes>",
          "",
          "<documento>",
          "Olá, sou a Ana (ana@exemplo.com) e gostaria de...",
          "</documento>",
          "",
          "Responda apenas com o JSON dentro de <saida></saida>.",
          "```",
          "",
          "Dicas: use **nomes de tag descritivos** e **consistentes** (a mesma tag referida no texto e no conteúdo), e **aninhe** tags quando fizer sentido (`<exemplos><exemplo>...</exemplo></exemplos>`). Não existe um conjunto \"mágico\" de tags — o que importa é a estrutura consistente.",
          "",
          "## Combinando CoT + XML",
          "",
          "As duas técnicas se reforçam: estruture a entrada com tags e peça o raciocínio em `<pensamento>` e a resposta em `<resposta>`. Você ganha qualidade (CoT) e facilidade de extração (XML) ao mesmo tempo.",
          "",
          "> Leitura oficial: https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview",
        ].join("\n"),
        flashcards: [
          {
            front: "O que é chain-of-thought (CoT) prompting e quando usar?",
            back: "Pedir que Claude raciocine passo a passo antes da resposta final. Útil em tarefas complexas (matemática, lógica de múltiplos passos, análise). Custa tokens de saída, pois o raciocínio é gerado.",
            tags: ["prompt-engineering"],
          },
          {
            front: "Por que envolver o raciocínio em uma tag como <pensamento>?",
            back: "Para separar o raciocínio da resposta final (<resposta>), permitindo mostrar ao usuário só a resposta e/ou descartar o raciocínio no seu código.",
            tags: ["prompt-engineering"],
          },
          {
            front: "Para que servem XML tags em um prompt do Claude?",
            back: "Delimitar partes do prompt (instruções, documento, exemplos, saída) sem ambiguidade. Claude presta atenção a tags; elas melhoram clareza, precisão e facilitam extrair a saída.",
            tags: ["prompt-engineering"],
          },
          {
            front: "Existe um conjunto obrigatório de nomes de tags XML no prompt?",
            back: "Não. Não há tags \"mágicas\". O que importa é usar nomes descritivos, consistentes (o mesmo nome no texto e no conteúdo) e bem estruturados/aninhados.",
            tags: ["prompt-engineering"],
          },
        ],
        questions: [
          {
            prompt: "Qual é uma vantagem prática de pedir a resposta final dentro de uma tag (ex.: <resposta>)?",
            options: [
              "Reduz o custo de tokens de entrada pela metade",
              "Permite extrair facilmente só a resposta e separá-la do raciocínio",
              "Desativa a amostragem (temperature passa a ser ignorada)",
              "Garante que stop_reason seja sempre end_turn",
            ],
            correctIndex: 1,
            explanation:
              "Colocar a resposta em uma tag dedicada facilita o parsing: seu código extrai apenas aquele bloco e pode descartar o raciocínio de <pensamento>.",
            difficulty: 2,
            tags: ["prompt-engineering"],
          },
          {
            prompt: "Sobre chain-of-thought via prompt, qual afirmação é correta?",
            options: [
              "Não tem custo, pois o raciocínio não conta como saída",
              "Tende a melhorar tarefas complexas, mas o raciocínio gerado consome tokens de saída",
              "Só funciona se temperature for 1",
              "Substitui completamente a necessidade de exemplos",
            ],
            correctIndex: 1,
            explanation:
              "CoT melhora tarefas de múltiplos passos, porém o raciocínio é texto gerado e conta como tokens de saída (custo/latência). É diferente do raciocínio nativo (thinking) da API.",
            difficulty: 2,
            tags: ["prompt-engineering"],
          },
          {
            prompt: "Por que Claude lida bem com XML tags no prompt?",
            options: [
              "Porque XML é o único formato aceito pela Messages API",
              "Porque o modelo foi treinado prestando atenção a tags, então elas delimitam partes do prompt com pouca ambiguidade",
              "Porque tags reduzem automaticamente alucinações a zero",
              "Porque tags convertem o texto em JSON internamente",
            ],
            correctIndex: 1,
            explanation:
              "Claude responde bem a estruturação com tags estilo XML; elas separam instruções, dados e saída, reduzindo confusão. Não são obrigatórias na API nem eliminam alucinação sozinhas.",
            difficulty: 1,
            tags: ["prompt-engineering"],
          },
        ],
        labs: [
          {
            title: "Estruturar uma tarefa de análise com XML + CoT",
            promptMd: [
              "Você precisa que Claude analise uma reclamação de cliente e decida a **prioridade** (alta/média/baixa), justificando.",
              "",
              "**Tarefa:** escreva um prompt que (1) use XML tags para separar instruções e o texto da reclamação, (2) peça o raciocínio em uma tag e a decisão final em outra tag de fácil extração, e (3) restrinja as opções de prioridade.",
            ].join("\n"),
            rubric: [
              "Usa tags distintas para instruções e para o conteúdo da reclamação.",
              "Pede raciocínio passo a passo em uma tag dedicada (ex.: <pensamento>).",
              "Pede a decisão final em uma tag separada e fácil de extrair (ex.: <prioridade>).",
              "Restringe a saída a um conjunto fechado de valores (alta/média/baixa).",
              "Deixa claro que a decisão deve se basear no texto fornecido.",
            ],
            modelAnswer: [
              "```text",
              "<instrucoes>",
              "Você triagem reclamações de clientes. Classifique a PRIORIDADE como exatamente",
              "um destes valores: alta, media, baixa. Baseie-se SOMENTE no texto da reclamação.",
              "Primeiro raciocine; depois dê a decisão final.",
              "</instrucoes>",
              "",
              "<reclamacao>",
              "{{TEXTO_DA_RECLAMACAO}}",
              "</reclamacao>",
              "",
              "Pense dentro de <pensamento>...</pensamento> considerando impacto, urgência e risco.",
              "Depois responda apenas com o valor dentro de <prioridade>...</prioridade>.",
              "```",
              "",
              "Por que funciona: as tags <instrucoes> e <reclamacao> impedem que o modelo confunda o",
              "texto do cliente com instruções; <pensamento> ativa chain-of-thought; e <prioridade>,",
              "com valores fechados, torna a saída trivial de extrair e validar por código.",
            ].join("\n"),
          },
        ],
      },
      {
        title: "System prompts, papéis e prefill da resposta",
        readingMd: [
          "# System prompts, papéis e prefill da resposta",
          "",
          "Duas alavancas poderosas para controlar comportamento e formato: dar um **papel** a Claude via system prompt, e **preencher o início (prefill)** da resposta do assistant.",
          "",
          "## System prompt e role prompting",
          "",
          "O **system prompt** é passado no campo de topo `system` da Messages API (separado do array `messages`). Ele define papel, tom, regras e contexto persistente — não é um turno de usuário.",
          "",
          "Dar um **papel** (\"você é um advogado tributarista sênior\", \"você é um revisor de código rigoroso\") muda a forma como Claude responde: vocabulário, profundidade, prioridades e nível de cautela. Role prompting é uma das maneiras mais simples e eficazes de elevar a qualidade em domínios específicos.",
          "",
          "Boas práticas para o system prompt:",
          "",
          "- Coloque ali **quem Claude é** e **as regras gerais** que valem para toda a conversa.",
          "- Deixe a **tarefa específica e os dados** no turno `user` — o system define comportamento, o user traz o pedido concreto.",
          "- Inclua restrições de segurança e de formato que devem valer sempre.",
          "",
          "```json",
          "{",
          "  \"model\": \"<modelo>\",",
          "  \"max_tokens\": 1024,",
          "  \"system\": \"Você é um tutor de certificações Anthropic. Responda em português, de forma didática, e nunca invente nomes de parâmetros da API.\",",
          "  \"messages\": [",
          "    { \"role\": \"user\", \"content\": \"Explique o que é o campo system.\" }",
          "  ]",
          "}",
          "```",
          "",
          "## Prefill da resposta do assistant",
          "",
          "Você pode **começar a resposta por Claude** incluindo um último turno com `role: \"assistant\"` cujo `content` é o início desejado. Claude continua **a partir** daquele texto. Isso é o *prefill*.",
          "",
          "Para que serve:",
          "",
          "- **Forçar formato:** prefill com `{` faz Claude continuar gerando JSON, pulando preâmbulos como \"Claro! Aqui está...\".",
          "- **Controlar estilo/voz:** começar com um cabeçalho ou um \"- \" induz listas/markdown.",
          "- **Manter consistência** em respostas estruturadas.",
          "",
          "```json",
          "{",
          "  \"messages\": [",
          "    { \"role\": \"user\", \"content\": \"Devolva os dados do cliente como JSON.\" },",
          "    { \"role\": \"assistant\", \"content\": \"{\" }",
          "  ]",
          "}",
          "```",
          "",
          "Detalhes importantes do prefill:",
          "",
          "- O texto do prefill **faz parte** da resposta final: a saída de Claude vem **logo após** o que você escreveu (na prática, você concatena o prefill com `content` da resposta).",
          "- Há uma restrição da API: o `content` do prefill **não pode terminar com espaços em branco** no fim.",
          "- Prefill é uma alternativa leve e eficaz quando você quer pular preâmbulos e garantir um formato — sem precisar de tooling adicional.",
          "",
          "> Observação: para obtenção de JSON realmente confiável e validado por schema, prefira *tool use* ou *structured outputs* (veja o módulo de saídas estruturadas). O prefill ajuda, mas não garante JSON válido por construção.",
          "",
          "> Leitura oficial: https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview",
        ].join("\n"),
        flashcards: [
          {
            front: "Onde se define o papel/persona de Claude e por quê?",
            back: "No system prompt (campo de topo `system`). Ele define papel, tom, regras e contexto persistente para toda a conversa; a tarefa concreta e os dados ficam no turno user.",
            tags: ["prompt-engineering", "api"],
          },
          {
            front: "O que é prefill da resposta do assistant?",
            back: "Incluir um último turno com role \"assistant\" cujo content é o início desejado da resposta. Claude continua a partir dali — útil para forçar formato (ex.: começar com { para JSON) e pular preâmbulos.",
            tags: ["prompt-engineering", "api"],
          },
          {
            front: "Restrição da API sobre o content de um prefill assistant?",
            back: "O content do prefill não pode terminar com espaços em branco no final.",
            tags: ["prompt-engineering", "api"],
          },
          {
            front: "Prefill garante JSON válido por construção?",
            back: "Não. Prefill ajuda a induzir o formato (ex.: iniciar com {), mas não valida schema. Para JSON confiável use tool use ou structured outputs.",
            tags: ["prompt-engineering", "structured-outputs"],
          },
        ],
        questions: [
          {
            prompt: "Qual é a maneira de fazer prefill (começar a resposta de Claude) na Messages API?",
            options: [
              "Definir o campo system com o texto inicial da resposta",
              "Adicionar um turno final com role \"assistant\" cujo content é o início desejado",
              "Usar o parâmetro stop_sequences com o texto inicial",
              "Definir temperature como 0",
            ],
            correctIndex: 1,
            explanation:
              "Prefill é feito incluindo um último turno assistant com o começo da resposta; Claude continua a partir dele. O system define comportamento, não inicia a resposta.",
            difficulty: 2,
            tags: ["prompt-engineering", "api"],
          },
          {
            prompt: "Para fazer Claude responder direto em JSON, pulando frases como \"Claro, aqui está\", uma técnica simples é:",
            options: [
              "Aumentar max_tokens",
              "Prefill com \"{\" no turno assistant",
              "Definir top_k = 1",
              "Enviar a instrução duas vezes",
            ],
            correctIndex: 1,
            explanation:
              "Prefill com { induz Claude a continuar gerando o objeto JSON, sem preâmbulos. Para garantia de schema, porém, use tool use / structured outputs.",
            difficulty: 1,
            tags: ["prompt-engineering", "structured-outputs"],
          },
          {
            prompt: "Qual conteúdo é mais apropriado para o system prompt (em vez do turno user)?",
            options: [
              "O documento específico a ser resumido nesta requisição",
              "A pergunta exata do usuário desta vez",
              "O papel de Claude e as regras gerais válidas para toda a conversa",
              "O JSON de resposta esperado",
            ],
            correctIndex: 2,
            explanation:
              "O system prompt carrega papel, tom e regras persistentes. Dados e o pedido específico desta vez pertencem ao turno user.",
            difficulty: 2,
            tags: ["prompt-engineering", "api"],
          },
        ],
        labs: [
          {
            title: "Combinar role prompting e prefill",
            promptMd: [
              "Você está construindo um endpoint que retorna a classificação de risco de uma transação como JSON.",
              "",
              "**Tarefa:** descreva (a) um system prompt que dê a Claude um papel adequado e regras de segurança/formato, e (b) como usar prefill para garantir que a resposta comece como JSON. Explique por que essa combinação é eficaz.",
            ].join("\n"),
            rubric: [
              "Define um system prompt com papel claro e regras (segurança/formato).",
              "Mostra o uso de um turno assistant de prefill começando com {.",
              "Explica que o prefill pula preâmbulos e induz JSON.",
              "Menciona que prefill não valida schema e cita tool use/structured outputs como reforço.",
              "Coloca a tarefa concreta/dados no turno user, não no system.",
            ],
            modelAnswer: [
              "```json",
              "{",
              "  \"system\": \"Você é um analista de risco antifraude. Avalie transações de forma conservadora. Nunca invente campos. Responda SOMENTE com JSON válido, sem texto antes ou depois.\",",
              "  \"messages\": [",
              "    { \"role\": \"user\", \"content\": \"Transação: R$ 9.800 às 3h, país diferente do cadastro. Classifique o risco.\" },",
              "    { \"role\": \"assistant\", \"content\": \"{\" }",
              "  ]",
              "}",
              "```",
              "",
              "Por que funciona: o system define o papel (analista antifraude) e as regras de saída,",
              "elevando a qualidade e a cautela; o prefill com { faz Claude continuar diretamente o JSON,",
              "eliminando preâmbulos. Como o prefill não garante schema, em produção eu combinaria isso",
              "com tool use (uma ferramenta com input_schema do objeto de risco) ou structured outputs",
              "para obter JSON validado por construção. A tarefa específica fica no turno user.",
            ].join("\n"),
          },
        ],
      },
    ],
  },

  // =====================================================================
  // MÓDULO — VISÃO, PDFs E SAÍDAS ESTRUTURADAS
  // =====================================================================
  {
    title: "Visão, PDFs e saídas estruturadas",
    lessons: [
      {
        title: "Enviando imagens: content blocks de imagem",
        readingMd: [
          "# Enviando imagens: content blocks de imagem",
          "",
          "Os modelos atuais do Claude são **multimodais**: aceitam texto e imagem como entrada. Você envia imagens dentro do array `content` de um turno, como **content blocks** do tipo `image`.",
          "",
          "## Estrutura do bloco de imagem",
          "",
          "Um bloco de imagem tem um `source`, que pode ser **base64**, **url** ou um **file_id** (via Files API).",
          "",
          "```json",
          "{",
          "  \"role\": \"user\",",
          "  \"content\": [",
          "    {",
          "      \"type\": \"image\",",
          "      \"source\": {",
          "        \"type\": \"base64\",",
          "        \"media_type\": \"image/jpeg\",",
          "        \"data\": \"<BASE64_DA_IMAGEM>\"",
          "      }",
          "    },",
          "    { \"type\": \"text\", \"text\": \"O que há nesta imagem?\" }",
          "  ]",
          "}",
          "```",
          "",
          "Variante por URL (mais simples quando a imagem já está hospedada):",
          "",
          "```json",
          "{ \"type\": \"image\", \"source\": { \"type\": \"url\", \"url\": \"https://exemplo.com/foto.png\" } }",
          "```",
          "",
          "O **`media_type`** deve casar com o formato real dos bytes. Formatos suportados: **JPEG, PNG, GIF e WebP** (animações não são suportadas — apenas o primeiro frame é usado).",
          "",
          "## Limites importantes",
          "",
          "- **Quantidade por requisição (API):** até 100 imagens em modelos com janela de 200k tokens, e até 600 nos demais. (Na claude.ai, até 20 por mensagem.)",
          "- **Dimensões:** no máximo 8000x8000 px. Acima de 20 imagens em uma requisição, aplica-se um limite por imagem mais estrito.",
          "- **Tamanho por imagem:** até 10 MB (base64) usando a Claude API diretamente.",
          "- O **limite de tamanho da requisição** (ex.: 32 MB) costuma ser atingido antes do limite de contagem; para muitas imagens, use a **Files API** e referencie por `file_id`.",
          "",
          "## Como Claude \"vê\" e quanto custa",
          "",
          "Claude processa a imagem em **patches** de 28x28 px (visual tokens). Imagens muito grandes são **redimensionadas** preservando a proporção. O custo em tokens cresce com a resolução, até um teto: imagens acima da resolução nativa são reduzidas antes do processamento. Para controlar custo e latência, **redimensione as imagens antes de enviar**.",
          "",
          "## Boas práticas de prompt com imagem",
          "",
          "- **Coloque a imagem ANTES do texto** no content quando possível — costuma render melhor.",
          "- Faça perguntas específicas (\"liste os itens da nota fiscal nesta foto\").",
          "- Você pode enviar **várias imagens** e pedir comparação; numere-as no texto (\"imagem 1\", \"imagem 2\").",
          "- Garanta **legibilidade**: imagens nítidas e texto não minúsculo melhoram a extração.",
          "",
          "> Leitura oficial: https://docs.anthropic.com/en/docs/build-with-claude/vision",
        ].join("\n"),
        flashcards: [
          {
            front: "Quais são os três tipos de source de um content block de imagem?",
            back: "base64 (com media_type + data), url (com url) e file (file_id via Files API).",
            tags: ["vision", "api"],
          },
          {
            front: "Quais formatos de imagem o Claude suporta?",
            back: "JPEG, PNG, GIF e WebP. Animações não são suportadas — apenas o primeiro frame é usado.",
            tags: ["vision"],
          },
          {
            front: "Onde colocar a imagem em relação ao texto no content, e por quê?",
            back: "Coloque a imagem ANTES do texto; costuma melhorar os resultados. Faça perguntas específicas sobre a imagem.",
            tags: ["vision", "prompt-engineering"],
          },
          {
            front: "Como Claude processa imagens e o que isso significa para custo?",
            back: "Em patches de 28x28 px (visual tokens). Imagens grandes são redimensionadas; o custo cresce com a resolução até um teto. Redimensione antes de enviar para controlar custo/latência.",
            tags: ["vision"],
          },
        ],
        questions: [
          {
            prompt: "Qual estrutura representa corretamente uma imagem base64 na Messages API?",
            options: [
              "{ \"type\": \"image_url\", \"url\": \"...\" }",
              "{ \"type\": \"image\", \"source\": { \"type\": \"base64\", \"media_type\": \"image/png\", \"data\": \"...\" } }",
              "{ \"role\": \"image\", \"content\": \"...\" }",
              "{ \"type\": \"file\", \"data\": \"...\" }",
            ],
            correctIndex: 1,
            explanation:
              "Um bloco de imagem tem type \"image\" e um source com type \"base64\", media_type e data. Também existem sources do tipo url e file (file_id).",
            difficulty: 2,
            tags: ["vision", "api"],
          },
          {
            prompt: "Qual formato de imagem NÃO é suportado pela visão do Claude?",
            options: ["JPEG", "PNG", "TIFF", "WebP"],
            correctIndex: 2,
            explanation:
              "Os formatos suportados são JPEG, PNG, GIF e WebP. TIFF não está na lista.",
            difficulty: 1,
            tags: ["vision"],
          },
          {
            prompt: "Boa prática ao enviar uma imagem junto com uma pergunta:",
            options: [
              "Colocar o texto antes e a imagem por último, sempre",
              "Colocar a imagem antes do texto, pois costuma melhorar os resultados",
              "Enviar a imagem como string no campo system",
              "Converter a imagem em JSON antes de enviar",
            ],
            correctIndex: 1,
            explanation:
              "A documentação recomenda colocar a imagem antes do texto para melhores resultados, além de fazer perguntas específicas.",
            difficulty: 1,
            tags: ["vision", "prompt-engineering"],
          },
        ],
        labs: [
          {
            title: "Montar uma requisição multimodal com duas imagens",
            promptMd: [
              "Você quer que Claude compare duas fotos de um produto (frente e verso) e liste diferenças visíveis.",
              "",
              "**Tarefa:** descreva o array content da mensagem user, com as duas imagens e o texto, seguindo as boas práticas (ordem, numeração, pergunta específica). Pode usar pseudo-base64.",
            ].join("\n"),
            rubric: [
              "Usa dois blocos type \"image\" com source válido (base64 ou url).",
              "Coloca as imagens antes do bloco de texto.",
              "Numera/identifica as imagens no texto (imagem 1, imagem 2).",
              "Faz uma pergunta específica (comparar/listar diferenças).",
              "media_type coerente com o formato indicado.",
            ],
            modelAnswer: [
              "```json",
              "{",
              "  \"role\": \"user\",",
              "  \"content\": [",
              "    { \"type\": \"image\", \"source\": { \"type\": \"base64\", \"media_type\": \"image/jpeg\", \"data\": \"<FRENTE_BASE64>\" } },",
              "    { \"type\": \"image\", \"source\": { \"type\": \"base64\", \"media_type\": \"image/jpeg\", \"data\": \"<VERSO_BASE64>\" } },",
              "    { \"type\": \"text\", \"text\": \"A imagem 1 é a frente e a imagem 2 é o verso do mesmo produto. Liste em bullets as diferenças visíveis entre elas (texto, selos, danos). Seja específico.\" }",
              "  ]",
              "}",
              "```",
              "",
              "Por que funciona: as imagens vêm antes do texto; o prompt as identifica como imagem 1 e 2,",
              "permitindo a comparação; a pergunta é específica e pede um formato (bullets). Em produção,",
              "eu redimensionaria as fotos antes de codificar para controlar tokens/latência e, se fossem",
              "reutilizadas, usaria a Files API com file_id.",
            ].join("\n"),
          },
        ],
      },
      {
        title: "Análise de PDFs com Claude",
        readingMd: [
          "# Análise de PDFs com Claude",
          "",
          "Claude consegue **ler PDFs**: extrai o texto E analisa os elementos visuais (gráficos, tabelas, diagramas). Isso porque o suporte a PDF se apoia na capacidade de visão — cada página é processada **como texto e como imagem**.",
          "",
          "## Como enviar um PDF",
          "",
          "Use um content block `document`. O `source` pode ser **url**, **base64** (`media_type: \"application/pdf\"`) ou **file** (file_id via Files API).",
          "",
          "```json",
          "{",
          "  \"role\": \"user\",",
          "  \"content\": [",
          "    {",
          "      \"type\": \"document\",",
          "      \"source\": {",
          "        \"type\": \"base64\",",
          "        \"media_type\": \"application/pdf\",",
          "        \"data\": \"<PDF_BASE64>\"",
          "      }",
          "    },",
          "    { \"type\": \"text\", \"text\": \"Quais são as principais conclusões deste documento?\" }",
          "  ]",
          "}",
          "```",
          "",
          "Variante por URL:",
          "",
          "```json",
          "{ \"type\": \"document\", \"source\": { \"type\": \"url\", \"url\": \"https://exemplo.com/relatorio.pdf\" } }",
          "```",
          "",
          "## O que Claude faz com o PDF (por dentro)",
          "",
          "1. Cada página é convertida em **imagem** e o **texto** de cada página é extraído.",
          "2. Claude analisa **texto + imagem** em conjunto — por isso consegue interpretar gráficos e tabelas, não só o texto puro.",
          "3. Responde referenciando o conteúdo textual e visual quando relevante.",
          "",
          "## Requisitos e limites",
          "",
          "- **Tamanho máximo da requisição:** ~32 MB (varia por plataforma) — vale para o payload inteiro.",
          "- **Páginas por requisição:** até 600 (e até 100 em modelos com janela de 200k tokens).",
          "- **Formato:** PDF padrão, **sem senha/criptografia**.",
          "- PDFs **densos** (muitas páginas, fontes pequenas, gráficos pesados) podem encher a janela de contexto antes do limite de páginas. Considere **dividir** o documento.",
          "",
          "## Boas práticas e custo",
          "",
          "- **Coloque o PDF antes do texto** na requisição.",
          "- Use **page numbers lógicos** (do visualizador) ao se referir a páginas no prompt.",
          "- Para PDFs reutilizados, use a **Files API** (referencie por `file_id`) e/ou **prompt caching** para acelerar análises repetidas.",
          "- **Custo:** cada página gera tokens de texto (tipicamente 1.500–3.000/página) **e** tokens de imagem (cada página vira imagem). Use *token counting* para estimar.",
          "",
          "> Dica: PDF + **citations** (próximo módulo) permite respostas com citações exatas das páginas, reduzindo alucinação.",
          "",
          "> Leitura oficial: https://docs.anthropic.com/en/docs/build-with-claude/pdf-support",
        ].join("\n"),
        flashcards: [
          {
            front: "Qual content block e media_type usar para enviar um PDF base64?",
            back: "Um bloco type \"document\" com source type \"base64\" e media_type \"application/pdf\" (também há sources url e file/file_id).",
            tags: ["pdf", "api"],
          },
          {
            front: "Por que Claude entende gráficos e tabelas de um PDF, não só o texto?",
            back: "Porque cada página é processada como texto E como imagem (o suporte a PDF usa visão). Claude analisa ambos em conjunto.",
            tags: ["pdf", "vision"],
          },
          {
            front: "Limites principais de PDF: tamanho de requisição e páginas?",
            back: "~32 MB por requisição (varia por plataforma) e até 600 páginas (100 em modelos com janela de 200k tokens). PDF deve ser padrão, sem senha.",
            tags: ["pdf"],
          },
          {
            front: "Como reduzir custo/latência ao analisar o mesmo PDF várias vezes?",
            back: "Enviar via Files API (file_id) e usar prompt caching para análises repetidas; dividir PDFs muito densos.",
            tags: ["pdf"],
          },
        ],
        questions: [
          {
            prompt: "Qual é o media_type correto para um PDF base64 em um bloco document?",
            options: ["text/pdf", "application/pdf", "image/pdf", "document/pdf"],
            correctIndex: 1,
            explanation:
              "Para PDFs base64 o media_type é application/pdf, dentro de um source de um content block type \"document\".",
            difficulty: 1,
            tags: ["pdf", "api"],
          },
          {
            prompt: "Por que Claude consegue responder sobre um gráfico dentro de um PDF?",
            options: [
              "Porque converte o PDF inteiro em uma planilha",
              "Porque cada página é processada como texto e como imagem, usando visão",
              "Porque executa OCR externo obrigatório fornecido pelo usuário",
              "Porque ignora elementos visuais e só lê o texto",
            ],
            correctIndex: 1,
            explanation:
              "O suporte a PDF se apoia em visão: cada página vira imagem além do texto extraído, permitindo interpretar gráficos, tabelas e diagramas.",
            difficulty: 2,
            tags: ["pdf", "vision"],
          },
          {
            prompt: "Qual afirmação sobre limites de PDF é correta?",
            options: [
              "PDFs com senha são suportados normalmente",
              "Não há limite de páginas por requisição",
              "O limite é de até 600 páginas (100 em modelos com janela de 200k tokens)",
              "O tamanho da requisição é ilimitado",
            ],
            correctIndex: 2,
            explanation:
              "São até 600 páginas por requisição (100 para modelos de 200k de contexto), com limite de ~32 MB no payload, e o PDF precisa ser padrão sem senha.",
            difficulty: 2,
            tags: ["pdf"],
          },
        ],
        labs: [
          {
            title: "Escolher a estratégia de envio de PDF",
            promptMd: [
              "Sua aplicação responde perguntas sobre o mesmo contrato (PDF de 40 páginas) muitas vezes ao dia, para usuários diferentes.",
              "",
              "**Tarefa:** descreva como você enviaria esse PDF de forma eficiente e quais recursos usaria para reduzir custo/latência sem perder a capacidade de analisar tabelas. Justifique.",
            ].join("\n"),
            rubric: [
              "Usa content block document com source adequado (Files API / file_id é ideal aqui).",
              "Justifica reutilização via Files API para evitar reencodar o PDF a cada chamada.",
              "Menciona prompt caching para acelerar análises repetidas do mesmo documento.",
              "Reconhece que cada página vira texto + imagem (visão), preservando tabelas/gráficos.",
              "Cita limites relevantes (tamanho/páginas) ou estratégia de divisão se necessário.",
            ],
            modelAnswer: [
              "Estratégia: fazer upload do contrato uma vez via Files API e referenciá-lo por file_id em",
              "cada requisição, em vez de reenviar 40 páginas em base64 toda vez (menos payload, menos",
              "latência). Aplicar prompt caching no bloco do documento para que as análises repetidas",
              "reutilizem o conteúdo já processado.",
              "",
              "```json",
              "{",
              "  \"role\": \"user\",",
              "  \"content\": [",
              "    { \"type\": \"document\", \"source\": { \"type\": \"file\", \"file_id\": \"file_abc123\" } },",
              "    { \"type\": \"text\", \"text\": \"Com base no contrato, qual é o prazo de rescisão? Cite a página.\" }",
              "  ]",
              "}",
              "```",
              "",
              "Como cada página é processada como texto e imagem, tabelas e cláusulas em layout complexo",
              "continuam interpretáveis. O contrato (40 páginas) está bem abaixo dos limites (600 páginas /",
              "~32 MB). Para perguntas que exigem rastreabilidade, eu ativaria citations no documento para",
              "obter a página exata de cada afirmação.",
            ].join("\n"),
          },
        ],
      },
      {
        title: "Saídas estruturadas: JSON confiável com tool use",
        readingMd: [
          "# Saídas estruturadas: JSON confiável com tool use",
          "",
          "Quando a saída de Claude alimenta **outro sistema** (banco de dados, API, frontend), você precisa de **JSON confiável** — com os campos certos, nos tipos certos, sempre. Pedir \"responda em JSON\" no prompt ajuda, mas não garante.",
          "",
          "## O problema do JSON \"só no prompt\"",
          "",
          "Instruir o formato em linguagem natural (mesmo com exemplos e XML tags) melhora muito, mas o modelo ainda pode: adicionar preâmbulos (\"Claro! Aqui está...\"), trocar nomes de campos, ou emitir JSON levemente inválido. Para integrações de produção, isso é frágil.",
          "",
          "## Técnicas, da mais leve à mais robusta",
          "",
          "### 1. Prompt + prefill (leve)",
          "Peça o JSON e faça **prefill** com `{` no turno assistant para pular preâmbulos. Bom para protótipos; ainda sem garantia de schema.",
          "",
          "### 2. Tool use (robusto e amplamente suportado)",
          "Você define uma **ferramenta** com um `input_schema` (JSON Schema). Quando Claude decide usá-la, ele devolve um bloco `tool_use` com `input` **já no formato do schema** — é a forma idiomática de obter dados estruturados.",
          "",
          "```json",
          "{",
          "  \"tools\": [",
          "    {",
          "      \"name\": \"registrar_contato\",",
          "      \"description\": \"Salva os dados extraídos de um contato.\",",
          "      \"input_schema\": {",
          "        \"type\": \"object\",",
          "        \"properties\": {",
          "          \"nome\": { \"type\": \"string\" },",
          "          \"email\": { \"type\": \"string\" },",
          "          \"prioridade\": { \"type\": \"string\", \"enum\": [\"alta\", \"media\", \"baixa\"] }",
          "        },",
          "        \"required\": [\"nome\", \"email\", \"prioridade\"]",
          "      }",
          "    }",
          "  ],",
          "  \"tool_choice\": { \"type\": \"tool\", \"name\": \"registrar_contato\" }",
          "}",
          "```",
          "",
          "Definir `tool_choice` para a ferramenta específica **força** Claude a chamá-la, e o `input` que volta segue o `input_schema`. Mesmo quando você não vai \"executar\" nada, usar uma ferramenta apenas como **molde de saída** é um padrão comum para extração estruturada.",
          "",
          "### 3. Structured outputs (quando disponível)",
          "Alguns modelos/recursos oferecem *structured outputs* com schema estrito, garantindo aderência ao formato por construção. Use quando precisar de garantia máxima de schema. **Atenção:** structured outputs e o recurso de **citations são incompatíveis** na mesma requisição.",
          "",
          "## Boas práticas de schema",
          "",
          "- Use **`enum`** para campos categóricos (evita variações de texto).",
          "- Marque **`required`** nos campos obrigatórios.",
          "- Descreva cada campo com **`description`** clara — Claude usa isso para preencher corretamente.",
          "- Valide a saída do seu lado (o schema orienta o modelo, mas validar é defensivo).",
          "",
          "> Leitura oficial: https://docs.anthropic.com/en/docs/build-with-claude/tool-use/overview",
        ].join("\n"),
        flashcards: [
          {
            front: "Por que \"responda em JSON\" só no prompt é frágil para produção?",
            back: "O modelo pode adicionar preâmbulos, trocar nomes de campos ou gerar JSON levemente inválido. Não há garantia de schema. Use tool use ou structured outputs.",
            tags: ["structured-outputs"],
          },
          {
            front: "Como tool use ajuda a obter JSON estruturado?",
            back: "Você define uma ferramenta com input_schema (JSON Schema). Claude retorna um bloco tool_use com input já no formato do schema — idiomático para extração estruturada, mesmo sem executar nada.",
            tags: ["structured-outputs"],
          },
          {
            front: "Como forçar Claude a usar uma ferramenta específica?",
            back: "Definindo tool_choice como { \"type\": \"tool\", \"name\": \"<nome>\" }. Isso força a chamada e o input volta seguindo o input_schema.",
            tags: ["structured-outputs"],
          },
          {
            front: "Citations e structured outputs podem ser usados juntos?",
            back: "Não — são incompatíveis na mesma requisição. Citations intercalam blocos de citação com o texto, o que conflita com o JSON estrito dos structured outputs.",
            tags: ["structured-outputs", "citations"],
          },
        ],
        questions: [
          {
            prompt: "Qual é a forma idiomática de obter dados estruturados (JSON com campos garantidos pelo schema) do Claude?",
            options: [
              "Aumentar max_tokens e pedir JSON no prompt",
              "Definir uma ferramenta com input_schema e ler o input do bloco tool_use",
              "Usar stop_sequences com }",
              "Definir temperature = 0",
            ],
            correctIndex: 1,
            explanation:
              "Tool use com input_schema faz Claude devolver tool_use cujo input segue o JSON Schema. É o padrão idiomático para extração estruturada.",
            difficulty: 2,
            tags: ["structured-outputs"],
          },
          {
            prompt: "Como você força Claude a chamar uma ferramenta específica para extração?",
            options: [
              "tool_choice: { \"type\": \"auto\" }",
              "tool_choice: { \"type\": \"tool\", \"name\": \"<nome_da_ferramenta>\" }",
              "Definindo system com o nome da ferramenta",
              "Não é possível forçar; depende do modelo",
            ],
            correctIndex: 1,
            explanation:
              "tool_choice do tipo tool com o name força o uso daquela ferramenta; o input retornado segue seu input_schema.",
            difficulty: 2,
            tags: ["structured-outputs"],
          },
          {
            prompt: "Qual combinação NÃO é permitida na mesma requisição?",
            options: [
              "Tool use + prompt caching",
              "Citations + structured outputs",
              "Imagem + texto no mesmo content",
              "PDF + prompt caching",
            ],
            correctIndex: 1,
            explanation:
              "Citations e structured outputs são incompatíveis: enviar os dois (ex.: citations habilitado + output_config.format) retorna erro 400.",
            difficulty: 3,
            tags: ["structured-outputs", "citations"],
          },
        ],
        labs: [
          {
            title: "Definir uma ferramenta como molde de saída",
            promptMd: [
              "Você precisa extrair de avaliações de produto um objeto com: nota (1 a 5), sentimento (positivo/neutro/negativo) e um resumo curto.",
              "",
              "**Tarefa:** defina a ferramenta (name, description, input_schema com tipos/enum/required) e explique como forçar seu uso e por que isso é mais confiável do que pedir JSON no prompt.",
            ].join("\n"),
            rubric: [
              "Define name e description claros para a ferramenta.",
              "input_schema com type object e properties tipadas.",
              "Usa enum para sentimento e limites/tipo para nota.",
              "Marca required nos campos obrigatórios.",
              "Explica tool_choice forçado e por que é mais confiável que JSON só no prompt.",
            ],
            modelAnswer: [
              "```json",
              "{",
              "  \"tools\": [{",
              "    \"name\": \"registrar_avaliacao\",",
              "    \"description\": \"Registra a análise estruturada de uma avaliação de produto.\",",
              "    \"input_schema\": {",
              "      \"type\": \"object\",",
              "      \"properties\": {",
              "        \"nota\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 5, \"description\": \"Nota de 1 a 5\" },",
              "        \"sentimento\": { \"type\": \"string\", \"enum\": [\"positivo\", \"neutro\", \"negativo\"] },",
              "        \"resumo\": { \"type\": \"string\", \"description\": \"Resumo em até 15 palavras\" }",
              "      },",
              "      \"required\": [\"nota\", \"sentimento\", \"resumo\"]",
              "    }",
              "  }],",
              "  \"tool_choice\": { \"type\": \"tool\", \"name\": \"registrar_avaliacao\" }",
              "}",
              "```",
              "",
              "Forçando tool_choice para registrar_avaliacao, Claude obrigatoriamente devolve um bloco",
              "tool_use cujo input segue o input_schema: nota é inteiro de 1 a 5, sentimento é um dos três",
              "valores do enum e todos os campos required estão presentes. Isso é mais confiável do que",
              "pedir JSON no prompt porque o schema restringe a forma da saída (tipos, enum, obrigatórios),",
              "em vez de depender de o modelo lembrar o formato. Ainda assim, valido o input no meu código",
              "como camada defensiva.",
            ].join("\n"),
          },
        ],
      },
    ],
  },

  // =====================================================================
  // MÓDULO — MODELOS, JANELA DE CONTEXTO E EXTENDED THINKING
  // =====================================================================
  {
    title: "Modelos, janela de contexto e raciocínio",
    lessons: [
      {
        title: "A família de modelos e como escolher o tier",
        readingMd: [
          "# A família de modelos e como escolher o tier",
          "",
          "Claude é uma **família** de modelos. Para arquitetar uma solução, você escolhe o **tier** certo equilibrando **capacidade × velocidade × custo**. Os tiers principais:",
          "",
          "- **Opus** — o tier **mais capaz**, para raciocínio complexo, tarefas agênticas de longo horizonte e trabalho de alta autonomia. Maior capacidade, geralmente maior custo e latência.",
          "- **Sonnet** — o **equilíbrio** entre inteligência e velocidade. Ótima escolha padrão para a maioria das cargas de produção.",
          "- **Haiku** — o **mais rápido e econômico**, com inteligência próxima da fronteira para muitas tarefas. Ideal para alto volume, baixa latência e tarefas mais simples.",
          "",
          "> Regra prática: comece pelo **Sonnet** (bom equilíbrio). Suba para **Opus** quando a tarefa exigir o máximo de raciocínio; desça para **Haiku** quando velocidade/custo dominarem e a tarefa for mais direta.",
          "",
          "## Não decore versões e preços — consulte a página oficial",
          "",
          "Os **números de versão** (ex.: famílias 4.x) e os **preços por milhão de tokens** mudam ao longo do tempo. Para arquitetar, o que importa é entender os **tiers** e suas características. Sempre confirme o **ID exato do modelo**, a janela de contexto, o limite de saída e o preço atual na **página oficial de modelos** antes de fixar em produção.",
          "",
          "## Características que variam por modelo",
          "",
          "- **Janela de contexto** (quanto cabe de entrada — veja a próxima lição).",
          "- **Máximo de tokens de saída** (`max_tokens` da resposta).",
          "- **Suporte a raciocínio nativo (thinking)** (varia entre modelos).",
          "- **Latência comparativa** (Haiku é o mais rápido; Opus tende a ser o mais lento).",
          "- Todos os modelos atuais suportam **texto e imagem** na entrada e **visão**.",
          "",
          "## IDs de modelo são snapshots fixos",
          "",
          "Cada ID de modelo é um **snapshot fixo** (pinned), não um ponteiro \"sempre o mais novo\". Fixe um ID específico em produção para reprodutibilidade e migre conscientemente quando quiser uma versão nova. Você também pode consultar capacidades e limites programaticamente pela **Models API**.",
          "",
          "## Como decidir (checklist)",
          "",
          "1. A tarefa é difícil (raciocínio profundo, agente de longo horizonte)? → tenda a **Opus**.",
          "2. É uma carga geral de produção com bom custo-benefício? → **Sonnet**.",
          "3. É alto volume, simples e sensível a latência/custo? → **Haiku**.",
          "4. Precisa de janela de contexto muito grande ou de raciocínio (thinking)? → confira quais modelos oferecem na página oficial.",
          "",
          "> Leitura oficial: https://docs.anthropic.com/en/docs/about-claude/models/overview",
        ].join("\n"),
        flashcards: [
          {
            front: "Resuma os três tiers principais de modelos Claude.",
            back: "Opus = mais capaz (raciocínio complexo/agêntico, maior custo/latência); Sonnet = equilíbrio inteligência×velocidade (padrão); Haiku = mais rápido e econômico para alto volume e tarefas simples.",
            tags: ["models"],
          },
          {
            front: "Qual tier escolher como ponto de partida e quando mudar?",
            back: "Comece pelo Sonnet (equilíbrio). Suba para Opus em tarefas de raciocínio máximo; desça para Haiku quando velocidade/custo dominarem e a tarefa for simples.",
            tags: ["models"],
          },
          {
            front: "Por que não decorar versões e preços de modelos?",
            back: "Mudam com o tempo. O que importa é entender os tiers; confirme ID exato, janela de contexto, max de saída e preço atual na página oficial de modelos antes de fixar em produção.",
            tags: ["models"],
          },
          {
            front: "ID de modelo: snapshot fixo ou ponteiro para o mais novo?",
            back: "Snapshot fixo (pinned). Fixe um ID específico para reprodutibilidade e migre conscientemente. Capacidades/limites podem ser consultados via Models API.",
            tags: ["models"],
          },
        ],
        questions: [
          {
            prompt: "Qual tier de modelo é, em geral, o mais indicado para alto volume e baixa latência em tarefas mais simples?",
            options: ["Opus", "Sonnet", "Haiku", "Todos têm a mesma latência"],
            correctIndex: 2,
            explanation:
              "Haiku é o tier mais rápido e econômico, ideal para alto volume e baixa latência. Opus é o mais capaz (e mais lento); Sonnet é o equilíbrio.",
            difficulty: 1,
            tags: ["models"],
          },
          {
            prompt: "Você tem uma carga geral de produção e quer bom custo-benefício sem abrir mão de inteligência. Qual é o ponto de partida recomendado?",
            options: [
              "Sempre Opus, independentemente do custo",
              "Sonnet, pelo equilíbrio entre velocidade e inteligência",
              "Haiku, pois é sempre suficiente",
              "Depende apenas da temperature",
            ],
            correctIndex: 1,
            explanation:
              "Sonnet oferece o melhor equilíbrio velocidade×inteligência e é o ponto de partida típico; ajusta-se para Opus ou Haiku conforme a necessidade.",
            difficulty: 1,
            tags: ["models"],
          },
          {
            prompt: "O que um ID de modelo (pinned snapshot) garante?",
            options: [
              "Que você sempre recebe a versão mais nova automaticamente",
              "Que o ID aponta para uma versão fixa, dando reprodutibilidade até você migrar",
              "Que o preço nunca muda",
              "Que a janela de contexto é infinita",
            ],
            correctIndex: 1,
            explanation:
              "IDs são snapshots fixos: garantem comportamento reprodutível de uma versão específica. Você migra conscientemente; não é um ponteiro evergreen.",
            difficulty: 2,
            tags: ["models"],
          },
        ],
        labs: [
          {
            title: "Selecionar o tier para três cargas distintas",
            promptMd: [
              "Para cada cenário, escolha um tier (Opus/Sonnet/Haiku) e justifique em 1-2 frases:",
              "",
              "A) Classificar 2 milhões de mensagens/dia em 3 categorias, com latência baixa.",
              "B) Um agente que planeja e executa refatorações grandes de código em múltiplos passos.",
              "C) Um chatbot de atendimento geral de produção, com bom custo-benefício.",
            ].join("\n"),
            rubric: [
              "A) escolhe Haiku, citando alto volume + baixa latência + tarefa simples.",
              "B) escolhe Opus, citando raciocínio complexo/agêntico de longo horizonte.",
              "C) escolhe Sonnet, citando equilíbrio custo×inteligência para produção geral.",
              "Justificativas coerentes com as características de cada tier.",
              "Menciona confirmar ID/janela/preço atual na página oficial antes de fixar.",
            ],
            modelAnswer: [
              "A) **Haiku.** Classificação em 3 categorias é uma tarefa simples e de alto volume (2M/dia)",
              "com requisito de latência baixa — exatamente o ponto forte do tier mais rápido e econômico.",
              "",
              "B) **Opus.** Planejar e executar refatorações grandes em múltiplos passos é trabalho agêntico",
              "de longo horizonte com raciocínio profundo — o caso de uso do tier mais capaz.",
              "",
              "C) **Sonnet.** Um chatbot de produção geral pede o melhor equilíbrio entre inteligência e",
              "velocidade/custo, que é a proposta do Sonnet.",
              "",
              "Antes de fixar qualquer um em produção, eu confirmaria o ID exato do modelo, a janela de",
              "contexto, o limite de saída e o preço atual na página oficial de modelos, e fixaria o ID",
              "(pinned snapshot) para reprodutibilidade.",
            ].join("\n"),
          },
        ],
      },
      {
        title: "Janela de contexto e raciocínio (thinking)",
        readingMd: [
          "# Janela de contexto e raciocínio (thinking)",
          "",
          "Dois conceitos que definem o que cabe e como Claude raciocina: a **janela de contexto** e o **raciocínio (thinking)**.",
          "",
          "## Janela de contexto",
          "",
          "A **janela de contexto** é o total de tokens que o modelo consegue considerar de uma vez — **entrada + saída** na mesma conta. Tudo o que você manda (system prompt, histórico de mensagens, documentos, imagens) **mais** o que o modelo gera precisa caber nessa janela.",
          "",
          "Pontos-chave:",
          "",
          "- A janela varia por modelo (alguns modelos têm janelas grandes; consulte a página oficial para o número exato de cada um).",
          "- Tokens **não são palavras**: aproxime, mas conte tokens de verdade quando o limite importar (há *token counting* na API).",
          "- O **`max_tokens`** da resposta limita só a saída; ele compete pelo mesmo orçamento da janela. Em modelos de janela muito grande, há limites próprios de saída.",
          "- Estratégias para caber: resumir histórico, recuperar só trechos relevantes (RAG), dividir documentos, usar prompt caching para conteúdo repetido.",
          "",
          "## Raciocínio do modelo: do extended thinking ao adaptive thinking",
          "",
          "Claude pode **raciocinar passo a passo internamente antes de responder**, emitindo blocos `thinking` antes do `text` final. É um recurso **nativo da API** — diferente do chain-of-thought via prompt (que é só texto comum gerado na saída).",
          "",
          "**O jeito atual e recomendado é o adaptive thinking:** você liga e o **próprio Claude decide quando e o quanto pensar** a cada requisição. Não há orçamento de tokens para você calibrar na mão.",
          "",
          "```json",
          "{",
          "  \"model\": \"claude-sonnet-4-6\",",
          "  \"max_tokens\": 16000,",
          "  \"thinking\": { \"type\": \"adaptive\" },",
          "  \"output_config\": { \"effort\": \"high\" },",
          "  \"messages\": [ { \"role\": \"user\", \"content\": \"...\" } ]",
          "}",
          "```",
          "",
          "### O parâmetro `effort` (quanto esforço gastar)",
          "",
          "O quanto de esforço (raciocínio + ação) o modelo gasta é controlado por **`effort`**, dentro de `output_config`:",
          "",
          "- Níveis: **`low` · `medium` · `high` · `xhigh` · `max`** (o padrão é `high`).",
          "- `low` é mais rápido/barato para tarefas simples; `high`/`xhigh` para trabalho que exige inteligência (código, agentes); `max` quando o acerto importa mais que o custo.",
          "- A disponibilidade dos níveis varia por modelo — confirme na doc oficial.",
          "",
          "### E o `budget_tokens`? (legado — cuidado na prova e na prática)",
          "",
          "O modo antigo era manual: `thinking: { \"type\": \"enabled\", \"budget_tokens\": N }`, com a regra de que **`budget_tokens` deveria ser menor que `max_tokens`**. **Isso é legado:** nos modelos de ponta atuais (ex.: Opus 4.8 e 4.7) o parâmetro foi **removido e retorna erro 400**; em modelos como Sonnet 4.6 está **deprecado**. Para conteúdo novo, **use `thinking: {type: \"adaptive\"}` + `effort`** — não `budget_tokens`.",
          "",
          "### Detalhes úteis",
          "",
          "- A resposta traz blocos `thinking` antes do bloco `text`. Nos modelos mais novos, o **texto do raciocínio vem omitido por padrão** — para exibir um resumo, peça `thinking: { \"type\": \"adaptive\", \"display\": \"summarized\" }`.",
          "- Com **tool use**, o adaptive thinking intercala o raciocínio entre as chamadas de ferramenta automaticamente; preserve os blocos `thinking` ao devolver os resultados.",
          "",
          "## Quando ligar o raciocínio",
          "",
          "Bom para **matemática, raciocínio de múltiplos passos, análise/depuração de código, planejamento e pesquisa**. Para tarefas simples ou de alto volume (classificação, saudações), só adiciona custo e latência — deixe desligado ou em `effort` baixo.",
          "",
          "> Leitura oficial: https://platform.claude.com/docs/en/build-with-claude/adaptive-thinking (e a página de `effort`).",
        ].join("\n"),
        flashcards: [
          {
            front: "O que é a janela de contexto e o que entra nela?",
            back: "É o total de tokens que o modelo considera de uma vez — entrada (system, histórico, documentos, imagens) E saída na mesma conta. Tudo precisa caber nesse limite.",
            tags: ["models"],
          },
          {
            front: "Qual é a forma atual de ligar o raciocínio do modelo na API?",
            back: "Adaptive thinking: thinking: { type: \"adaptive\" } — o próprio Claude decide quando e quanto pensar. O quanto de esforço é controlado por output_config.effort (low/medium/high/xhigh/max). Não se usa mais budget_tokens nos modelos atuais.",
            tags: ["thinking", "api"],
          },
          {
            front: "O parâmetro budget_tokens (thinking type enabled) ainda deve ser usado?",
            back: "Não para conteúdo novo. É legado: foi removido (erro 400) nos modelos de ponta atuais e está deprecado nos demais. Use thinking adaptive + effort no lugar.",
            tags: ["thinking", "migracao"],
          },
          {
            front: "Quando vale a pena ligar o raciocínio (thinking)?",
            back: "Em tarefas complexas: matemática, raciocínio de múltiplos passos, análise/depuração de código, planejamento e pesquisa. Em tarefas simples ou de alto volume, só adiciona custo/latência — deixe desligado ou em effort baixo.",
            tags: ["thinking"],
          },
        ],
        questions: [
          {
            prompt: "O que a janela de contexto de um modelo limita?",
            options: [
              "Apenas o tamanho do system prompt",
              "Apenas a saída gerada",
              "O total de tokens considerados de uma vez, somando entrada e saída",
              "O número de ferramentas que você pode definir",
            ],
            correctIndex: 2,
            explanation:
              "A janela de contexto cobre entrada + saída juntas. Todo o prompt, histórico, documentos e a resposta gerada precisam caber nela.",
            difficulty: 2,
            tags: ["models"],
          },
          {
            prompt: "Qual é a forma recomendada hoje de controlar o raciocínio de Claude na API?",
            options: [
              "Definir budget_tokens menor que max_tokens",
              "Usar thinking adaptive e o parâmetro effort",
              "Aumentar a temperature",
              "Sempre desligar o thinking",
            ],
            correctIndex: 1,
            explanation:
              "O paradigma atual é adaptive thinking (thinking: {type: \"adaptive\"}) combinado com output_config.effort. O budget_tokens é legado — removido nos modelos de ponta (erro 400) e deprecado nos demais.",
            difficulty: 2,
            tags: ["thinking"],
          },
          {
            prompt: "Qual cenário é o MAIS apropriado para ligar o raciocínio (thinking)?",
            options: [
              "Ecoar de volta o texto enviado pelo usuário",
              "Resolver um problema de matemática com vários passos de raciocínio",
              "Classificar um e-mail como spam/não-spam em alto volume",
              "Retornar uma string fixa de saudação",
            ],
            correctIndex: 1,
            explanation:
              "O raciocínio brilha em problemas complexos de múltiplos passos (matemática, código, planejamento). Tarefas triviais ou de alto volume simples não justificam o custo extra.",
            difficulty: 1,
            tags: ["thinking"],
          },
        ],
        labs: [
          {
            title: "Configurar o raciocínio (adaptive thinking + effort) para uma tarefa de lógica",
            promptMd: [
              "Você quer que Claude resolva problemas de lógica de múltiplos passos, mostrando que raciocinou, com a resposta final clara.",
              "",
              "**Tarefa:** escreva o corpo da requisição ligando o raciocínio pelo paradigma **atual**, escolha um nível de `effort` coerente, explique por que **não** usaria `budget_tokens` hoje e diga quando **não** ligar raciocínio.",
            ].join("\n"),
            rubric: [
              "Usa thinking: { type: \"adaptive\" } (e NÃO budget_tokens).",
              "Inclui output_config.effort com um nível coerente (ex.: high para raciocínio).",
              "Explica que budget_tokens é legado (removido nos modelos de ponta / deprecado nos demais) e por isso o evitou.",
              "Indica que a resposta traz blocos thinking antes do text (e que o texto do raciocínio pode vir omitido por padrão; display: summarized para resumir).",
              "Diz quando NÃO ligar raciocínio (tarefas simples/alto volume) por custo/latência.",
            ],
            modelAnswer: [
              "```json",
              "{",
              "  \"model\": \"claude-sonnet-4-6\",",
              "  \"max_tokens\": 16000,",
              "  \"thinking\": { \"type\": \"adaptive\" },",
              "  \"output_config\": { \"effort\": \"high\" },",
              "  \"messages\": [",
              "    { \"role\": \"user\", \"content\": \"Há infinitos primos p com p mod 4 == 3? Justifique passo a passo.\" }",
              "  ]",
              "}",
              "```",
              "",
              "Liguei o raciocínio com `thinking: {type: \"adaptive\"}` — o próprio Claude decide quando e quanto",
              "pensar — e usei `effort: \"high\"` porque é uma tarefa que exige inteligência. NÃO usei `budget_tokens`:",
              "ele é legado (removido com erro 400 nos modelos de ponta atuais, deprecado nos demais).",
              "",
              "A resposta vem com blocos `thinking` antes do `text`. Nos modelos novos o texto do raciocínio",
              "vem omitido por padrão; se eu quisesse exibir um resumo, pediria `display: \"summarized\"`.",
              "",
              "Eu NÃO ligaria raciocínio para tarefas simples ou de alto volume (classificação, saudações, ecos),",
              "porque adiciona custo e latência sem ganho — nesses casos, deixo desligado ou em `effort` baixo.",
            ].join("\n"),
          },
        ],
      },
    ],
  },

  // =====================================================================
  // MÓDULO — AVALIAÇÃO E QUALIDADE
  // =====================================================================
  {
    title: "Avaliação e qualidade",
    lessons: [
      {
        title: "Por que avaliar e como construir test sets",
        readingMd: [
          "# Por que avaliar e como construir test sets",
          "",
          "Construir uma aplicação com LLM começa por **definir critérios de sucesso** e **medir** o desempenho contra eles. Sem avaliações (*evals*), você itera no escuro: muda o prompt e não sabe se melhorou ou piorou.",
          "",
          "## Critérios de sucesso bons são...",
          "",
          "- **Específicos:** \"classificação de sentimento precisa\", não \"bom desempenho\".",
          "- **Mensuráveis:** uma métrica quantitativa (acurácia, F1, tempo de resposta) ou uma escala qualitativa aplicada de forma consistente. Até temas \"nebulosos\" como segurança podem ser quantificados (ex.: \"menos de 0,1% das saídas sinalizadas como tóxicas em 10.000 testes\").",
          "- **Atingíveis:** baseados em benchmarks, experimentos anteriores ou conhecimento de domínio.",
          "- **Relevantes:** alinhados ao propósito da aplicação (precisão de citação é crítica em app médico, menos em um chatbot casual).",
          "",
          "A maioria dos casos precisa de avaliação **multidimensional**: por exemplo, F1 ≥ 0,85 **e** 99,5% de saídas não tóxicas **e** 95% das respostas abaixo de 200 ms.",
          "",
          "## Construindo o conjunto de testes (test set / eval suite)",
          "",
          "Princípios de design de evals:",
          "",
          "1. **Seja específico da tarefa:** os casos de teste devem **espelhar a distribuição real** do seu problema — incluindo **casos de borda** (entrada irrelevante/inexistente, entrada longa demais, input do usuário ruim/ambíguo, casos em que até humanos discordariam).",
          "2. **Automatize quando possível:** estruture as questões para permitir correção automática (múltipla escolha, string match, correção por código, correção por LLM).",
          "3. **Priorize volume sobre perfeição:** muitas questões com correção automática (sinal um pouco menor) costumam valer mais do que poucas questões corrigidas à mão.",
          "",
          "> Use um **held-out test set** (conjunto separado, não usado para ajustar o prompt) para validar de forma honesta.",
          "",
          "## O ciclo",
          "",
          "Critérios → casos de teste → prompt preliminar → testar/iterar → validação final → enviar. Esse loop é o coração da engenharia de prompts.",
          "",
          "> Dica: peça ao próprio Claude para **gerar mais casos de teste** a partir de alguns exemplos-semente, e para brainstorm de métricas.",
          "",
          "> Leitura oficial: https://docs.anthropic.com/en/docs/test-and-evaluate/develop-tests",
        ].join("\n"),
        flashcards: [
          {
            front: "Quais são as quatro qualidades de um bom critério de sucesso?",
            back: "Específico, Mensurável, Atingível e Relevante. Ex.: \"F1 ≥ 0,85 num test set de 10.000 posts\" em vez de \"classificar bem\".",
            tags: ["evals"],
          },
          {
            front: "Três princípios de design de evals?",
            back: "(1) Ser específico da tarefa e cobrir casos de borda; (2) automatizar a correção quando possível; (3) priorizar volume de questões sobre poucas corrigidas à mão.",
            tags: ["evals"],
          },
          {
            front: "O que é um held-out test set e por que usar?",
            back: "Um conjunto separado, não usado para ajustar o prompt, reservado para validar o desempenho de forma honesta (evita superajuste ao próprio conjunto de iteração).",
            tags: ["evals"],
          },
          {
            front: "Por que cobrir casos de borda nos evals?",
            back: "Porque os evals devem espelhar a distribuição real, incluindo entradas estranhas, longas, ambíguas ou maliciosas — onde os erros mais importam.",
            tags: ["evals"],
          },
        ],
        questions: [
          {
            prompt: "Qual é o melhor exemplo de critério de sucesso, segundo a documentação?",
            options: [
              "\"O modelo deve classificar sentimentos bem\"",
              "\"F1 de pelo menos 0,85 num test set de 10.000 posts diversos, 5% acima do baseline\"",
              "\"As respostas devem ser legais\"",
              "\"O modelo deve ser rápido\"",
            ],
            correctIndex: 1,
            explanation:
              "Bons critérios são específicos, mensuráveis, atingíveis e relevantes. A opção com F1, tamanho do test set e comparação com baseline atende a todos.",
            difficulty: 2,
            tags: ["evals"],
          },
          {
            prompt: "Segundo os princípios de design de evals, o que é geralmente preferível?",
            options: [
              "Poucas questões corrigidas à mão com altíssima qualidade",
              "Muitas questões com correção automática, mesmo com sinal um pouco menor",
              "Nenhum caso de borda, para não confundir a métrica",
              "Apenas correção humana, sempre",
            ],
            correctIndex: 1,
            explanation:
              "A documentação recomenda priorizar volume com correção automatizada sobre poucos casos hand-graded — mais sinal agregado e escalável.",
            difficulty: 2,
            tags: ["evals"],
          },
          {
            prompt: "Por que usar um held-out test set ao iterar prompts?",
            options: [
              "Para aumentar a janela de contexto",
              "Para validar o desempenho sem superajustar ao conjunto usado na iteração",
              "Porque é obrigatório pela Messages API",
              "Para reduzir o número de tokens de saída",
            ],
            correctIndex: 1,
            explanation:
              "Um conjunto reservado (held-out) dá uma medida honesta do desempenho, evitando que você \"acerte\" só no conjunto que usou para ajustar.",
            difficulty: 2,
            tags: ["evals"],
          },
        ],
        labs: [
          {
            title: "Definir critérios e esboçar um test set",
            promptMd: [
              "Sua equipe vai lançar um classificador que rotula tickets de suporte em: cobrança, técnico, conta, outro.",
              "",
              "**Tarefa:** (1) escreva um critério de sucesso bom (específico, mensurável, atingível, relevante) e (2) descreva como montaria o test set, incluindo casos de borda e o método de correção.",
            ].join("\n"),
            rubric: [
              "Critério é específico e mensurável (métrica + alvo numérico).",
              "Critério é atingível e relevante para o caso (classificação).",
              "Test set espelha a distribuição real das categorias.",
              "Inclui casos de borda explícitos (ambíguos, multi-tópico, entrada ruim).",
              "Escolhe um método de correção automatizável (ex.: exact match).",
            ],
            modelAnswer: [
              "**Critério de sucesso:** num held-out test set de 2.000 tickets rotulados por humanos,",
              "o classificador deve atingir acurácia (exact match) de pelo menos 0,90 nas 4 categorias,",
              "com no máximo 1% de tickets de \"cobrança\" classificados como \"outro\" (erro caro).",
              "É específico (acurácia + alvo), mensurável (0,90), atingível (acima do baseline manual)",
              "e relevante (a categoria correta direciona o atendimento).",
              "",
              "**Test set:** coletar tickets reais respeitando a proporção real das categorias (espelhar a",
              "distribuição). Incluir casos de borda: tickets multi-tópico (cobrança + técnico), mensagens",
              "ambíguas onde até humanos discordariam, entradas muito curtas/longas e ruído (typos, idioma",
              "misturado). Correção por **exact match** contra o rótulo de ouro (normalizando caixa/espaços),",
              "que é rápida, escalável e ideal para categorias fechadas. Eu pediria ao Claude para ajudar a",
              "gerar variações de casos de borda a partir de exemplos-semente.",
            ].join("\n"),
          },
        ],
      },
      {
        title: "Métricas, grading e citations para reduzir alucinação",
        readingMd: [
          "# Métricas, grading e citations para reduzir alucinação",
          "",
          "Tendo o test set, falta **corrigir** (grading) e **iterar**. E, para tarefas baseadas em documentos, o recurso de **citations** ajuda a reduzir alucinação ancorando as respostas nas fontes.",
          "",
          "## Três métodos de grading",
          "",
          "Escolha o método mais rápido, confiável e escalável que sirva:",
          "",
          "1. **Correção por código** — a mais rápida e confiável; ótima para respostas categóricas. Ex.: *exact match* (`saida == gabarito`) ou *string match* (`frase_chave in saida`). Falta nuance para julgamentos complexos.",
          "2. **Correção humana** — a mais flexível e de alta qualidade, mas **lenta e cara**. Evite quando possível.",
          "3. **Correção por LLM (LLM-as-judge)** — rápida, flexível e escalável para julgamentos complexos. Valide a confiabilidade antes de escalar.",
          "",
          "### Dicas para LLM-as-judge",
          "",
          "- **Rubricas claras e detalhadas** (\"se não mencionar X, é incorreto\").",
          "- Saída **empírica e específica:** peça apenas `correto`/`incorreto` ou uma nota de 1 a 5 — facilita agregar.",
          "- **Incentive o raciocínio** antes do veredito (pense em <thinking>, depois decida em <result>); melhora a qualidade do julgamento.",
          "- De preferência, use um **modelo diferente** para julgar do que o que gerou a resposta.",
          "",
          "## Métricas comuns",
          "",
          "- **Acurácia / precisão / recall / F1** (classificação).",
          "- **Similaridade de cosseno** entre embeddings (consistência de respostas a perguntas equivalentes).",
          "- **ROUGE-L** (qualidade de sumarização).",
          "- **Escalas Likert/ordinal via LLM** (tom, empatia, uso de contexto).",
          "",
          "## Citations: ancorar respostas em fontes",
          "",
          "O recurso de **citations** faz Claude **citar trechos exatos** dos documentos fornecidos, o que **reduz alucinação** (a resposta passa a apontar para a fonte) e dá rastreabilidade. Ative com `citations: { \"enabled\": true }` em cada bloco `document`.",
          "",
          "```json",
          "{",
          "  \"type\": \"document\",",
          "  \"source\": { \"type\": \"text\", \"media_type\": \"text/plain\", \"data\": \"A grama é verde. O céu é azul.\" },",
          "  \"title\": \"Meu Documento\",",
          "  \"citations\": { \"enabled\": true }",
          "}",
          "```",
          "",
          "Como vêm as citações na resposta: blocos `text` ganham um array `citations`, cada citação com `cited_text` (o trecho exato), `document_index` e a **localização** — por **caractere** (texto puro), **página** (PDF) ou **índice de bloco** (custom content).",
          "",
          "Vantagens sobre pedir citação só no prompt: maior **confiabilidade** (ponteiros válidos para o documento), **qualidade** (cita os trechos mais relevantes) e **economia** (o `cited_text` não conta como tokens de saída).",
          "",
          "> Atenção: citations e **structured outputs** são **incompatíveis** na mesma requisição. Todos os documentos da requisição devem ter citations habilitado (ou nenhum).",
          "",
          "## Iterar com base nos evals",
          "",
          "Rode o test set, meça, identifique os erros, ajuste o prompt (clareza, exemplos, CoT, citations) e **rode de novo**. Esse loop — medir, mudar, remedir — é o que transforma um protótipo em algo de produção.",
          "",
          "> Leitura oficial: https://docs.anthropic.com/en/docs/build-with-claude/citations",
        ].join("\n"),
        flashcards: [
          {
            front: "Quais são os três métodos de grading de evals, do mais ao menos escalável?",
            back: "Correção por código (exact/string match) — mais rápida/confiável; correção por LLM (LLM-as-judge) — flexível e escalável; correção humana — alta qualidade, porém lenta e cara.",
            tags: ["evals"],
          },
          {
            front: "Boas práticas de LLM-as-judge?",
            back: "Rubricas claras e detalhadas; saída empírica (correto/incorreto ou nota 1–5); incentivar raciocínio antes do veredito; preferir um modelo diferente do que gerou a resposta.",
            tags: ["evals"],
          },
          {
            front: "Como o recurso de citations reduz alucinação?",
            back: "Faz Claude citar trechos exatos (cited_text) dos documentos fornecidos, ancorando cada afirmação a uma fonte rastreável (por caractere, página ou bloco), em vez de inventar.",
            tags: ["citations"],
          },
          {
            front: "Como ativar citations e o que vem na resposta?",
            back: "citations: { \"enabled\": true } em cada bloco document. Na resposta, blocos text trazem um array citations com cited_text, document_index e a localização (char/página/bloco).",
            tags: ["citations", "api"],
          },
        ],
        questions: [
          {
            prompt: "Qual método de grading é o mais rápido e confiável, ideal para respostas categóricas?",
            options: [
              "Correção humana",
              "Correção por código (ex.: exact match)",
              "LLM-as-judge sem rubrica",
              "Nenhum, é sempre necessário humano",
            ],
            correctIndex: 1,
            explanation:
              "Correção por código (exact/string match) é a mais rápida, confiável e escalável para respostas categóricas; falta nuance para julgamentos complexos.",
            difficulty: 1,
            tags: ["evals"],
          },
          {
            prompt: "Ao usar LLM-as-judge, qual prática melhora a qualidade do julgamento?",
            options: [
              "Pedir uma resposta longa e livre, sem formato definido",
              "Pedir raciocínio antes e então um veredito empírico (ex.: correto/incorreto)",
              "Usar sempre o mesmo modelo que gerou a resposta, sem rubrica",
              "Evitar rubricas para não enviesar",
            ],
            correctIndex: 1,
            explanation:
              "Rubricas claras, saída empírica e raciocínio antes do veredito elevam a qualidade; é preferível um modelo diferente do que gerou a resposta.",
            difficulty: 2,
            tags: ["evals"],
          },
          {
            prompt: "O que o recurso de citations devolve na resposta para cada afirmação ancorada?",
            options: [
              "Apenas um booleano \"verificado\"",
              "Um array citations com cited_text, document_index e a localização (char/página/bloco)",
              "Um novo documento gerado pelo modelo",
              "O hash do documento",
            ],
            correctIndex: 1,
            explanation:
              "Blocos text recebem um array citations; cada citação tem cited_text (trecho exato), document_index e a localização conforme o tipo de documento.",
            difficulty: 2,
            tags: ["citations"],
          },
          {
            prompt: "Qual afirmação sobre citations é correta?",
            options: [
              "Pode ser combinada livremente com structured outputs",
              "O cited_text conta como tokens de saída, encarecendo a resposta",
              "É incompatível com structured outputs na mesma requisição",
              "Funciona apenas com imagens",
            ],
            correctIndex: 2,
            explanation:
              "Citations e structured outputs são incompatíveis na mesma requisição. Além disso, cited_text NÃO conta como tokens de saída — é uma vantagem do recurso.",
            difficulty: 3,
            tags: ["citations", "structured-outputs"],
          },
        ],
        labs: [
          {
            title: "Reduzir alucinação em um Q&A sobre documento",
            promptMd: [
              "Seu produto responde perguntas sobre políticas internas (documentos de texto). Usuários reclamam de respostas inventadas.",
              "",
              "**Tarefa:** descreva como usar citations para ancorar as respostas e como avaliaria a melhoria com um eval. Mostre o bloco document com citations habilitado e proponha o método de grading.",
            ].join("\n"),
            rubric: [
              "Mostra um bloco document com citations: { enabled: true }.",
              "Explica que citations ancoram a resposta em trechos exatos, reduzindo alucinação.",
              "Descreve a resposta com cited_text + document_index + localização.",
              "Propõe um eval com test set e um método de grading adequado.",
              "Menciona a incompatibilidade entre citations e structured outputs.",
            ],
            modelAnswer: [
              "Habilito citations em cada documento de política para que cada afirmação aponte para o",
              "trecho exato da fonte:",
              "",
              "```json",
              "{",
              "  \"type\": \"document\",",
              "  \"source\": { \"type\": \"text\", \"media_type\": \"text/plain\", \"data\": \"<TEXTO_DA_POLITICA>\" },",
              "  \"title\": \"Política de Reembolso\",",
              "  \"citations\": { \"enabled\": true }",
              "}",
              "```",
              "",
              "Na resposta, os blocos text trazem um array citations com cited_text (o trecho citado),",
              "document_index e a localização por caractere (texto puro) — então consigo mostrar a fonte e",
              "rastrear cada afirmação, o que reduz alucinação porque a resposta fica ancorada no documento.",
              "",
              "**Eval:** monto um test set de perguntas com a resposta correta e a passagem-fonte esperada.",
              "Meço duas coisas: (1) acurácia da resposta (exact/string match contra o gabarito) e (2) se a",
              "citação aponta para a passagem certa. Para o julgamento de \"a resposta está fundamentada na",
              "citação?\" uso LLM-as-judge com rubrica clara (correto/incorreto), de preferência com um modelo",
              "diferente. Rodo antes/depois para comprovar a redução de alucinação.",
              "",
              "Observação: se eu precisasse de citations, NÃO poderia usar structured outputs na mesma",
              "requisição (são incompatíveis); nesse caso, parsearia a resposta citada do meu lado.",
            ].join("\n"),
          },
        ],
      },
    ],
  },
];
