import type { CertificationPack } from "./pack.js";

// Curso PREPARATÓRIO (não oficial) para a futura certificação "Claude Certified
// Seller", anunciada pela Anthropic no Claude Partner Network mas ainda não
// lançada. O conteúdo é comercial/conceitual (proposta de valor, modelos, casos
// de uso, implantação, IA responsável) e foi construído a partir de material
// PÚBLICO da Anthropic. NÃO é o exame oficial e pode não refletir o blueprint
// final.
//
// Convenção de tags (kebab-case): "value-prop" | "models" | "use-cases" |
// "deployment" | "pricing" | "security" | "safety".
//
// REGRA DE PRECISÃO: este material NÃO afirma preços em dólar nem cotas/benchmarks
// exatos (podem mudar). Ensina a ESTRUTURA (por token, tiers, prompt caching,
// batch) e remete sempre à página oficial.

export const ccaSellerPrep: CertificationPack = {
  slug: "cca-seller-prep",
  title: "Claude Certified Seller — Preparatório (não oficial)",
  description:
    "Curso PREPARATÓRIO baseado em material público da Anthropic para a futura certificação de Seller (anunciada, ainda não lançada): proposta de valor do Claude, família de modelos, casos de uso, opções de implantação, IA responsável e como posicionar soluções. Não é o exame oficial.",
  version: 1,
  modules: [
    // =====================================================================
    // MÓDULO 1 — CONTEXTO E PROPOSTA DE VALOR
    // =====================================================================
    {
      title: "Contexto e proposta de valor",
      lessons: [
        {
          title: "Aviso e contexto: o que esta certificação é (e não é)",
          readingMd: [
            "# Aviso e contexto: leia antes de tudo",
            "",
            "> **Este curso é PREPARATÓRIO e NÃO OFICIAL.** Ele não é o exame da Anthropic, não confere a credencial de \"Claude Certified Seller\" e pode não refletir o blueprint (programa de provas) final.",
            "",
            "## O que a Anthropic realmente anunciou",
            "",
            "Em 2026, a Anthropic lançou o **Claude Partner Network** — um programa para habilitar parceiros a vender, implementar e dar suporte ao Claude em empresas. Como parte dele, a empresa anunciou uma trilha de **certificações para três papéis**: **sellers** (vendedores), **architects** (arquitetos de solução) e **developers** (desenvolvedores).",
            "",
            "Porém, a situação atual é importante e honesta:",
            "",
            "| Certificação | Status (no momento da escrita) |",
            "| --- | --- |",
            "| **Claude Certified Architect – Foundations** | **Lançada** — exame técnico já disponível |",
            "| Claude Certified **Seller** | **Anunciada**, ainda **não lançada** |",
            "| Demais certificações de architect/developer | Anunciadas, a serem introduzidas |",
            "",
            "A comunicação oficial diz, em essência, que \"ainda neste ano\" serão introduzidas certificações adicionais para sellers, architects e developers. Ou seja: **a de Seller foi prometida, mas o exame oficial ainda não existe** quando este material foi escrito.",
            "",
            "## De onde veio o conteúdo deste curso",
            "",
            "Tudo aqui foi construído a partir de **material público** da Anthropic (anthropic.com, claude.com e a documentação oficial). Cobrimos os conceitos que um bom vendedor de Claude precisa dominar — proposta de valor, família de modelos, casos de uso, implantação, preços e IA responsável — sem inventar números, cotas ou estatísticas.",
            "",
            "## Como usar este preparatório",
            "",
            "- Trate-o como **base conceitual e treino de discurso comercial**, não como \"simulado do exame real\".",
            "- Sempre que houver número volátil (preço, benchmark, limite), **vá à fonte oficial** — nós apontamos o link.",
            "- Quando a certificação oficial for lançada, **reveja o blueprint dela**: a ementa real manda.",
            "",
            "## Princípio de honestidade na venda",
            "",
            "Vender bem o Claude começa por **não exagerar**. A própria cultura da Anthropic gira em torno de segurança e honestidade; um seller que promete o que o produto não faz destrói confiança. Posicione capacidades reais, admita limites e remeta a documentação oficial — isso é, inclusive, um diferencial competitivo.",
            "",
            "> Leitura oficial: https://www.anthropic.com/news/claude-partner-network",
          ].join("\n"),
          flashcards: [
            {
              front: "Qual certificação Anthropic já está LANÇADA e qual ainda NÃO está?",
              back: "Lançada: Claude Certified Architect – Foundations (exame técnico). A de Seller foi anunciada no Claude Partner Network, mas ainda NÃO foi lançada quando este curso foi escrito.",
              tags: ["value-prop"],
            },
            {
              front: "O que é o Claude Partner Network?",
              back: "Programa da Anthropic para habilitar parceiros a vender, implementar e dar suporte ao Claude em empresas. Inclui treinamento, suporte técnico, portal de parceiros e a trilha de certificações (seller/architect/developer).",
              tags: ["value-prop"],
            },
            {
              front: "Este curso é o exame oficial de Seller?",
              back: "Não. É um preparatório NÃO oficial, baseado em material público, que pode não refletir o blueprint final. Não confere a credencial real.",
              tags: ["value-prop"],
            },
            {
              front: "Por que honestidade é argumento de venda na Anthropic?",
              back: "A cultura da Anthropic é centrada em segurança e honestidade. Posicionar capacidades reais e admitir limites preserva confiança do cliente — e isso é um diferencial, não uma fraqueza.",
              tags: ["value-prop"],
            },
          ],
          questions: [
            {
              prompt: "Um cliente pergunta: \"Posso fazer a prova oficial de Claude Certified Seller hoje?\" Qual resposta é HONESTA e correta?",
              options: [
                "Sim, é o mesmo exame que você está estudando aqui.",
                "A certificação de Seller foi anunciada pela Anthropic, mas ainda não foi lançada; por enquanto só a de Architect – Foundations está disponível.",
                "Não existe nenhum plano de certificação para sellers.",
                "Sim, basta concluir este curso preparatório que você recebe a credencial oficial.",
              ],
              correctIndex: 1,
              explanation:
                "A Anthropic anunciou certificações para seller/architect/developer, mas até o momento só a Architect – Foundations foi lançada. Este curso é preparatório, não confere credencial oficial.",
              difficulty: 1,
              tags: ["value-prop"],
            },
            {
              prompt: "Qual é a fonte e o status deste material?",
              options: [
                "É o blueprint oficial confidencial vazado da Anthropic.",
                "É um preparatório baseado em material público da Anthropic, que pode não refletir o blueprint final.",
                "É um conteúdo gerado sem nenhuma fonte.",
                "É documentação interna de produto da Anthropic.",
              ],
              correctIndex: 1,
              explanation:
                "O curso foi construído a partir de material público (anthropic.com / docs) e é honestamente rotulado como preparatório não oficial.",
              difficulty: 1,
              tags: ["value-prop"],
            },
            {
              prompt: "Por que o curso evita citar preços específicos em dólar e benchmarks exatos?",
              options: [
                "Porque esses números não existem.",
                "Porque são informações secretas.",
                "Porque são voláteis (mudam com frequência) e citá-los de cabeça gera risco de informação errada; o correto é remeter à página oficial.",
                "Porque vendedores não precisam falar de preço.",
              ],
              correctIndex: 2,
              explanation:
                "Preços, cotas e benchmarks mudam. Ensina-se a ESTRUTURA e remete-se à fonte oficial para o número atual.",
              difficulty: 2,
              tags: ["value-prop", "pricing"],
            },
          ],
          labs: [
            {
              title: "Role-play: responder com honestidade sobre a certificação",
              promptMd: [
                "## Cenário",
                "",
                "Você é parceiro de vendas da Anthropic. Um gestor de TI diz, empolgado:",
                "",
                "> \"Quero que minha equipe inteira tire a certificação oficial de *Claude Certified Seller* este mês. Esse seu curso já vale como a prova oficial, certo?\"",
                "",
                "## Sua tarefa",
                "",
                "Escreva uma resposta curta (4-6 frases) que seja **honesta**, **não desanime** o cliente e o **direcione corretamente**.",
              ].join("\n"),
              rubric: [
                "Deixa claro que a certificação de Seller foi anunciada, mas ainda NÃO foi lançada.",
                "Esclarece que este curso é preparatório/não oficial e não confere a credencial.",
                "Menciona que a Architect – Foundations já está disponível como alternativa concreta hoje.",
                "Mantém tom positivo e oferece próximo passo (acompanhar o Claude Partner Network / preparar a equipe).",
                "Não promete datas inventadas nem exagera.",
              ],
              modelAnswer: [
                "Adoro o entusiasmo — e quero ser totalmente transparente para não te prometer algo que ainda não existe. A Anthropic **anunciou** uma certificação de Seller dentro do Claude Partner Network, mas ela **ainda não foi lançada**; portanto não há prova oficial de Seller para sua equipe fazer este mês.",
                "Este curso é **preparatório e não oficial**: ele prepara muito bem o discurso comercial, mas não emite a credencial.",
                "O que **já está disponível hoje** é a *Claude Certified Architect – Foundations*, mais técnica — pode ser um ótimo primeiro selo para quem implementa.",
                "Minha sugestão: já entramos no Partner Network para ter **acesso prioritário** quando a de Seller sair, e usamos este preparatório para a equipe chegar pronta. Assim que a Anthropic publicar o blueprint oficial, eu te aviso e ajustamos o plano.",
              ].join("\n"),
            },
          ],
        },
        {
          title: "O que é o Claude e quais problemas de negócio ele resolve",
          readingMd: [
            "# O que é o Claude e quais problemas de negócio ele resolve",
            "",
            "**Claude** é a família de modelos de IA da **Anthropic** — um assistente de IA de fronteira posicionado como um \"parceiro para resolver problemas\". Para um vendedor, a frase-chave não é \"é uma IA\", e sim: **que dor de negócio o Claude tira da mesa do cliente?**",
            "",
            "## Capacidades que viram valor",
            "",
            "- **Texto + visão (multimodal de entrada):** lê e raciocina sobre documentos, PDFs, planilhas e imagens, e responde em texto. Útil para análise documental, due diligence, suporte.",
            "- **Contexto longo:** os modelos atuais trabalham com janelas de contexto grandes (na ordem de centenas de milhares a ~1 milhão de tokens, dependendo do modelo). Isso permite \"jogar\" contratos inteiros, bases de conhecimento ou históricos longos de uma vez.",
            "- **Multilíngue:** atende operações globais, incluindo português.",
            "- **Trabalho agêntico e código:** os modelos mais capazes executam tarefas de raciocínio longas e fluxos agênticos (planejar, usar ferramentas, escrever e revisar código).",
            "- **Integração via API e conectores:** entra nos sistemas que a empresa já usa, em vez de virar mais um portal isolado.",
            "",
            "## Traduzindo capacidade em dor de negócio",
            "",
            "| Dor do cliente | Como o Claude endereça |",
            "| --- | --- |",
            "| \"Meu time perde horas lendo documentos\" | Sumarização e extração com contexto longo |",
            "| \"Meu suporte é caro e lento\" | Atendimento assistido por IA, com tom controlado |",
            "| \"Não consigo escalar análise de dados\" | Análise e geração de relatórios sob demanda |",
            "| \"Desenvolvimento é gargalo\" | Geração/revisão de código e fluxos agênticos |",
            "| \"Tenho medo de IA que vaza dados ou alucina\" | Postura de segurança, privacidade e honestidade da Anthropic |",
            "",
            "## A regra de ouro do discurso",
            "",
            "Venda **resultado de negócio**, não recurso técnico. Em vez de \"temos 1M de tokens de contexto\", diga: \"você consegue analisar o contrato inteiro em uma única passagem, sem cortar em pedaços\". O recurso é o *meio*; o valor é o *fim*.",
            "",
            "> Leitura oficial: https://www.anthropic.com/claude",
          ].join("\n"),
          flashcards: [
            {
              front: "O que é o Claude, em uma frase de vendas?",
              back: "A família de modelos de IA da Anthropic — um assistente de fronteira que atua como parceiro para resolver problemas de negócio (análise, atendimento, código, pesquisa).",
              tags: ["value-prop"],
            },
            {
              front: "Por que 'contexto longo' importa comercialmente?",
              back: "Permite processar documentos, bases e históricos inteiros em uma única passagem (na ordem de centenas de milhares a ~1M de tokens), evitando fragmentar a informação e perder qualidade.",
              tags: ["value-prop", "models"],
            },
            {
              front: "Qual a 'regra de ouro' do discurso comercial de Claude?",
              back: "Vender resultado de negócio, não recurso técnico: traduzir capacidades (contexto, multimodal, agêntico) em dores resolvidas (analisar contrato inteiro, baratear suporte, escalar análise).",
              tags: ["value-prop"],
            },
            {
              front: "Quais entradas o Claude aceita?",
              back: "Texto e imagem (multimodal de entrada), em vários idiomas, com saída em texto. Lê documentos, PDFs, planilhas e imagens.",
              tags: ["value-prop", "use-cases"],
            },
          ],
          questions: [
            {
              prompt: "Um diretor financeiro diz que o time gasta horas lendo contratos longos. Qual capacidade do Claude você posiciona primeiro?",
              options: [
                "Geração de imagens",
                "Janela de contexto longa, para analisar o contrato inteiro de uma vez",
                "Treinamento do modelo nos dados do cliente",
                "Latência mais baixa possível",
              ],
              correctIndex: 1,
              explanation:
                "Contexto longo permite carregar o documento inteiro sem fragmentar, endereçando diretamente a dor de 'horas lendo contratos'.",
              difficulty: 1,
              tags: ["value-prop", "use-cases"],
            },
            {
              prompt: "Qual frase está MAIS alinhada à 'regra de ouro' de vender resultado, não recurso?",
              options: [
                "\"Nosso modelo suporta até ~1 milhão de tokens de contexto.\"",
                "\"Você analisa o contrato inteiro numa única passagem, sem precisar picotar o documento.\"",
                "\"Usamos uma arquitetura transformer de última geração.\"",
                "\"Temos tool use e streaming na API.\"",
              ],
              correctIndex: 1,
              explanation:
                "A segunda opção traduz o recurso (contexto longo) em um resultado concreto para o cliente. As demais são recursos técnicos sem benefício explícito.",
              difficulty: 2,
              tags: ["value-prop"],
            },
            {
              prompt: "Por que dizer 'a IA nunca erra' é um erro de venda do Claude?",
              options: [
                "Porque é verdade, mas soa arrogante",
                "Porque exagera uma capacidade, quebra a confiança e contraria a cultura de honestidade da Anthropic",
                "Porque modelos de IA não cometem erros mesmo",
                "Porque o cliente prefere não ouvir sobre limites",
              ],
              correctIndex: 1,
              explanation:
                "Nenhum modelo é infalível. Prometer perfeição destrói confiança e contraria a postura de honestidade que é, ela própria, um diferencial.",
              difficulty: 2,
              tags: ["value-prop", "safety"],
            },
          ],
          labs: [
            {
              title: "Tradução: de recurso técnico para valor de negócio",
              promptMd: [
                "## Tarefa",
                "",
                "Para CADA recurso técnico abaixo, escreva uma frase de venda focada em **resultado de negócio** (sem jargão), endereçada a um executivo não técnico:",
                "",
                "1. Janela de contexto longa (~1M tokens em alguns modelos)",
                "2. Entrada multimodal (texto + imagem/PDF)",
                "3. Capacidade agêntica / uso de ferramentas",
                "4. Não treina nos dados do cliente por padrão",
              ].join("\n"),
              rubric: [
                "Cada item traduz o recurso em um RESULTADO de negócio claro, não em jargão.",
                "A linguagem é compreensível por um executivo não técnico.",
                "Nenhuma frase exagera ou promete infalibilidade.",
                "As quatro traduções são distintas e coerentes com o recurso.",
              ],
              modelAnswer: [
                "1. **Contexto longo:** \"Seu time joga o contrato, o manual ou a base inteira de uma vez e recebe a análise — sem ficar quebrando o documento em pedaços e perdendo o fio da meada.\"",
                "2. **Multimodal:** \"Pode mandar PDFs, planilhas e até fotos de documentos: o Claude lê e interpreta, então você não precisa redigitar nada antes de analisar.\"",
                "3. **Agêntico / ferramentas:** \"Não é só responder pergunta: ele consegue executar tarefas em etapas — consultar um sistema, montar o rascunho, revisar — liberando seu time do trabalho repetitivo.\"",
                "4. **Sem treino nos seus dados por padrão:** \"O que você manda fica seu: por padrão, seu conteúdo não é usado para treinar o modelo. Isso facilita aprovar o projeto com jurídico e segurança.\"",
              ].join("\n"),
            },
          ],
        },
        {
          title: "Diferenciais: segurança, contexto longo e qualidade",
          readingMd: [
            "# Diferenciais: segurança, contexto longo e qualidade",
            "",
            "Quando o comprador compara fornecedores de IA, ele pergunta: **\"por que Claude e não outro?\"**. Um seller precisa de uma resposta estruturada em três pilares.",
            "",
            "## Pilar 1 — Segurança e confiança como produto",
            "",
            "A Anthropic é uma empresa de pesquisa em segurança de IA. Segurança não é um adendo de marketing: está no núcleo. Para o comprador, isso se traduz em:",
            "",
            "- Postura pública e documentada de gestão de risco (a **Responsible Scaling Policy** — ver Módulo 4).",
            "- Foco em **honestidade** do modelo (reduzir alucinação, admitir incerteza).",
            "- Recursos empresariais de privacidade e governança (ver Módulo 3).",
            "",
            "Em setores regulados (saúde, finanças, governo), \"a IA é segura e a empresa leva risco a sério\" pode ser o **fator decisivo**, não a última linha do slide.",
            "",
            "## Pilar 2 — Contexto longo de verdade",
            "",
            "Janelas de contexto grandes (centenas de milhares a ~1M de tokens em modelos selecionados) permitem casos que concorrentes com janelas curtas não atendem bem: análise de contratos inteiros, bases de conhecimento extensas, históricos longos de conversa. Cuidado honesto: o número exato **depende do modelo**; confirme na documentação.",
            "",
            "## Pilar 3 — Qualidade e raciocínio",
            "",
            "Os modelos Claude se destacam em raciocínio, código, tarefas multilíngues e seguir instruções com nuance. Em vez de citar um número de benchmark (que muda), posicione **qualidade percebida**: respostas que seguem o tom pedido, lidam bem com ambiguidade e produzem trabalho \"de nível especialista\".",
            "",
            "## Quadro-resumo de objeções",
            "",
            "| Objeção do comprador | Resposta de valor |",
            "| --- | --- |",
            "| \"Todo mundo tem IA hoje\" | Segurança no núcleo + contexto longo + qualidade de raciocínio; não é só gerar texto |",
            "| \"Tenho medo de vazar dados\" | Por padrão não treina nos dados do cliente; recursos de governança empresarial |",
            "| \"E se a IA inventar respostas?\" | Foco em honestidade e admissão de incerteza; desenhe o caso de uso com verificação |",
            "| \"É caro?\" | Estrutura de preços flexível por token e por tier de modelo (ver Módulo 3) |",
            "",
            "> Leitura oficial: https://www.anthropic.com/enterprise",
          ].join("\n"),
          flashcards: [
            {
              front: "Quais são os três pilares de diferenciação do Claude na venda?",
              back: "1) Segurança e confiança no núcleo do produto; 2) Contexto longo de verdade; 3) Qualidade de raciocínio e aderência a instruções. (Traduzidos em valor, não em benchmarks voláteis.)",
              tags: ["value-prop"],
            },
            {
              front: "Por que segurança é argumento de venda forte em setores regulados?",
              back: "Em saúde, finanças e governo, a postura documentada de gestão de risco e privacidade pode ser o fator DECISIVO de compra, não um detalhe — reduz risco jurídico e de compliance.",
              tags: ["value-prop", "safety"],
            },
            {
              front: "Como posicionar 'qualidade' sem citar benchmarks que mudam?",
              back: "Fale em qualidade percebida: segue o tom pedido, lida com ambiguidade, produz trabalho de nível especialista. Remeta a documentação para números atuais.",
              tags: ["value-prop"],
            },
            {
              front: "Cuidado honesto ao falar de janela de contexto?",
              back: "O tamanho exato DEPENDE do modelo (alguns ~200k, outros ~1M de tokens). Não generalize um número; confirme na documentação oficial antes de prometer.",
              tags: ["value-prop", "models"],
            },
          ],
          questions: [
            {
              prompt: "Um comprador de um banco diz: \"IA todo fornecedor tem; por que Claude?\". Qual abertura é mais forte?",
              options: [
                "\"Porque é a IA mais barata do mercado.\"",
                "\"Porque a Anthropic é uma empresa de segurança de IA: segurança e gestão de risco estão no núcleo — algo decisivo para um banco regulado — somado a contexto longo e qualidade de raciocínio.\"",
                "\"Porque temos o maior número de parâmetros.\"",
                "\"Porque nosso modelo nunca erra.\"",
              ],
              correctIndex: 1,
              explanation:
                "Para um setor regulado, a postura de segurança/risco é diferencial decisivo. As outras opções são vagas, irrelevantes ou desonestas.",
              difficulty: 2,
              tags: ["value-prop", "safety"],
            },
            {
              prompt: "Qual afirmação sobre janela de contexto é HONESTA?",
              options: [
                "\"Todos os modelos Claude têm 1 milhão de tokens.\"",
                "\"O tamanho da janela depende do modelo; alguns chegam a ~1M de tokens, outros são menores. Confirmo o número exato na documentação.\"",
                "\"Contexto é ilimitado.\"",
                "\"Contexto não importa para o cliente.\"",
              ],
              correctIndex: 1,
              explanation:
                "A janela varia por modelo; o vendedor honesto qualifica a afirmação e remete à fonte oficial.",
              difficulty: 1,
              tags: ["models", "value-prop"],
            },
            {
              prompt: "Cliente: \"E se a IA inventar uma resposta errada?\". Melhor resposta de venda?",
              options: [
                "\"Isso nunca acontece com o Claude.\"",
                "\"Nenhuma IA é infalível; a Anthropic foca em honestidade e admissão de incerteza, e desenhamos o caso de uso com verificação humana ou checagem nos pontos críticos.\"",
                "\"Você deveria confiar cegamente no modelo.\"",
                "\"Esse risco não existe na nossa plataforma.\"",
              ],
              correctIndex: 1,
              explanation:
                "A resposta honesta reconhece o risco, cita o foco em honestidade do modelo e propõe mitigação de processo — em vez de negar o risco.",
              difficulty: 2,
              tags: ["value-prop", "safety"],
            },
          ],
          labs: [
            {
              title: "Discovery: as 4 perguntas que abrem a venda",
              promptMd: [
                "## Tarefa",
                "",
                "Antes de empurrar recursos, um bom seller faz **discovery**. Escreva 4 perguntas abertas para uma reunião inicial com um diretor de operações que \"quer usar IA\", de modo a descobrir:",
                "",
                "- a dor de negócio real,",
                "- o volume/escala,",
                "- restrições de segurança/compliance,",
                "- como ele mede sucesso.",
                "",
                "Para cada pergunta, explique em uma linha o que você está tentando descobrir.",
              ].join("\n"),
              rubric: [
                "As 4 perguntas são abertas (não respondíveis com sim/não) e focadas em negócio.",
                "Cobrem dor, escala, segurança/compliance e métrica de sucesso.",
                "Cada pergunta vem com a intenção (o que se quer descobrir).",
                "Tom consultivo, sem empurrar produto antes de entender o problema.",
              ],
              modelAnswer: [
                "1. \"Hoje, qual processo consome mais tempo ou gera mais retrabalho na sua operação?\" — descobre a **dor real** e onde o ROI seria visível.",
                "2. \"Qual o volume disso por dia ou por mês, e isso tende a crescer?\" — dimensiona **escala** (e ajuda a estimar custo/modelo depois).",
                "3. \"Que dados estariam envolvidos e quais regras de segurança ou compliance precisam ser respeitadas?\" — mapeia **restrições** (privacidade, setor regulado, residência de dados).",
                "4. \"Se isso desse muito certo em 3 meses, que número você gostaria de ver mudar?\" — define a **métrica de sucesso** acordada desde o início.",
              ].join("\n"),
            },
          ],
        },
      ],
    },
    // =====================================================================
    // MÓDULO 2 — FAMÍLIA DE MODELOS E CASOS DE USO
    // =====================================================================
    {
      title: "Família de modelos e casos de uso",
      lessons: [
        {
          title: "Opus, Sonnet e Haiku: quando posicionar cada um",
          readingMd: [
            "# Opus, Sonnet e Haiku: quando posicionar cada um",
            "",
            "A família Claude é organizada em **tiers** com um trade-off clássico entre **inteligência, velocidade e custo**. Os nomes dos tiers (Opus, Sonnet, Haiku) se mantêm entre gerações; o número da versão muda. Um seller não decora versões — entende **o eixo** e ajuda o cliente a escolher.",
            "",
            "## O trade-off em uma frase",
            "",
            "> Quanto mais **inteligência de fronteira** você precisa, mais para o lado **Opus**. Quanto mais **velocidade e baixo custo em escala**, mais para o lado **Haiku**. O **Sonnet** é o equilíbrio.",
            "",
            "## Os três tiers",
            "",
            "| Tier | Posicione quando o cliente precisa de... | Exemplos |",
            "| --- | --- | --- |",
            "| **Opus** | Máxima capacidade: raciocínio complexo, trabalho agêntico de longo horizonte, código difícil, alta autonomia | Copiloto de engenharia, análise jurídica profunda, agentes que decidem |",
            "| **Sonnet** | Melhor combinação de velocidade e inteligência para o dia a dia em produção | Atendimento de qualidade, geração de conteúdo, automações gerais |",
            "| **Haiku** | Velocidade máxima e baixo custo em alto volume, com inteligência próxima da fronteira | Classificação/roteamento em massa, respostas rápidas, pré-processamento |",
            "",
            "## Como conduzir a escolha com o cliente",
            "",
            "1. **Comece pela tarefa, não pelo modelo.** Tarefa difícil e de alto valor → Opus. Fluxo de produção equilibrado → Sonnet. Altíssimo volume e simples → Haiku.",
            "2. **Pense em arquitetura mista.** É comum (e econômico) usar **Haiku para triagem** e **Opus/Sonnet** só nos casos que exigem mais raciocínio. Isso é um ótimo argumento de **custo**.",
            "3. **Não prometa um modelo específico para sempre.** Versões evoluem; posicione o *tier* e revise quando sair geração nova.",
            "",
            "## Erros comuns de posicionamento",
            "",
            "- Vender Opus para tudo (custo desnecessário em tarefas simples).",
            "- Vender Haiku para uma tarefa que exige raciocínio profundo (qualidade insuficiente).",
            "- Citar números de benchmark de cabeça — eles mudam a cada geração.",
            "",
            "> Leitura oficial: https://docs.anthropic.com/en/docs/about-claude/models/overview",
          ].join("\n"),
          flashcards: [
            {
              front: "Qual é o trade-off entre os tiers Opus, Sonnet e Haiku?",
              back: "Inteligência x velocidade x custo. Opus = máxima capacidade (mais caro/mais lento). Haiku = mais rápido e barato em escala. Sonnet = equilíbrio entre os dois.",
              tags: ["models"],
            },
            {
              front: "Quando posicionar Opus?",
              back: "Tarefas de máxima dificuldade e alto valor: raciocínio complexo, agentes de longo horizonte, código difícil, alta autonomia.",
              tags: ["models"],
            },
            {
              front: "Quando posicionar Haiku?",
              back: "Alto volume com necessidade de velocidade e baixo custo, e inteligência próxima da fronteira: classificação/roteamento em massa, respostas rápidas, triagem.",
              tags: ["models"],
            },
            {
              front: "O que é uma 'arquitetura mista' de modelos e por que vender isso?",
              back: "Usar Haiku para triagem barata e escalar para Sonnet/Opus só quando o caso exige mais raciocínio. É um forte argumento de custo: paga-se a inteligência cara só onde ela importa.",
              tags: ["models", "pricing"],
            },
          ],
          questions: [
            {
              prompt: "Um cliente precisa classificar 10 milhões de tickets/mês em categorias simples, o mais barato e rápido possível. Qual tier posicionar primeiro?",
              options: ["Opus", "Sonnet", "Haiku", "Sempre o mais novo Opus disponível"],
              correctIndex: 2,
              explanation:
                "Alto volume + tarefa simples + foco em custo/velocidade = Haiku. Usar Opus aqui encareceria sem ganho proporcional.",
              difficulty: 1,
              tags: ["models", "use-cases"],
            },
            {
              prompt: "Um escritório quer um agente que faça análise jurídica profunda e raciocínio de várias etapas sobre processos complexos. Qual tier?",
              options: ["Haiku", "Sonnet ou Opus, com Opus para os casos mais difíceis", "Só Haiku para baratear", "Qualquer um, é indiferente"],
              correctIndex: 1,
              explanation:
                "Raciocínio profundo e de várias etapas pede o topo de capacidade (Opus), eventualmente Sonnet para casos menos exigentes. Haiku não é o tier indicado para a parte mais complexa.",
              difficulty: 2,
              tags: ["models", "use-cases"],
            },
            {
              prompt: "Qual é a melhor prática ao recomendar um modelo específico (ex.: 'Opus 4.x') ao cliente?",
              options: [
                "Garantir que ele usará exatamente aquela versão para sempre",
                "Posicionar o TIER (Opus/Sonnet/Haiku) e revisar a escolha quando sair uma nova geração",
                "Nunca mencionar tiers",
                "Escolher sempre o mais barato independentemente da tarefa",
              ],
              correctIndex: 1,
              explanation:
                "Versões evoluem; o seller posiciona o tier conforme a necessidade e revisa quando há geração nova. Travar uma versão 'para sempre' é frágil.",
              difficulty: 2,
              tags: ["models"],
            },
          ],
          labs: [
            {
              title: "Recomendação de tier por cenário",
              promptMd: [
                "## Tarefa",
                "",
                "Para cada cenário, recomende um **tier** (Opus / Sonnet / Haiku) — ou uma combinação — e justifique em uma frase, citando o trade-off inteligência/velocidade/custo:",
                "",
                "1. Chat de suporte ao cliente de qualidade, volume médio, em produção.",
                "2. Roteamento de 50 milhões de mensagens/mês para a fila certa.",
                "3. Agente autônomo que escreve e refatora código complexo.",
                "4. Pipeline que faz triagem barata e só escala casos difíceis para análise profunda.",
              ].join("\n"),
              rubric: [
                "Cada cenário recebe um tier coerente com o trade-off inteligência/velocidade/custo.",
                "Cenário 1 → Sonnet; 2 → Haiku; 3 → Opus; 4 → arquitetura mista (Haiku + Opus/Sonnet).",
                "Justificativas curtas e corretas, sem citar benchmarks numéricos.",
                "Não recomenda Opus indiscriminadamente para tudo.",
              ],
              modelAnswer: [
                "1. **Sonnet** — melhor equilíbrio entre qualidade e velocidade para um fluxo de produção do dia a dia.",
                "2. **Haiku** — volume altíssimo e tarefa de roteamento simples pedem o tier mais rápido e barato.",
                "3. **Opus** — código complexo e autonomia de longo horizonte exigem o topo de capacidade de raciocínio.",
                "4. **Arquitetura mista**: **Haiku** faz a triagem barata e só escala para **Opus** (ou Sonnet) os casos que realmente exigem raciocínio profundo — paga-se a inteligência cara apenas onde ela importa.",
              ].join("\n"),
            },
          ],
        },
        {
          title: "Casos de uso por setor: atendimento, jurídico, software e análise",
          readingMd: [
            "# Casos de uso por setor: atendimento, jurídico, software e análise",
            "",
            "Vendedor que fala a língua do setor do cliente fecha mais. Abaixo, quatro frentes onde o Claude tem encaixe natural, com a dor, o desenho da solução e o cuidado de venda.",
            "",
            "## 1. Atendimento ao cliente",
            "",
            "- **Dor:** suporte caro, lento, inconsistente; agentes humanos sobrecarregados com perguntas repetidas.",
            "- **Solução:** assistente que responde com o **tom e as políticas da marca** (via system prompt), consulta a base de conhecimento (contexto longo / recuperação) e escala para humano quando necessário.",
            "- **Posicionamento de modelo:** **Sonnet** para a maioria; **Haiku** para triagem/roteamento; **Opus** para casos sensíveis.",
            "- **Cuidado:** desenhe *handoff* para humano e verificação em respostas sensíveis.",
            "",
            "## 2. Jurídico",
            "",
            "- **Dor:** revisar contratos longos, comparar cláusulas, resumir jurisprudência — caro e demorado.",
            "- **Solução:** **contexto longo** para ler o documento inteiro; extração de cláusulas, resumo, comparação, perguntas e respostas sobre o texto.",
            "- **Posicionamento:** **Opus/Sonnet** pela exigência de raciocínio e nuance.",
            "- **Cuidado:** jurídico é alto risco — posicione como **assistência ao advogado**, com revisão humana, nunca como substituto que dá parecer final sozinho.",
            "",
            "## 3. Software / engenharia",
            "",
            "- **Dor:** desenvolvimento é gargalo; revisão de código consome seniores; modernização de sistemas legados é lenta.",
            "- **Solução:** geração e revisão de código, explicação de bases legadas, fluxos agênticos de desenvolvimento.",
            "- **Posicionamento:** **Opus** para tarefas agênticas/complexas; **Sonnet** para o dia a dia.",
            "- **Cuidado:** mantenha humano no controle de merge e testes.",
            "",
            "## 4. Análise de dados e conhecimento",
            "",
            "- **Dor:** insights presos em documentos e planilhas; análise não escala.",
            "- **Solução:** sumarização, extração estruturada, geração de relatórios, perguntas em linguagem natural sobre os dados (multimodal: lê planilhas e PDFs).",
            "- **Posicionamento:** **Sonnet** para a maioria; **Opus** para análises mais profundas.",
            "- **Cuidado:** para números críticos, combine com checagem/verificação.",
            "",
            "## Padrão comum de venda",
            "",
            "Em todos os setores: **(1)** identifique a dor, **(2)** mostre o fluxo (não só o modelo), **(3)** escolha o tier por tarefa, **(4)** trate segurança/risco do setor, **(5)** defina como medir sucesso.",
            "",
            "> Leitura oficial: https://www.anthropic.com/enterprise",
          ].join("\n"),
          flashcards: [
            {
              front: "Como posicionar Claude em ATENDIMENTO ao cliente?",
              back: "Assistente com tom e políticas da marca (system prompt) + base de conhecimento (contexto/recuperação) + handoff para humano. Sonnet na maioria, Haiku para triagem, Opus em casos sensíveis.",
              tags: ["use-cases"],
            },
            {
              front: "Qual o cuidado essencial ao vender Claude para o JURÍDICO?",
              back: "Posicionar como ASSISTÊNCIA ao advogado, com revisão humana — nunca como substituto que dá parecer final sozinho. É um domínio de alto risco.",
              tags: ["use-cases", "safety"],
            },
            {
              front: "Por que contexto longo é especialmente forte no jurídico?",
              back: "Permite ler contratos e documentos inteiros de uma vez para extrair cláusulas, resumir, comparar e responder perguntas sobre o texto sem fragmentar.",
              tags: ["use-cases", "models"],
            },
            {
              front: "Qual o padrão comum de venda válido para todos os setores?",
              back: "1) Identificar a dor; 2) mostrar o fluxo (não só o modelo); 3) escolher o tier por tarefa; 4) tratar segurança/risco do setor; 5) definir métrica de sucesso.",
              tags: ["use-cases", "value-prop"],
            },
          ],
          questions: [
            {
              prompt: "Ao vender Claude para um escritório de advocacia, qual posicionamento é responsável?",
              options: [
                "\"Substitui o advogado e emite o parecer final automaticamente.\"",
                "\"Assiste o advogado — lê o contrato inteiro, extrai cláusulas e resume — sempre com revisão humana antes de qualquer decisão.\"",
                "\"Garante 100% de exatidão jurídica.\"",
                "\"Dispensa qualquer revisão humana.\"",
              ],
              correctIndex: 1,
              explanation:
                "Jurídico é alto risco; o posicionamento correto é assistência com revisão humana, aproveitando contexto longo. As outras opções são exageradas e perigosas.",
              difficulty: 2,
              tags: ["use-cases", "safety"],
            },
            {
              prompt: "Em um caso de atendimento ao cliente de alto volume, qual desenho de modelos é mais econômico e eficaz?",
              options: [
                "Tudo em Opus",
                "Haiku para triagem/roteamento e Sonnet para as respostas, escalando a Opus só em casos sensíveis",
                "Tudo em Haiku, inclusive casos sensíveis",
                "Sortear o modelo a cada mensagem",
              ],
              correctIndex: 1,
              explanation:
                "Arquitetura mista: Haiku barateia a triagem, Sonnet entrega qualidade no dia a dia e Opus cobre o sensível. Tudo em Opus desperdiça; tudo em Haiku falha no sensível.",
              difficulty: 2,
              tags: ["use-cases", "models", "pricing"],
            },
            {
              prompt: "Para análise de dados com planilhas e PDFs, qual capacidade do Claude é central?",
              options: [
                "Geração de áudio",
                "Entrada multimodal (ler planilhas/PDFs) + sumarização e extração estruturada",
                "Treinar o modelo nos dados do cliente",
                "Apenas latência baixa",
              ],
              correctIndex: 1,
              explanation:
                "O Claude lê planilhas e PDFs (multimodal de entrada) e faz sumarização/extração, endereçando a dor de insights presos em documentos.",
              difficulty: 1,
              tags: ["use-cases"],
            },
          ],
          labs: [
            {
              title: "Mini pitch setorial",
              promptMd: [
                "## Tarefa",
                "",
                "Escolha **um** setor (atendimento, jurídico, software ou análise de dados) e escreva um **mini pitch de 5 frases** seguindo o padrão comum de venda:",
                "",
                "1. nomeie a dor,",
                "2. descreva o fluxo da solução (não só 'use IA'),",
                "3. recomende o(s) tier(s) por tarefa,",
                "4. trate um risco/segurança do setor,",
                "5. proponha como medir sucesso.",
              ].join("\n"),
              rubric: [
                "Cobre os 5 elementos do padrão (dor, fluxo, tier, risco, métrica).",
                "O fluxo descreve uma solução concreta, não 'apenas use IA'.",
                "A escolha de tier é coerente com as tarefas descritas.",
                "Trata um risco real do setor escolhido (ex.: revisão humana no jurídico).",
                "Propõe uma métrica de sucesso mensurável.",
              ],
              modelAnswer: [
                "**Setor: atendimento ao cliente.**",
                "1. \"Hoje seu suporte gasta caro respondendo as mesmas dúvidas e o tempo de espera frustra o cliente.\"",
                "2. \"Montamos um assistente que responde no **tom e nas políticas da sua marca**, consulta sua base de conhecimento e **passa para um humano** quando o caso é sensível.\"",
                "3. \"Usamos **Haiku** para rotear a mensagem à fila certa, **Sonnet** para a maioria das respostas e **Opus** nos casos delicados.\"",
                "4. \"Em temas sensíveis, há **handoff humano e verificação** — a IA não fecha sozinha o que exige julgamento.\"",
                "5. \"Medimos sucesso por **tempo de resposta, % de resolução no primeiro contato e satisfação (CSAT)** antes e depois.\"",
              ].join("\n"),
            },
          ],
        },
      ],
    },
    // =====================================================================
    // MÓDULO 3 — IMPLANTAÇÃO E COMERCIAL
    // =====================================================================
    {
      title: "Implantação e comercial",
      lessons: [
        {
          title: "Onde rodar o Claude: API direta, Amazon Bedrock e Google Vertex AI",
          readingMd: [
            "# Onde rodar o Claude: API direta, Amazon Bedrock e Google Vertex AI",
            "",
            "Uma objeção comum de compradores empresariais é: **\"e a minha nuvem? e meus contratos existentes?\"**. O Claude responde bem porque está disponível em **múltiplos canais de implantação**, e o seller deve saber qual recomendar.",
            "",
            "## Os principais canais",
            "",
            "| Canal | Quando recomendar |",
            "| --- | --- |",
            "| **Claude API (Anthropic)** | Acesso direto, mais rápido para começar, primeiro a receber recursos novos. Ideal para quem quer agilidade e a relação direta com a Anthropic. |",
            "| **Amazon Bedrock** | Cliente já é **AWS**: usa billing, IAM, rede e governança da AWS; mantém dados no ecossistema que já aprovou. |",
            "| **Google Vertex AI** | Cliente já é **Google Cloud**: integra com a stack GCP, billing e governança do Google. |",
            "",
            "Existem outros canais empresariais (por exemplo, plataformas de nuvem adicionais). O ponto comercial é: **o Claude se encaixa na nuvem que o cliente já tem**, em vez de forçar uma migração.",
            "",
            "## Por que isso é um argumento de venda forte",
            "",
            "- **Reduz atrito de compras/segurança:** comprar via marketplace da nuvem que já está aprovada acelera o jurídico e o procurement.",
            "- **Aproveita compromissos de gasto:** muitos clientes têm verba comprometida com AWS/GCP; usar o Claude por lá ajuda a justificar internamente.",
            "- **Mantém governança existente:** identidade, rede e auditoria seguem as ferramentas que o cliente já domina.",
            "",
            "## Cuidados honestos",
            "",
            "- A **disponibilidade de um modelo específico pode variar por canal e por região** — confirme na documentação antes de prometer.",
            "- IDs de modelo e endpoints diferem entre Claude API, Bedrock e Vertex; isso é detalhe de implementação, mas não prometa paridade total sem checar.",
            "",
            "## Como conduzir a conversa",
            "",
            "Pergunte cedo: *\"qual nuvem vocês já usam e têm aprovada?\"*. A resposta normalmente já indica o canal de menor atrito.",
            "",
            "> Leitura oficial: https://docs.anthropic.com/en/docs/about-claude/models/overview",
          ].join("\n"),
          flashcards: [
            {
              front: "Quais são os três principais canais de implantação do Claude?",
              back: "Claude API (Anthropic, acesso direto), Amazon Bedrock (para clientes AWS) e Google Vertex AI (para clientes Google Cloud). Há ainda outros canais empresariais.",
              tags: ["deployment"],
            },
            {
              front: "Por que oferecer Claude via Bedrock/Vertex é forte na venda empresarial?",
              back: "Encaixa na nuvem que o cliente já aprovou: usa billing, identidade, rede e governança existentes; reduz atrito de procurement/jurídico e aproveita verba já comprometida com a nuvem.",
              tags: ["deployment", "value-prop"],
            },
            {
              front: "Quando recomendar a Claude API direta da Anthropic?",
              back: "Quando o cliente quer começar rápido, ter relação direta com a Anthropic e acesso mais cedo a recursos novos.",
              tags: ["deployment"],
            },
            {
              front: "Que cuidado honesto ter ao falar de canais de implantação?",
              back: "A disponibilidade de um modelo específico pode variar por canal e por região; IDs/endpoints diferem. Confirme na documentação antes de prometer paridade.",
              tags: ["deployment"],
            },
          ],
          questions: [
            {
              prompt: "Um cliente é fortemente padronizado em AWS, com governança e billing centralizados lá. Qual canal reduz mais o atrito de compra?",
              options: ["Sempre a API direta", "Amazon Bedrock", "Google Vertex AI", "Nenhum, ele precisa migrar de nuvem"],
              correctIndex: 1,
              explanation:
                "Para um cliente AWS, o Bedrock aproveita billing, IAM, rede e governança já aprovados, acelerando procurement e segurança.",
              difficulty: 1,
              tags: ["deployment"],
            },
            {
              prompt: "Qual pergunta de discovery ajuda a escolher o canal de implantação?",
              options: [
                "\"Qual o seu orçamento de marketing?\"",
                "\"Qual nuvem vocês já usam e têm aprovada internamente?\"",
                "\"Quantos funcionários a empresa tem?\"",
                "\"Você prefere Opus ou Haiku?\"",
              ],
              correctIndex: 1,
              explanation:
                "Saber a nuvem já aprovada indica o canal de menor atrito (Bedrock para AWS, Vertex para GCP, ou API direta).",
              difficulty: 1,
              tags: ["deployment"],
            },
            {
              prompt: "O cliente pergunta se um modelo específico está disponível em todos os canais e regiões. Resposta honesta?",
              options: [
                "\"Sim, tudo está disponível em todo lugar, sempre.\"",
                "\"A disponibilidade pode variar por canal e por região; deixa eu confirmar na documentação oficial o seu caso antes de cravar.\"",
                "\"Não importa, escolha qualquer um.\"",
                "\"Só funciona na API direta.\"",
              ],
              correctIndex: 1,
              explanation:
                "Disponibilidade varia por canal/região; o seller confirma na documentação em vez de prometer paridade total de cabeça.",
              difficulty: 2,
              tags: ["deployment"],
            },
          ],
          labs: [
            {
              title: "Recomendar o canal certo",
              promptMd: [
                "## Tarefa",
                "",
                "Para cada cliente, recomende um canal (Claude API / Amazon Bedrock / Google Vertex AI) e justifique em uma frase:",
                "",
                "1. Startup que quer um protótipo no ar esta semana, sem amarras de nuvem.",
                "2. Banco padronizado em AWS, com forte governança e verba comprometida na AWS.",
                "3. Varejista cujo data lake e ferramentas de ML já vivem no Google Cloud.",
              ].join("\n"),
              rubric: [
                "Cliente 1 → Claude API direta; 2 → Amazon Bedrock; 3 → Google Vertex AI.",
                "Cada justificativa cita o motivo comercial (agilidade, governança/verba AWS, stack GCP).",
                "Não força migração de nuvem desnecessária.",
                "Menciona, ao menos uma vez, confirmar disponibilidade na documentação.",
              ],
              modelAnswer: [
                "1. **Claude API (Anthropic)** — para um protótipo rápido sem amarras de nuvem, o acesso direto é o caminho de menor fricção e recebe recursos novos primeiro.",
                "2. **Amazon Bedrock** — o banco já tem AWS aprovada, com governança e verba comprometida lá; usar o Claude via Bedrock acelera procurement e mantém a auditoria existente.",
                "3. **Google Vertex AI** — como dados e ML do varejista já vivem no GCP, o Vertex integra naturalmente à stack e ao billing do Google.",
                "Em todos os casos, confirmo na **documentação oficial** se o modelo/versão desejado está disponível no canal e na região do cliente antes de fechar.",
              ].join("\n"),
            },
          ],
        },
        {
          title: "Estrutura de preços e como estimar custo",
          readingMd: [
            "# Estrutura de preços e como estimar custo",
            "",
            "> **Importante:** este curso **não** cita preços em dólar — eles mudam. Aqui você aprende a **estrutura** para conversar sobre custo com confiança e sempre confirmar o número atual na **página oficial de preços**.",
            "",
            "## Os blocos da estrutura de preços (API)",
            "",
            "1. **Cobrança por token.** Você paga por **tokens de entrada** (o que envia: prompt + contexto) e **tokens de saída** (o que o modelo gera). Em geral, **saída custa mais por token** que entrada. Token ≈ pedaço de palavra.",
            "2. **Preço varia por tier de modelo.** Opus (mais capaz) custa mais por token que Sonnet, que custa mais que Haiku. Por isso escolher o tier certo é também uma decisão de **custo**.",
            "3. **Prompt caching (cache de prompt).** Se você reaproveita um trecho grande e estável de contexto (ex.: um manual, instruções fixas) em muitas chamadas, o **caching** reduz o custo de reprocessar esse trecho repetidamente.",
            "4. **Batch (processamento em lote) com desconto.** Para trabalho **assíncrono** que não precisa de resposta imediata (ex.: processar uma noite inteira de documentos), a API de lote oferece **desconto** em troca de não ser em tempo real.",
            "5. **Planos para times/empresas.** Além da API, há planos por assento (Team/Enterprise) onde o uso pode ser cobrado a taxas de API; o mix depende do caso.",
            "",
            "## Como estimar custo de forma honesta",
            "",
            "Roteiro simples para uma estimativa de ordem de grandeza:",
            "",
            "1. **Volume:** quantas chamadas por dia/mês?",
            "2. **Tamanho médio:** quantos tokens de entrada e de saída por chamada (aproxime; documentos longos = muitos tokens de entrada)?",
            "3. **Tier:** qual modelo cada etapa usa (lembre da arquitetura mista — Haiku barateia)?",
            "4. **Otimizações:** dá para usar **caching** (contexto repetido) ou **batch** (assíncrono)?",
            "5. **Multiplique e busque o preço atual** na página oficial — nunca de memória.",
            "",
            "## Alavancas de custo que viram argumento de venda",
            "",
            "| Alavanca | Efeito |",
            "| --- | --- |",
            "| Escolher o tier certo por tarefa | Não pagar Opus por trabalho que Haiku/Sonnet resolvem |",
            "| Arquitetura mista (triagem barata) | Reserva o modelo caro só para o que exige raciocínio |",
            "| Prompt caching | Reduz custo de contexto fixo reutilizado |",
            "| Batch | Desconto em cargas assíncronas |",
            "| Prompts enxutos | Menos tokens de entrada = menos custo |",
            "",
            "> Leitura oficial: https://www.anthropic.com/pricing",
          ].join("\n"),
          flashcards: [
            {
              front: "Como é a cobrança básica da API do Claude?",
              back: "Por token: tokens de entrada (prompt + contexto) e tokens de saída (gerados). A saída geralmente custa mais por token que a entrada. NÃO decore valores — confirme na página oficial.",
              tags: ["pricing"],
            },
            {
              front: "O que é prompt caching e quando ele reduz custo?",
              back: "Reaproveitar um trecho grande e estável de contexto (manual, instruções fixas) entre muitas chamadas, evitando reprocessá-lo do zero toda vez — reduzindo o custo desse contexto repetido.",
              tags: ["pricing"],
            },
            {
              front: "Quando o processamento em lote (batch) compensa?",
              back: "Em trabalho assíncrono que não exige resposta imediata (ex.: processar documentos à noite). Oferece desconto em troca de não ser em tempo real.",
              tags: ["pricing"],
            },
            {
              front: "Por que a escolha de tier é também uma decisão de custo?",
              back: "Porque o preço por token varia por tier: Opus > Sonnet > Haiku. Usar o tier certo (e arquitetura mista) evita pagar por inteligência que a tarefa não exige.",
              tags: ["pricing", "models"],
            },
          ],
          questions: [
            {
              prompt: "Qual afirmação sobre a estrutura de preços está correta (sem citar valores)?",
              options: [
                "Cobra-se um valor fixo mensal independente de uso.",
                "Cobra-se por token de entrada e de saída, e o preço por token varia conforme o tier do modelo.",
                "Só se cobra pelos tokens de saída.",
                "Opus é sempre o mais barato por token.",
              ],
              correctIndex: 1,
              explanation:
                "A cobrança é por token (entrada e saída), com preço variando por tier (Opus > Sonnet > Haiku). Saída costuma custar mais que entrada.",
              difficulty: 1,
              tags: ["pricing"],
            },
            {
              prompt: "Um cliente processa 2 milhões de documentos por noite, sem necessidade de resposta imediata. Qual otimização você sugere?",
              options: [
                "Usar sempre Opus em tempo real",
                "Usar a API de lote (batch) para obter desconto em carga assíncrona",
                "Aumentar o max_tokens ao máximo",
                "Desativar o caching",
              ],
              correctIndex: 1,
              explanation:
                "Carga assíncrona e tolerante a latência é o caso clássico de batch, que oferece desconto.",
              difficulty: 2,
              tags: ["pricing"],
            },
            {
              prompt: "O cliente pergunta o preço exato por 1 milhão de tokens do Opus. Qual é a conduta correta do seller?",
              options: [
                "Citar um número de memória para parecer confiante",
                "Explicar a estrutura (por token, varia por tier) e buscar o valor ATUAL na página oficial de preços",
                "Dizer que é de graça",
                "Recusar-se a falar de preço",
              ],
              correctIndex: 1,
              explanation:
                "Preços mudam; o seller explica a estrutura e confirma o número atual na fonte oficial, sem citar de memória.",
              difficulty: 1,
              tags: ["pricing", "value-prop"],
            },
          ],
          labs: [
            {
              title: "Roteiro de estimativa de custo (sem citar dólares)",
              promptMd: [
                "## Cenário",
                "",
                "Um cliente quer um chatbot interno que responde perguntas sobre um **manual fixo de 300 páginas**, com **muitas chamadas por dia**, em tempo real.",
                "",
                "## Tarefa",
                "",
                "Escreva o **roteiro de estimativa** que você seguiria com o cliente (passos e perguntas), citando quais **alavancas de custo** se aplicam — **sem inventar valores em dólar**. Termine indicando onde buscar o preço atual.",
              ].join("\n"),
              rubric: [
                "Lista os passos: volume, tamanho médio de entrada/saída, tier por etapa, otimizações.",
                "Identifica que o manual fixo é candidato a PROMPT CACHING (contexto estável reutilizado).",
                "Sugere tier adequado (ex.: Sonnet para o dia a dia; Haiku para triagem se houver).",
                "NÃO inventa valores em dólar.",
                "Encerra remetendo à página oficial de preços para o número atual.",
              ],
              modelAnswer: [
                "1. **Volume:** \"Quantas perguntas por dia esperamos, e em horário de pico?\" — define a escala.",
                "2. **Tamanho médio:** a resposta é curta (poucos tokens de saída), mas o **manual de 300 páginas** é muito contexto de entrada — então a entrada domina o custo.",
                "3. **Alavanca-chave — prompt caching:** como o manual é **fixo e reutilizado** em quase toda chamada, o **caching** evita reprocessá-lo do zero a cada pergunta, reduzindo bastante o custo de entrada.",
                "4. **Tier:** **Sonnet** dá bom equilíbrio para respostas de qualidade; se houver triagem/roteamento, **Haiku** pode filtrar antes.",
                "5. **Tempo real:** como precisa ser imediato, **batch não se aplica** aqui (ele é para assíncrono).",
                "6. **Fechamento honesto:** \"Com volume e tamanhos estimados, multiplicamos pela tarifa por token do tier escolhido — e eu confirmo o **valor atual na página oficial de preços** antes de te passar qualquer número.\"",
                "",
                "> Buscar preço atual em: https://www.anthropic.com/pricing",
              ].join("\n"),
            },
          ],
        },
        {
          title: "Segurança, privacidade e governança empresarial",
          readingMd: [
            "# Segurança, privacidade e governança empresarial",
            "",
            "Em vendas empresariais, o negócio costuma ser ganho ou perdido na mesa de **segurança e jurídico**. Um seller que conhece a postura empresarial do Claude **destrava** essas aprovações em vez de travar.",
            "",
            "## O que importa para o comprador empresarial",
            "",
            "- **Não treinar nos dados do cliente por padrão.** O conteúdo enviado **não é usado para treinar** os modelos por padrão — argumento central para jurídico e segurança.",
            "- **Controles de retenção de dados.** Políticas configuráveis de quanto tempo os dados ficam retidos.",
            "- **Identidade e acesso:** **SSO** (login único) com verificação de domínio, **SCIM** para provisionamento, **acesso baseado em papéis** com permissões granulares.",
            "- **Auditoria e governança:** **logs de auditoria**, API de compliance, controles de gasto por usuário/organização.",
            "- **Compliance:** ofertas com **conformidade tipo SOC 2** e **opção pronta para HIPAA** (saúde), além de controles de rede (ex.: allowlist de IP).",
            "- **Implantação em nuvem aprovada:** via **Bedrock/Vertex**, herda a governança da nuvem do cliente (ver lição anterior).",
            "",
            "> Cuidado honesto: certificações e ofertas de compliance **evoluem** e podem depender do **plano e do canal**. Não prometa um selo específico de cabeça; confirme na documentação/contrato o que se aplica ao caso.",
            "",
            "## Como transformar isso em conversa de venda",
            "",
            "| Pergunta do comprador | Resposta de valor |",
            "| --- | --- |",
            "| \"Vocês treinam nos meus dados?\" | \"Por padrão, não — seu conteúdo não é usado para treinar os modelos.\" |",
            "| \"Como controlo quem acessa?\" | \"SSO, SCIM e acesso por papéis com permissões granulares.\" |",
            "| \"Consigo auditar o uso?\" | \"Sim, há logs de auditoria e API de compliance.\" |",
            "| \"Atende saúde/dados sensíveis?\" | \"Há oferta pronta para HIPAA e conformidade tipo SOC 2 — confirmo no contrato o que se aplica ao seu caso.\" |",
            "| \"Preciso ficar na minha nuvem.\" | \"Pode rodar via Bedrock (AWS) ou Vertex (GCP), herdando sua governança.\" |",
            "",
            "## O princípio",
            "",
            "Segurança não é o slide do fim — é, muitas vezes, **a razão da compra**. Leve segurança e privacidade para o **início** da conversa em setores regulados.",
            "",
            "> Leitura oficial: https://www.anthropic.com/enterprise",
          ].join("\n"),
          flashcards: [
            {
              front: "O Claude treina nos dados do cliente?",
              back: "Por padrão, NÃO — o conteúdo enviado não é usado para treinar os modelos. É um argumento central para destravar segurança e jurídico.",
              tags: ["security"],
            },
            {
              front: "Quais recursos de identidade/acesso empresarial citar na venda?",
              back: "SSO (login único) com verificação de domínio, SCIM para provisionamento, e acesso baseado em papéis com permissões granulares.",
              tags: ["security"],
            },
            {
              front: "Que recursos de governança/auditoria o Claude oferece para empresas?",
              back: "Logs de auditoria, API de compliance, controles de gasto por usuário/organização e controles de rede (ex.: allowlist de IP).",
              tags: ["security"],
            },
            {
              front: "Cuidado honesto ao falar de compliance (SOC 2, HIPAA etc.)?",
              back: "Certificações/ofertas evoluem e podem depender do plano e do canal. Não prometa um selo específico de memória; confirme na documentação/contrato o que se aplica ao caso.",
              tags: ["security", "safety"],
            },
          ],
          questions: [
            {
              prompt: "O jurídico do cliente pergunta se o conteúdo enviado será usado para treinar o modelo. Resposta correta?",
              options: [
                "\"Sim, tudo é usado para treinar.\"",
                "\"Por padrão, não — seu conteúdo não é usado para treinar os modelos.\"",
                "\"Não sei dizer.\"",
                "\"Depende do humor da equipe.\"",
              ],
              correctIndex: 1,
              explanation:
                "Por padrão, o conteúdo do cliente não é usado para treinar os modelos — argumento central de privacidade empresarial.",
              difficulty: 1,
              tags: ["security"],
            },
            {
              prompt: "Um hospital pergunta sobre dados sensíveis de pacientes. Qual conduta é responsável?",
              options: [
                "Garantir verbalmente que está 100% certificado para tudo",
                "Mencionar a oferta pronta para HIPAA e conformidade tipo SOC 2, e confirmar no contrato/documentação o que se aplica ao caso específico",
                "Dizer que compliance não importa em saúde",
                "Recomendar enviar os dados sem qualquer controle",
              ],
              correctIndex: 1,
              explanation:
                "Há oferta pronta para HIPAA e conformidade tipo SOC 2, mas o escopo depende do plano/canal — o seller confirma no contrato em vez de prometer de cabeça.",
              difficulty: 2,
              tags: ["security", "safety"],
            },
            {
              prompt: "Em uma venda para um banco regulado, quando trazer o tema de segurança e privacidade?",
              options: [
                "Só no último slide, se sobrar tempo",
                "Logo no início — frequentemente é a própria razão da compra em setores regulados",
                "Nunca, para não assustar o cliente",
                "Apenas se o cliente reclamar",
              ],
              correctIndex: 1,
              explanation:
                "Em setores regulados, segurança/privacidade costuma ser o fator decisivo; levá-la ao início destrava a aprovação.",
              difficulty: 1,
              tags: ["security", "value-prop"],
            },
          ],
          labs: [
            {
              title: "Responder ao questionário de segurança",
              promptMd: [
                "## Cenário",
                "",
                "O time de segurança de uma seguradora enviou um questionário. Responda às perguntas abaixo de forma **precisa e honesta**, sem prometer selos específicos de cabeça:",
                "",
                "1. \"Nossos dados serão usados para treinar o modelo?\"",
                "2. \"Como controlamos o acesso da nossa equipe?\"",
                "3. \"Conseguimos auditar quem usou o quê?\"",
                "4. \"Podemos manter tudo dentro da nossa nuvem AWS?\"",
                "5. \"Vocês são certificados para HIPAA/SOC 2?\"",
              ].join("\n"),
              rubric: [
                "Q1: afirma que, por padrão, os dados não são usados para treinar os modelos.",
                "Q2: cita SSO, SCIM e acesso baseado em papéis com permissões granulares.",
                "Q3: cita logs de auditoria / API de compliance.",
                "Q4: indica implantação via Amazon Bedrock para herdar a governança AWS.",
                "Q5: menciona oferta pronta para HIPAA e conformidade tipo SOC 2, MAS condiciona ao contrato/plano/canal em vez de prometer de cabeça.",
              ],
              modelAnswer: [
                "1. \"Por **padrão, não**: o conteúdo que vocês enviam **não é usado para treinar** os modelos.\"",
                "2. \"Vocês controlam acesso com **SSO** (login único com verificação de domínio), **SCIM** para provisionar/desprovisionar usuários e **acesso baseado em papéis** com permissões granulares.\"",
                "3. \"Sim: há **logs de auditoria** e **API de compliance** para acompanhar o uso.\"",
                "4. \"Podem rodar o Claude via **Amazon Bedrock**, herdando a **governança, identidade e rede da sua AWS** já aprovada.\"",
                "5. \"Existe **oferta pronta para HIPAA** e **conformidade tipo SOC 2**. Como o escopo exato depende do **plano e do canal**, eu confirmo no **contrato e na documentação oficial** o que se aplica ao caso de vocês — prefiro acertar isso por escrito a prometer de cabeça.\"",
              ].join("\n"),
            },
          ],
        },
      ],
    },
    // =====================================================================
    // MÓDULO 4 — IA RESPONSÁVEL COMO DIFERENCIAL DE VENDA
    // =====================================================================
    {
      title: "IA responsável como diferencial de venda",
      lessons: [
        {
          title: "Responsible Scaling Policy: segurança que vira confiança",
          readingMd: [
            "# Responsible Scaling Policy: segurança que vira confiança",
            "",
            "A **Responsible Scaling Policy (RSP)** é o framework público da Anthropic para **gerenciar riscos à medida que os modelos ficam mais capazes**. Para o seller, ela não é teoria acadêmica: é **prova concreta** de que a empresa por trás do produto leva risco a sério — um ativo de confiança na mesa de compras.",
            "",
            "## A ideia central, em alto nível",
            "",
            "- À medida que a capacidade dos modelos cresce, **também crescem os potenciais riscos**. A RSP define **como** a Anthropic se prepara para isso.",
            "- O framework usa **AI Safety Levels (ASL)** — níveis de segurança escalonados. Conforme um modelo cruza certos **limiares de capacidade**, são exigidos **salvaguardas mais fortes** (de implantação e de segurança).",
            "- A abordagem é descrita como **proporcional, iterativa e exportável**: as medidas crescem com o risco, evoluem com o aprendizado e podem inspirar a indústria.",
            "",
            "## Exemplos de salvaguardas (alto nível)",
            "",
            "- Controles de acesso por confiança do usuário e legitimidade do caso de uso.",
            "- Classificadores em tempo real e monitoramento para usos perigosos.",
            "- Avaliações de capacidade e *red teaming* antes de liberar modelos mais poderosos.",
            "",
            "> Não memorize definições exatas de cada ASL nem versões da política — elas evoluem. Entenda a **lógica**: mais capacidade → mais salvaguardas, de forma documentada e pública.",
            "",
            "## Por que isso vende",
            "",
            "| Necessidade do comprador | Como a RSP ajuda na venda |",
            "| --- | --- |",
            "| Reduzir risco/responsabilidade | Há um framework público e versionado de gestão de risco |",
            "| Passar no comitê de risco | Trilha de auditoria e processos formais de avaliação |",
            "| Confiar no fornecedor a longo prazo | Postura iterativa e transparente, com histórico publicado |",
            "| Diferenciar de concorrentes | Segurança no núcleo, não como remendo |",
            "",
            "## O discurso",
            "",
            "\"Vocês não estão só comprando um modelo; estão escolhendo um fornecedor que **publica** como gerencia risco conforme a IA avança. Em um comitê de risco, isso é a diferença entre um 'talvez' e um 'aprovado'.\"",
            "",
            "> Leitura oficial: https://www.anthropic.com/responsible-scaling-policy",
          ].join("\n"),
          flashcards: [
            {
              front: "O que é a Responsible Scaling Policy (RSP)?",
              back: "O framework público da Anthropic para gerenciar riscos conforme os modelos ficam mais capazes: à medida que a capacidade cresce, exigem-se salvaguardas mais fortes, de forma documentada.",
              tags: ["safety"],
            },
            {
              front: "O que são AI Safety Levels (ASL) em alto nível?",
              back: "Níveis escalonados de segurança. Quando um modelo cruza certos limiares de capacidade, salvaguardas mais fortes (de implantação e segurança) passam a ser exigidas. Não decore versões exatas — elas evoluem.",
              tags: ["safety"],
            },
            {
              front: "Como descrever a abordagem da RSP em três adjetivos?",
              back: "Proporcional (cresce com o risco), iterativa (evolui com o aprendizado) e exportável (pode inspirar a indústria).",
              tags: ["safety"],
            },
            {
              front: "Por que a RSP é um argumento de VENDA?",
              back: "Dá ao comprador um framework público e versionado de gestão de risco, com trilha de auditoria — o que ajuda a passar em comitês de risco e diferencia o fornecedor de concorrentes.",
              tags: ["safety", "value-prop"],
            },
          ],
          questions: [
            {
              prompt: "Qual é a lógica central da Responsible Scaling Policy?",
              options: [
                "Liberar qualquer modelo o mais rápido possível",
                "À medida que a capacidade do modelo cresce e cruza limiares, salvaguardas mais fortes passam a ser exigidas, de forma documentada e pública",
                "Manter todos os detalhes de segurança em segredo",
                "Reduzir salvaguardas conforme o modelo melhora",
              ],
              correctIndex: 1,
              explanation:
                "A RSP escala salvaguardas com a capacidade (níveis ASL), de modo proporcional, iterativo e público.",
              difficulty: 1,
              tags: ["safety"],
            },
            {
              prompt: "Em um comitê de risco do cliente, como a RSP é melhor posicionada?",
              options: [
                "Como um detalhe técnico irrelevante para a compra",
                "Como um framework público e versionado de gestão de risco que oferece trilha de auditoria e ajuda na aprovação",
                "Como uma promessa de que riscos não existem",
                "Como algo confidencial que não pode ser citado",
              ],
              correctIndex: 1,
              explanation:
                "Para um comitê de risco, um framework público, versionado e auditável é exatamente o tipo de evidência que destrava aprovação.",
              difficulty: 2,
              tags: ["safety", "value-prop"],
            },
            {
              prompt: "Qual é a conduta correta sobre detalhes de versões e definições exatas de ASL na venda?",
              options: [
                "Memorizar e recitar todas as versões e limiares exatos",
                "Entender a lógica (mais capacidade → mais salvaguardas) e remeter à política oficial para os detalhes atuais, que evoluem",
                "Inventar definições para soar técnico",
                "Ignorar completamente o tema",
              ],
              correctIndex: 1,
              explanation:
                "As versões/limiares evoluem; o seller domina a lógica e aponta para a política oficial atualizada.",
              difficulty: 2,
              tags: ["safety"],
            },
          ],
          labs: [
            {
              title: "Pitch para um comitê de risco",
              promptMd: [
                "## Cenário",
                "",
                "Você terá 60 segundos diante do **comitê de risco** de uma seguradora, que desconfia de IA. O CISO pergunta: *\"Por que confiaríamos no fornecedor de IA, e não só no modelo?\"*",
                "",
                "## Tarefa",
                "",
                "Escreva um pitch curto (4-6 frases) usando a **Responsible Scaling Policy** como prova de confiança, **sem** memorizar versões/limiares exatos e **sem** prometer ausência de risco.",
              ].join("\n"),
              rubric: [
                "Explica a lógica da RSP (mais capacidade → mais salvaguardas) em linguagem de negócio.",
                "Posiciona a RSP como framework PÚBLICO, versionado e auditável (útil ao comitê).",
                "NÃO promete ausência total de risco nem recita versões/limiares exatos.",
                "Conecta ao que o comitê precisa (aprovar com confiança / trilha de auditoria).",
                "Remete à política oficial para os detalhes atuais.",
              ],
              modelAnswer: [
                "\"Boa pergunta — vocês não estão comprando só um modelo, estão escolhendo **quem** o constrói. A Anthropic publica a **Responsible Scaling Policy**: conforme os modelos ficam mais capazes e cruzam certos limiares, **salvaguardas mais fortes** passam a ser exigidas, de forma **documentada e versionada**.\"",
                "\"Para o comitê de vocês, isso é ouro: existe um **framework público com trilha de auditoria**, em vez de promessas verbais.\"",
                "\"Não vou dizer que risco é zero — ninguém honesto diria —, mas vocês têm um fornecedor cuja abordagem é **proporcional ao risco e transparente**, e que melhora a política ao longo do tempo.\"",
                "\"Posso compartilhar a **política oficial atualizada** para a análise de vocês: https://www.anthropic.com/responsible-scaling-policy\"",
              ].join("\n"),
            },
          ],
        },
        {
          title: "Constitutional AI e confiança/compliance como argumento",
          readingMd: [
            "# Constitutional AI e confiança/compliance como argumento",
            "",
            "Além da RSP, a Anthropic é conhecida por uma técnica de alinhamento chamada **Constitutional AI**. Você não precisa explicá-la como engenheiro — precisa saber **traduzi-la em confiança** para o comprador.",
            "",
            "## Constitutional AI em alto nível",
            "",
            "- A ideia: em vez de depender só de pessoas rotulando cada resposta boa/ruim, o modelo é treinado para **seguir um conjunto de princípios** (uma \"constituição\") que orienta comportamento útil, honesto e inofensivo.",
            "- Resultado prático para o comprador: um modelo desenhado para ser **mais consistente em recusar usos nocivos** e em **se comportar de acordo com princípios explícitos**, em vez de regras improvisadas.",
            "- Honestidade: isso **reduz** comportamentos indesejados, mas **não garante perfeição**. Posicione como redução de risco, não como blindagem absoluta.",
            "",
            "## Por que isso vende",
            "",
            "Confiança e compliance deixaram de ser \"requisitos chatos\" e viraram **critério de escolha**. Um comprador empresarial quer poder dizer ao próprio chefe e ao regulador: *\"escolhemos um fornecedor cujo modelo é alinhado por princípios e cuja empresa publica sua política de risco\"*.",
            "",
            "| Eixo | Argumento de venda |",
            "| --- | --- |",
            "| Constitutional AI | Modelo alinhado por princípios explícitos (útil, honesto, inofensivo) |",
            "| Responsible Scaling Policy | Gestão de risco pública e escalonada com a capacidade |",
            "| Privacidade empresarial | Não treina nos dados do cliente por padrão; governança e auditoria |",
            "| Honestidade do discurso | O próprio seller não exagera — coerência da marca |",
            "",
            "## O fechamento: confiança como vantagem competitiva",
            "",
            "Quando dois fornecedores parecem técnicos e equivalentes, **confiança desempata**. O conjunto \"Constitutional AI + RSP + privacidade empresarial + um vendedor honesto\" é uma narrativa difícil de bater em setores regulados.",
            "",
            "## Cuidado final",
            "",
            "Nunca use segurança para prometer o impossível (\"é 100% seguro/infalível\"). O poder do argumento vem justamente de ser **verdadeiro e verificável**. Aponte para as fontes oficiais e deixe o cliente checar.",
            "",
            "> Leitura oficial: https://www.anthropic.com/responsible-scaling-policy",
          ].join("\n"),
          flashcards: [
            {
              front: "O que é Constitutional AI, em alto nível?",
              back: "Técnica de alinhamento em que o modelo é treinado para seguir um conjunto de princípios (uma 'constituição') que orienta comportamento útil, honesto e inofensivo, em vez de depender só de rótulos humanos caso a caso.",
              tags: ["safety"],
            },
            {
              front: "Como traduzir Constitutional AI em valor para o comprador?",
              back: "Um modelo desenhado para ser mais consistente em recusar usos nocivos e se comportar por princípios explícitos — reduzindo risco (mas sem prometer perfeição).",
              tags: ["safety", "value-prop"],
            },
            {
              front: "Por que 'confiança' é vantagem competitiva na venda de IA?",
              back: "Quando fornecedores parecem técnicos e equivalentes, confiança desempata. Constitutional AI + RSP + privacidade empresarial + um vendedor honesto formam uma narrativa forte, sobretudo em setores regulados.",
              tags: ["value-prop", "safety"],
            },
            {
              front: "Qual o cuidado ao usar segurança como argumento?",
              back: "Nunca prometer o impossível ('100% seguro/infalível'). A força vem de ser verdadeiro e verificável — aponte fontes oficiais e deixe o cliente conferir.",
              tags: ["safety", "value-prop"],
            },
          ],
          questions: [
            {
              prompt: "Qual descrição de Constitutional AI é correta e honesta?",
              options: [
                "Garante que o modelo nunca produzirá nada indesejado.",
                "Treina o modelo para seguir princípios explícitos (útil, honesto, inofensivo), reduzindo comportamentos indesejados — sem prometer perfeição.",
                "Substitui completamente qualquer necessidade de supervisão humana.",
                "É um contrato jurídico com o cliente.",
              ],
              correctIndex: 1,
              explanation:
                "Constitutional AI alinha o modelo a princípios explícitos, reduzindo (não eliminando) comportamentos indesejados.",
              difficulty: 2,
              tags: ["safety"],
            },
            {
              prompt: "Dois fornecedores de IA parecem tecnicamente equivalentes. Qual é o melhor desempate na narrativa do seller de Claude?",
              options: [
                "Prometer o menor preço a qualquer custo",
                "A combinação de confiança: Constitutional AI + Responsible Scaling Policy + privacidade empresarial + um discurso honesto",
                "Afirmar que o concorrente é inseguro sem evidência",
                "Dizer que o modelo é infalível",
              ],
              correctIndex: 1,
              explanation:
                "Em paridade técnica, a confiança desempata — e ela vem do conjunto alinhamento + política de risco + privacidade + honestidade, tudo verificável.",
              difficulty: 2,
              tags: ["value-prop", "safety"],
            },
            {
              prompt: "Um seller diz a um cliente: \"Com Constitutional AI, o modelo é 100% seguro e nunca erra\". O que há de errado?",
              options: [
                "Nada, é uma boa frase de venda",
                "Exagera uma capacidade; a técnica reduz riscos mas não garante perfeição, e a promessa quebra a confiança e contraria a honestidade da marca",
                "Está certo, mas é técnico demais",
                "O problema é só o tom",
              ],
              correctIndex: 1,
              explanation:
                "Constitutional AI reduz comportamentos indesejados, não garante perfeição. Prometer infalibilidade é desonesto e contraproducente.",
              difficulty: 1,
              tags: ["safety", "value-prop"],
            },
          ],
          labs: [
            {
              title: "Fechamento por confiança (objeção do concorrente)",
              promptMd: [
                "## Cenário",
                "",
                "Você está no fim do ciclo de vendas. O cliente diz:",
                "",
                "> \"Tecnicamente, o concorrente parece equivalente e é um pouco mais barato. Por que eu deveria escolher Claude?\"",
                "",
                "## Tarefa",
                "",
                "Escreva um fechamento (4-6 frases) que use **confiança** (Constitutional AI + RSP + privacidade empresarial + honestidade) como desempate — **sem** difamar o concorrente e **sem** prometer infalibilidade.",
              ].join("\n"),
              rubric: [
                "Reconhece a paridade técnica e o preço sem desmerecer o concorrente de forma leviana.",
                "Usa o conjunto de confiança: Constitutional AI + RSP + privacidade empresarial (não treina nos dados por padrão).",
                "Posiciona confiança como redução de risco de negócio, não como infalibilidade.",
                "Mantém honestidade (não promete '100% seguro').",
                "Encerra com um próximo passo concreto e/ou link oficial para o cliente verificar.",
              ],
              modelAnswer: [
                "\"Justo — se estão tecnicamente parecidos, a decisão deixa de ser só sobre o modelo e passa a ser sobre **risco** e **confiança**, que é onde o Claude se diferencia.\"",
                "\"O modelo é alinhado por **princípios explícitos** (Constitutional AI), a Anthropic publica sua **política de gestão de risco** (Responsible Scaling Policy) e, por padrão, **seu conteúdo não é usado para treinar** os modelos — três coisas que o seu comitê de risco vai querer ver por escrito.\"",
                "\"Não vou prometer que é infalível, porque não seria verdade; vou prometer que é **verificável** — posso te mandar as fontes oficiais para sua própria diligência.\"",
                "\"Sobre o preço: muitas vezes a diferença some quando desenhamos o caso com **arquitetura mista** (Haiku barateando a triagem). Que tal fazermos um piloto curto, com uma métrica de sucesso acordada, e você decide com dados?\"",
              ].join("\n"),
            },
          ],
        },
      ],
    },
  ],
};
